## Inicialitzacions

In [1]:
import pandas as pd
import numpy as np
from random import randrange
import copy
import random
import operator

In [2]:
#Inicialitzacions
classes=2
TimeP=35
Chromo=[]
#Chromo=np.zeros((classes, TimeP),dtype=int)
#Chromo=Chromo.tolist()
Chromo=[[[0,0] for i in range(TimeP)] for i in range(classes)]
population=5
TeachingHours=np.array([11,6,7,10,9,5])
ZerosT=np.zeros((len(TeachingHours),),dtype=int)
ZerosT=TeachingHours*0
ClassesProfe=[]
numTeachers=6
Thours=np.zeros((classes, numTeachers),dtype=int)
AssigsProfe=[[[] for i in range(numTeachers)] for i in range(classes)]
Thours=Thours.tolist()
#0->Profe a l'institut, 1-> profe no és a l'institut
TeacherNoDays=[[1,0,0,0,0],[0,1,0,0,0],[0,0,0,1,1],[0,0,0,0,0],[0,0,1,0,0],[0,0,0,0,0]]
Total_Teachers=6
#TeachersTimeTable=[[[] for i in range(TimeP)] for i in range(numTeachers)]
#TeachersTimeTable=[[0 for i in range(TimeP)] for i in range(numTeachers)]

In [3]:
ClasseAssignatura2=[[[3,1,0,0],[2,2,0,0],[4,3,0,0],[3,1,0,0],[3,4,5,0],[3,4,0,7],[3,6,0,6]],
                    [[3,1,0,0],[4,2,0,4],[3,3,0,0],[4,4,0,2],[6,5,0,0],[2,6,0,0],[2,1,0,0]]]
print(ClasseAssignatura2)
print(" ")
#ClasseAssignatura3 = ClasseAssignatura2[:]
ClasseAssignatura3 = copy.deepcopy(ClasseAssignatura2)
print(ClasseAssignatura3)
print(" ")
print(Chromo)

[[[3, 1, 0, 0], [2, 2, 0, 0], [4, 3, 0, 0], [3, 1, 0, 0], [3, 4, 5, 0], [3, 4, 0, 7], [3, 6, 0, 6]], [[3, 1, 0, 0], [4, 2, 0, 4], [3, 3, 0, 0], [4, 4, 0, 2], [6, 5, 0, 0], [2, 6, 0, 0], [2, 1, 0, 0]]]
 
[[[3, 1, 0, 0], [2, 2, 0, 0], [4, 3, 0, 0], [3, 1, 0, 0], [3, 4, 5, 0], [3, 4, 0, 7], [3, 6, 0, 6]], [[3, 1, 0, 0], [4, 2, 0, 4], [3, 3, 0, 0], [4, 4, 0, 2], [6, 5, 0, 0], [2, 6, 0, 0], [2, 1, 0, 0]]]
 
[[[0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0]], [[0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0]]]


In [4]:
def Calculate_TeachingHours():    
    c=0
    for classe in ClasseAssignatura2:

        for assignatura in classe:
            professor=assignatura[1]
            hores=assignatura[0]
            #Per casa assignatura sumam en 1 el num d'assignatures al profe que la dona
            #Només calculam les hores de profe "principal"-> REVISAR SI AIXÒ SUPOSA ALGUN PROBLEMA
            #ANAR ALERTA!!!!!!!!!!!!!!!!!!!!!!
            #Aquest valor l'utilitzarem al cost de les classes
            #print(AssigsProfe)
            #AssigsProfeh[c][professor-1].append([hores])
            #AssigProfeU[c][professor-1].append([0])
            #print(AssigsProfe)
            Thours[c][professor-1]=Thours[c][professor-1]+hores
            #Si hi ha SC:
            if assignatura[2]!=0:
                profeSC=assignatura[2]
                Thours[c][profeSC-1]=Thours[c][profeSC-1]+hores  

        c=c+1;

    print(Thours)
    

In [5]:
def getDictProfes():
    dctKTeach=[]
    dctVTeach=[]
    for classe in ClasseAssignatura2:
        idx_Assig=0
        ProfesK=[]
        Profesv=[]
        for assignatura in classe:
            #Clau del diccionari profes 
            profes=[0,0]
            profes[0]=assignatura[1]
            if assignatura[2]!=0:
                profes[1]=assignatura[2]
            if assignatura[3]!=0:
                ProfeCT=classe[assignatura[3]-1][1]
                profes[1]=ProfeCT 
            #Quan hi hagi coteaching posam només el numero de una de les assignatures l'altra està assignada de manera implicita
            #Contingut a afegir (dictvalue)
            numhores=assignatura[0]
            #[Numassignatura, hores, utilitzat]
            infoAssig=[idx_Assig+1,numhores,0]
            
            if profes in ProfesK:
                Profesv[ProfesK.index(profes)].append(infoAssig)
            else:
                ProfesK.append(profes)
                Profesv.append([infoAssig])
                

            idx_Assig=idx_Assig+1
        dctKTeach.append(ProfesK)
        dctVTeach.append(Profesv)
        
    return dctKTeach,dctVTeach

In [6]:
Thours=np.zeros((classes, numTeachers),dtype=int)
#numAssigProfe=np.zeros((classes, numTeachers),dtype=int)
AssigsProfe=[[[] for i in range(numTeachers)] for i in range(classes)]
print(AssigsProfe)
print(" ")
print(ClasseAssignatura2)
print(" ")
Calculate_TeachingHours()

d_TeachersK,d_TeachersV=getDictProfes()
classTimeT=[0 for i in range(population)]

[[[], [], [], [], [], []], [[], [], [], [], [], []]]
 
[[[3, 1, 0, 0], [2, 2, 0, 0], [4, 3, 0, 0], [3, 1, 0, 0], [3, 4, 5, 0], [3, 4, 0, 7], [3, 6, 0, 6]], [[3, 1, 0, 0], [4, 2, 0, 4], [3, 3, 0, 0], [4, 4, 0, 2], [6, 5, 0, 0], [2, 6, 0, 0], [2, 1, 0, 0]]]
 
[[6 2 4 6 3 3]
 [5 4 3 4 6 2]]


In [7]:
def IdealTeachingDayHours():
    TeacherIdealHours=[]
    for t in range (numTeachers):
        horesideals=TeachingHours[t]/(5-np.count_nonzero(TeacherNoDays[t]))
        TeacherIdealHours.append(horesideals)
    return TeacherIdealHours

In [8]:
TeacherIdealHours=IdealTeachingDayHours()

## Funcions

In [9]:
BASE=1.5
HCW=10#??????
IDWT=3
TEPW=2


In [10]:
def prova(teachers, classe_ind):
    print("---debub---",classe_ind)

In [11]:
def CTeacherUnable(teachers, hora, classe_ind, individu, costsHoresProfes):
    #print("hora",hora)
#     if classe_ind > classe-1:
#         print("CORRECCIÓ XAPUZA INDEX", classe_ind)
#         classe_ind = 1
    #print("---debub---",classe_ind)
    dia=int(hora/7)
    #print("dia",dia)
    cost=0
    #print("profes",teachers)
    
    for teacher in teachers:
        if teacher != 0: 
            #print("at School?")
            #print(teacher,dia)
            #print(TeacherNoDays[teacher-1][dia])
            #print("classe_ind",classe_ind)
            c=TeacherNoDays[teacher-1][dia]*(HCW*(BASE**3))
            costsHoresProfes[teacher-1][classe_ind][hora]=costsHoresProfes[teacher-1][classe_ind][hora]+c
            
            cost=cost+TeacherNoDays[teacher-1][dia]
            #costsTeachers[individu][teacher-1]=costsTeachers[individu][teacher-1]+(HCW*(BASE**3))
    cost = 0
    costsHoresProfe = 0
    return cost,costsHoresProfes
    

Teacher’s empty spaces: For each teacher the following subcost is added:
TEPW ∗ HOURS ∗ BASE^DAYS, where
HOURS is the total number of empty time periods in the teacher’s timetable and DAYS is the number of days that empty time periods exist in the timetable of this specific teacher


In [12]:
#HCW*BASE^BASE
def C_classEmptySpaces(individu):
    costClEmptySpaces=0
    emptyHour=False
    
    for classe in individu:
        timeP=0
        #cLessonDispersion=costClLessDispersion(classe)
        for teachers in classe:
            #Si canviam de dia resetejam les variables          
            if timeP%7==0:
                emptyHour=False
            #Si hi ha una hora buida activam empty hour  
            if teachers==[0,0]:
                emptyHour=True
            #Si hi ha una hora ocupada i prèviament hi ha hagut una hora buida el mateix dia sumam 1 al cost
            elif emptyHour==True:
                emptyHour=False
                costClEmptySpaces=costClEmptySpaces+1
            timeP=timeP+1
    cost=costClEmptySpaces*HCW*(BASE**BASE)
    return cost  

In [13]:
#Crea els horaris per cada classe i calcula lesson dispersion
def createClassTimetable(individu):
    classTimeT=[[0 for i in range(TimeP)] for i in range(classes)]
    
    dtKeys=copy.deepcopy(d_TeachersK)
    dtValues=copy.deepcopy(d_TeachersV)
    i_class=0
    costClLessonDisp=0
    #print(dtKeys)
    #print(dtValues)
    for classe in individu:
        h=0
        c_hours=0
        c_days=0
        h2=0
        for day in range(5):
            for hour in range(7):
                teachers=individu[i_class][h]
                if teachers==[0,0]:
                    classTimeT[i_class][h]=0
                else:
                    indx=dtKeys[i_class].index(teachers)
                    #Buscam la assignatura d'aquest profe/s amb valor d 'utilitzat menor
                    #que encara tengui hores per assignar
                    AssigProfe=copy.deepcopy(dtValues[i_class][indx])
                    #Ordenam de menor a major segons el valor d'utilitzat:
                    ##print("profes ",teachers)
                    ##print("index",indx)
                    ##print("AsigProfes= ",AssigProfe)
                    ##print("hora ", h)
                    AssigProfe.sort(key=lambda x: x[2])
                    #Assignam una hora d'aquesta assignatura i la marcam com utilitzada
                    #Buscam una assignatura a la que encara li quedin hores
                    i=0
                    ##print("AssigProfe ,", AssigProfe)
                    while AssigProfe[i][1]==0:
                        i=i+1
                        
                    #print("AsigProfesOrdenat= ",AssigProfe)
                    #print("Assignatura seleccionada ",AssigProfe[i][0])
                    #Guardam numAssignatura
                    classTimeT[i_class][h]=AssigProfe[i][0]
                    i_assig=dtValues[i_class][indx].index(AssigProfe[i])
                    #print("i_assig ",i_assig)
                    
                    #incrementam utilitzat
                    dtValues[i_class][indx][i_assig][2]=dtValues[i_class][indx][i_assig][2]+1
                    #idx,numhores,utilitzat
                    #Decrementam les hores 
                    dtValues[i_class][indx][i_assig][1]=dtValues[i_class][indx][i_assig][1]-1
                    #print("classTimeT ",classTimeT)
                    #print("dtValues ",dtValues)
                    #print("---------------------------")
                h=h+1
            #Canvi de dia:
            
            DaySubjects=classTimeT[i_class][h2:h2+7]
            DaySubjects=[elem for elem in DaySubjects if elem!=0]
            NumRepeatedS=len(DaySubjects)-len(set(DaySubjects))
            #print("horesDIA",NumRepeatedS)
            c_hours=c_hours+NumRepeatedS
            if NumRepeatedS >0:
                c_days=c_days+1
            h2=h2+7
           
            #Reset de utilitzat:
            t=0
            for AssigT in dtValues[i_class]:
                for assig in range(len(AssigT)):
                    dtValues[i_class][t][assig][2]=0
                t=t+1 
        #Calculam el cost del dia  IDWC ∗ HOURS ∗ BASE^DAYS:
        costClLessonDisp=costClLessonDisp+IDWT*c_hours*(BASE**c_days)
        #print("cost hores ", c_hours)
        #print("cost dies ",c_days)
        i_class=i_class+1
            
    return classTimeT,costClLessonDisp
    
    


In [14]:
#TeachersTimeTable=np.zeros((numTeachers,TimeP), dtype=int).tolist()
#print(TeachersTimeTable)
#Funció per crear l'horari de cada un dels profes per cada individu :)
#Crec que funciona bé però s'ha de repassar!!!
def createTeachersTimeP(teachers,i_classe,i_timePeriod,TeachersTimeTable):
    #print(teachers)
    for teacher in teachers:
        if teacher!=0:
            #Guardam la classe que fa aquest profe en aquesta hora
            TeachersTimeTable[teacher-1][i_timePeriod]=i_classe+1
            #TeachersTimeTable[teacher-1][i_timePeriod].append(i_classe+1)
    return TeachersTimeTable


In [15]:
def calc_C1_C2(individu,indx_individu,costsHoresProfes):
    costUnable=0
    costMore1class=0
    #TeachersTimeTable=[[[] for i in range(TimeP)] for i in range(numTeachers)]
    TeachersTimeTable=[[0 for i in range(TimeP)] for i in range(numTeachers)]
    hours=[]
    llista_classes=[]
    #llista dels profes assignats a una hora
    teacher_timeP=[]
    #for individu in population:
    for i_timePeriod in range(TimeP):
        teacher_timeP=[]
        for i_classe in range(classes):
            teachers=individu[i_classe][i_timePeriod]
            #print("profes",teachers)
            
            #Cream els horaris dels profes -> Aixo no ho empleam pero vaja
            TeachersTimeTable=createTeachersTimeP(teachers,i_classe,i_timePeriod,TeachersTimeTable)
            
            #Calculam el cost de si el profe no és a l'institut
            costU,costsHoresProfes=CTeacherUnable(teachers,i_timePeriod,i_classe,indx_individu,costsHoresProfes)
            #if costU!=0:
                #print("--------------------")
                #print(i_timePeriod)
                #print("teachers",teachers)
                #print("costU",costU)
                #print("costUnable",costUnable)

            for teach in teachers:
                if teach!=0:
                    teacher_timeP.append(teach)
                    hours.append(i_timePeriod)
                    llista_classes.append(i_classe)
            
            costUnable=costUnable+costU
            #print("cost, i_timePeriod",costU,i_timePeriod)

        #Eliminam de la llista els buits(teacher 0) ja que teacher 0 no és cap teacher
        #teacher_timeP=[elem for elem in teacher_timeP if elem != 0]
        #print(set(teacher_timeP))
        #print(teacher_timeP)
        cM1c_K=len(teacher_timeP)-len(set(teacher_timeP))
        costMore1class=costMore1class+HCW*(BASE**cM1c_K)
        #Calculate the cost for each teacher
        h3=0
        for t in teacher_timeP:
            k=teacher_timeP.count(t)-1
            teachersM1c_Cost=HCW*(BASE**k)
            costsHoresProfes[t-1][llista_classes[h3]][hours[h3]]=costsHoresProfes[t-1][llista_classes[h3]][hours[h3]]+teachersM1c_Cost
            #costsTeachers[indx_individu][teacher-1]=costsTeachers[indx_individu][teacher-1]+HCW*(BASE**k)
            h3=h3+1

    costUnable=costUnable*(HCW*(BASE**3))
    return(costUnable,costMore1class,TeachersTimeTable,costsHoresProfes)


In [16]:
#Cost Teacher empty spaces and dispersion
def CostTeacherE_i_D(idx_individu,TeachersTimeTable1,costsHoresProfes):
    costTeacherEmpty=0
    costTeacherLDisp=0
    cTeacherDisph=0
    cTeacherDispd=0
    hoursTeacher=0#num hores que fa un profe cada dia
    TotalcostTeacherDisp=0
    EmptyFound=False
    TeacherIdealHours=IdealTeachingDayHours()
    t=0#index del professor
    
    for teacher in TeachersTimeTable1:
        h=0
        chours=0#cost hores
        cdays=0 #cost dies
        for day in range(5):
            incr=False
            thr=1
            for hour in range(7):
                
                if teacher[h]!=0:
                    hoursTeacher=hoursTeacher+1
                    if abs(hoursTeacher-TeacherIdealHours[t])>=thr:
                        clP_idx = teacher[h] - 1
                        costsHoresProfes[t][clP_idx][h]=costsHoresProfes[t][clP_idx][h]+IDWT*BASE
                        thr=thr+1
                        
                    #Si trobam una hora ocupada després de trobar un espai buit
                    if EmptyFound==True:
                        costsHoresProfes[t][clP_idx][h]=costsHoresProfes[t][clP_idx][h]+TEPW*BASE
                        chours=chours+1
                        incr=True
                        EmptyFound=False
                    
                elif teacher[h]==0:
                    EmptyFound=True
                    
                h=h+1#index de les hores
                
            #Quan canviam de dia incrementam el cost del dia i resetejam els paràmetres:
            #Si les hores que fa un professor un dia es desvien en més de 1 de la mitjana ideal:
            hour_difference=abs(hoursTeacher-TeacherIdealHours[t])
            if hour_difference >= 1:
                cTeacherDisph=cTeacherDisph+hour_difference
                cTeacherDispd=cTeacherDispd+1
            if incr==True:
                cdays=cdays+1
            hoursTeacher=0
            incr=False
            EmptyFound=False
            
        #Càlcul del cost de lesson's dispersion
        costTLD=IDWT*cTeacherDisph*(BASE**cTeacherDispd)
        costTeacherLDisp=costTeacherLDisp+costTLD
        #costsTeachers[idx_individu][t-1]=costsTeachers[idx_individu][t-1]+costTLD
        
        #Aquí calcul del cost de Empty Scpaces
        costES=TEPW*chours*(BASE**cdays)
        costTeacherEmpty=costTeacherEmpty+costES
        #costsTeachers[idx_individu][t-1]=costsTeachers[idx_individu][t-1]+costES
        
        t=t+1
        cTeacherDisph=0
        cTeacherDispd=0
        
    return costTeacherLDisp,costTeacherEmpty,costsHoresProfes
            

In [17]:
#costs timeP -> Per cada teacher llista amb els costs dels 35 timePeriods *el num de individus
costsHoresProfes=[[0 for i in range(35)] for i in range(numTeachers)]
cTeacherTimeP=[]
cTeacherTimeP.append(costsHoresProfes)
cTeacherTimeP.append(costsHoresProfes)
print(cTeacherTimeP[0])

[[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]]


. Teacher lessons’ dispersion: For each teacher the following subcost is added: 
IDWT ∗ HOURS ∗ BASE^DAYS
, where HOURS is the total number of time periods that are different compared to the ideal dispersion teacher’s timetable and DAYS is the number of days in the teacher’s timetable that such a declination from the ideal case exists

In [18]:
def costFunction(pobl):    
    #costsTeachers=[[0 for i in range(numTeachers)] for i in range(population)] #declarar antes de cridar funcio
    costs=[0 for i in range(len(pobl))]
    costsHoresProfes=[[[0 for i in range(35)] for i in range(classes)] for i in range(numTeachers)]
    print("costsHoresProfes", costsHoresProfes)
    cTeacherTimeP=[]
    costsTimeP=[]
    idx_individu=0
    
    
    for individu in pobl:
        #print("costs ",costs)
        #print("idx_individu ",idx_individu)
        
        #TeachersTimeTable=[[0 for i in range(TimeP)] for i in range(numTeachers)]

        cTU,cM1cl,TeachersTimeTable,costsHoresProfes=calc_C1_C2(individu,idx_individu,costsHoresProfes)
        print("costsHoresProfes 1: ", costsHoresProfes)
        
        cES=C_classEmptySpaces(individu)

        cTE,cTLD,costsHoresProfes=CostTeacherE_i_D(idx_individu,TeachersTimeTable,costsHoresProfes)
        print("costsHoresProfes 2: ", costsHoresProfes)
        
        classTimeT[idx_individu],cClassLDisp=createClassTimetable(individu)
#         print("cTU ",cTU)
#         print("cM1cl ",cM1cl)
#         print("cES",cES)
#         print("cTE ",cTE)
#         print("cTLD ",cTLD)
#         print("cClassLDisp ",cClassLDisp)

        TotalCost=cTU+cM1cl+cES+cTE+cTLD+cClassLDisp

        #print("CTEACH!",costsTeachers)
        
        costs[idx_individu] = TotalCost
        idx_individu=idx_individu+1
#         for i in range(len(costsHoresProfes)):
#             print("cProfesH",costsHoresProfes[i])
#         print("costs de l'individu ",idx_individu)
#         print("costs ",costs[idx_individu-1])

        cTeacherTimeP.append(costsHoresProfes)
        print("costsHoresProfes 3: ", costsHoresProfes)
    return costs,costsHoresProfes


In [19]:
#Recorrem les assignatures d'una classe
#[slots,professor1,professorSC,AssignaturaCT]

def decrementarHores(teacher,classe,Thours):
    #Recorrem les assignatures de la classe buscant les que fa el profe teacher
    #c= assignatures de la classe 1
    
    idxAssigntr=0

    c=ClasseAssignatura3[classe][:]

    for assignatura in c:

        if assignatura[1]==teacher and assignatura[0]>0:

            #Decrementam 
            ClasseAssignatura3[classe][idxAssigntr][0]=ClasseAssignatura3[classe][idxAssigntr][0]-1
            Thours[classe][teacher-1]=Thours[classe][teacher-1]-1
            teachers=[teacher,0]
          
            
            #si hi ha SC les decrementam de Thours
            if ClasseAssignatura3[classe][idxAssigntr][2]!=0:
                
                teacher2=ClasseAssignatura3[classe][idxAssigntr][2]
               
                Thours[classe][teacher2-1]=Thours[classe][teacher2-1]-1
                teachers=[teacher,teacher2]
               
                
            #Si hi ha coteaching llevam les hores de l'altra assignatura:
            if ClasseAssignatura3[classe][idxAssigntr][3]!=0:
                #Seleccionam el valor de l'index de l'assignatura amb la que hi ha coteaching
                AssigCT=ClasseAssignatura3[classe][idxAssigntr][3]
                
                #Decrementam en 1h les hores pendents d'assignar de l'assignatura de CT
                ClasseAssignatura3[classe][AssigCT-1][0]=ClasseAssignatura3[classe][AssigCT-1][0]-1
                teacherCT=ClasseAssignatura3[classe][AssigCT-1][1]
                Thours[classe][teacherCT-1]=Thours[classe][teacherCT-1]-1
                teachers=[teacher,teacherCT]
                
            
            break
                
        idxAssigntr=idxAssigntr+1
    #c=ClasseAssignatura3[classe][:]
    
    #print("ClasseAssignatura3 decrem",ClasseAssignatura3)
    return Thours,teachers
                
        

In [20]:
def mutation(pob, ctp):
    period_mutation_probability = 0.05
    bad_mutation_probability = 0.05

    pob_mutada=copy.deepcopy(pob)
    pob_final=copy.deepcopy(pob)


    # Botam el primer individu per no modificar la millor opcio
    for i_individu in range(1,len(pob_mutada)):
        
        for i_classe in range(len(pob_mutada[i_individu])):
            
            # ------------------------------------------------Period mutation
            if random.random() < period_mutation_probability:
                
                random_tp_1 = random.randrange(0, len(pob[i_individu][i_classe]))
                random_tp_2 = random.randrange(0, len(pob[i_individu][i_classe]))

                tp_1 = pob[i_individu][i_classe][random_tp_1]
                tp_2 = pob[i_individu][i_classe][random_tp_2]
        
                pob_mutada[i_individu][i_classe][random_tp_1] = tp_2
                pob_mutada[i_individu][i_classe][random_tp_2] = tp_1

#                 print("Individu mutat: ",i_individu)
#                 print("--- CLASSE MUTADA ---", i_classe)
#                 print("Periode 1 ", random_tp_1)
#                 print("Periode 2 ", random_tp_2)

            
            # ------------------------------------------------Bad mutation
            found_tp = False
            
            if random.random() < bad_mutation_probability:
                while found_tp == False:
                    
                    ctp[i_individu][i_class]
                    
                    # Comprobar TeacherNoDays
                    dia_t_1 = int(m_idx_tp/7)
                    dia_t_2 = int(m2_idx_tp/7)
                    print("Dies: ", dia_t_1, dia_t_2)
                    print("Teacher no days: ", TeacherNoDays[m_idx_t], TeacherNoDays[m_idx_t])
                    if (TeacherNoDays[m_idx_t][dia_t_1] == 0) & (TeacherNoDays[m2_idx_t][dia_t_2] == 0):
                        found_tp = True
                
                tp_1 = pob[m_idx_i][i_classe][random_tp_1]
                tp_2 = pob[i_individu][i_classe][random_tp_2]
        
                pob_mutada[i_individu][i_classe][random_tp_1] = tp_2
                pob_mutada[i_individu][i_classe][random_tp_2] = tp_1
                        
                
                
                
    for i in range(len(pob)):
        print("individu",i)
        print("ORIGINAL", pob[i][0])
        print(pob[i][1])
        print("MUTAT   ", pob_mutada[i][0])
        print(pob_mutada[i][1])
    
#     print(individusHanMutat)
#     print("P_ORI", pob)
#     print("P_MUT", pob_mutada)
#    print("Son iguals??????? ",pob_mutada==pob)

    return pob_mutada

## Creació de la primera població

In [21]:
poblacio=[0 for i in range(population)]
for i in range(population):
    Thours=np.zeros((classes, numTeachers),dtype=int)
    Calculate_TeachingHours()
    ClasseAssignatura3=copy.deepcopy(ClasseAssignatura2)
    for classe in range(classes):
        for hour in range(TimeP):
            c=copy.deepcopy(ClasseAssignatura2[classe])
            ok=False
            #Chose a teacher at random 
            print("classe= ",classe)
            print(Thours[classe])
            
            # Miram si s'han assignat totes les hores d'una classe.
            if np.array_equal(ZerosT,Thours[classe])==False:
                while ok==False:#mirar que no sigui que no et quedin profes i se quedi aqui infinitament
                    teacher=randrange(1, numTeachers+1)
                    print("teacher",teacher)
                    for j in c:
                        #print("i",i) 
                        #print("c",c)
                        #print("i[1]",i[1])
                        #print(Thours[classe][teacher-1])
                        if(j[1]==teacher) and Thours[classe][teacher-1]!=0:
                            ok=True
                    #ok=True       
                print("thours",Thours[classe][teacher-1])
                print("selected teacher", teacher)
                print("decrementam ")
                Thours,teachers=decrementarHores(teacher,classe,Thours)
                print("classe",classe)
                print("hours",hour)                
                Chromo[classe][hour]=teachers
                print("TeacherHours, teachers :",Thours[classe], teachers)

                print(teachers)
                
            
                #Assignar slot buit
            print("buit")
    print("index",i)      
    poblacio[i]=copy.deepcopy(Chromo)
    #break

                            
                

                        
                #Now we have a teacher!!!
                #print(teacher)

                #Decrementam les hores agafant una hora en concret d'una assignatura
                
                #TeachingHours[teacher-1]=TeachingHours[teacher-1]-1
                #TeachingHours=a
      

        
#Si algun teacher només està de subclasse mai el decrementa directament !Alerta!  

[[6 2 4 6 3 3]
 [5 4 3 4 6 2]]
classe=  0
[6 2 4 6 3 3]
teacher 5
teacher 1
thours 6
selected teacher 1
decrementam 
classe 0
hours 0
TeacherHours, teachers : [5 2 4 6 3 3] [1, 0]
[1, 0]
buit
classe=  0
[5 2 4 6 3 3]
teacher 2
thours 2
selected teacher 2
decrementam 
classe 0
hours 1
TeacherHours, teachers : [5 1 4 6 3 3] [2, 0]
[2, 0]
buit
classe=  0
[5 1 4 6 3 3]
teacher 4
thours 6
selected teacher 4
decrementam 
classe 0
hours 2
TeacherHours, teachers : [5 1 4 5 2 3] [4, 5]
[4, 5]
buit
classe=  0
[5 1 4 5 2 3]
teacher 4
thours 5
selected teacher 4
decrementam 
classe 0
hours 3
TeacherHours, teachers : [5 1 4 4 1 3] [4, 5]
[4, 5]
buit
classe=  0
[5 1 4 4 1 3]
teacher 4
thours 4
selected teacher 4
decrementam 
classe 0
hours 4
TeacherHours, teachers : [5 1 4 3 0 3] [4, 5]
[4, 5]
buit
classe=  0
[5 1 4 3 0 3]
teacher 3
thours 4
selected teacher 3
decrementam 
classe 0
hours 5
TeacherHours, teachers : [5 1 3 3 0 3] [3, 0]
[3, 0]
buit
classe=  0
[5 1 3 3 0 3]
teacher 6
thours 3
selected 

buit
index 1
[[6 2 4 6 3 3]
 [5 4 3 4 6 2]]
classe=  0
[6 2 4 6 3 3]
teacher 4
thours 6
selected teacher 4
decrementam 
classe 0
hours 0
TeacherHours, teachers : [6 2 4 5 2 3] [4, 5]
[4, 5]
buit
classe=  0
[6 2 4 5 2 3]
teacher 2
thours 2
selected teacher 2
decrementam 
classe 0
hours 1
TeacherHours, teachers : [6 1 4 5 2 3] [2, 0]
[2, 0]
buit
classe=  0
[6 1 4 5 2 3]
teacher 1
thours 6
selected teacher 1
decrementam 
classe 0
hours 2
TeacherHours, teachers : [5 1 4 5 2 3] [1, 0]
[1, 0]
buit
classe=  0
[5 1 4 5 2 3]
teacher 1
thours 5
selected teacher 1
decrementam 
classe 0
hours 3
TeacherHours, teachers : [4 1 4 5 2 3] [1, 0]
[1, 0]
buit
classe=  0
[4 1 4 5 2 3]
teacher 3
thours 4
selected teacher 3
decrementam 
classe 0
hours 4
TeacherHours, teachers : [4 1 3 5 2 3] [3, 0]
[3, 0]
buit
classe=  0
[4 1 3 5 2 3]
teacher 6
thours 3
selected teacher 6
decrementam 
classe 0
hours 5
TeacherHours, teachers : [4 1 3 4 2 2] [6, 4]
[6, 4]
buit
classe=  0
[4 1 3 4 2 2]
teacher 3
thours 3
select

classe=  1
[1 1 0 1 4 0]
teacher 3
teacher 1
thours 1
selected teacher 1
decrementam 
classe 1
hours 14
TeacherHours, teachers : [0 1 0 1 4 0] [1, 0]
[1, 0]
buit
classe=  1
[0 1 0 1 4 0]
teacher 4
thours 1
selected teacher 4
decrementam 
classe 1
hours 15
TeacherHours, teachers : [0 0 0 0 4 0] [4, 2]
[4, 2]
buit
classe=  1
[0 0 0 0 4 0]
teacher 6
teacher 4
teacher 3
teacher 1
teacher 5
thours 4
selected teacher 5
decrementam 
classe 1
hours 16
TeacherHours, teachers : [0 0 0 0 3 0] [5, 0]
[5, 0]
buit
classe=  1
[0 0 0 0 3 0]
teacher 3
teacher 3
teacher 4
teacher 3
teacher 4
teacher 6
teacher 6
teacher 2
teacher 4
teacher 1
teacher 3
teacher 4
teacher 1
teacher 2
teacher 4
teacher 4
teacher 4
teacher 6
teacher 5
thours 3
selected teacher 5
decrementam 
classe 1
hours 17
TeacherHours, teachers : [0 0 0 0 2 0] [5, 0]
[5, 0]
buit
classe=  1
[0 0 0 0 2 0]
teacher 2
teacher 4
teacher 3
teacher 3
teacher 5
thours 2
selected teacher 5
decrementam 
classe 1
hours 18
TeacherHours, teachers : [0 

In [22]:
# te=[2,0]
# for t in te:
#     print(t)
# costus,cTeacherTimeP=costFunction(poblacio)
# print(" ")
# print(cTeacherTimeP)

## Loop iteratiu

In [23]:
N = population
n_min = 0.2
n_max = 2 - n_min
    
probability = []

# Calcul de probabilitat de reproduccio
for i in range(N):
    probability.append((1/N)*(n_min+(n_max - n_min)*(i)/(N-1)))
    #probability.append(np.divide(1,N)*np.divide(n_min+(n_max - n_min)*(i-1),(N-1)))
    
# Vector de probabilitats de reproduccio
mapped = []
mapped.append(0)

for i in range(len(probability)-1):
    mapped.append(mapped[i] + probability[i])

mapped.append(1)

In [24]:
for i in range(100):
    print("===============================================================[{}]".format(i))
    #print('I love {} for "{}!"'.format('Geeks', 'Geeks'))
    costsTeachers=[[0 for i in range(numTeachers)] for i in range(population)]
    calculatedCosts,x = costFunction(poblacio)
    print("costs", calculatedCosts)
    
    #-------------------------------------------------------- SELECCIÓ
    # Creació d'un diccionari per ordenar els individus per cost.
    costs={}
    for i in range(population):
        costs[i]=calculatedCosts[i]
    print(costs)

    sorted_costs = sorted(costs.items(), key=operator.itemgetter(1))
    sorted_costs.reverse()
    print(sorted_costs)
    
    # Creació de la nova poblacio   
    nova_poblacio = copy.deepcopy(poblacio)

    # Elitism: aseguram que el millor cromosoma pasa a la següent generacio
    #nova_poblacio.append(poblacio[sorted_costs[-1][0]])
    nova_poblacio[0] = poblacio[sorted_costs[-1][0]]
    
    print("MINIM",sorted_costs[-1])
#     print("R",poblacio[sorted_costs[-1][0]])
#     print("T",nova_poblacio[0])

    # Selecció dels individus a reproduir
    for i in range(N-1):
        rand = random.random()
        for i in range(len(probability)):
            if (rand > mapped[i]) & (rand <= mapped[i+1]):
                cromo_index = i
                break
        # Aqui s'ha triat el cromosoma que s'ha de reproduir. Ara l'hem de reproduir
        
        #nova_poblacio.append(poblacio[sorted_costs[cromo_index][0]])
        nova_poblacio[i] = poblacio[sorted_costs[cromo_index][0]]
    
    
    
    #-------------------------------------------------------- MUTACIÓ
    poblacio_a_mutar = copy.deepcopy(nova_poblacio)
    
    costsTeachers=[[0 for i in range(numTeachers)] for i in range(population)]
    
    calculatedCosts,ctp_am = costFunction(poblacio_a_mutar)
    print("ctp_am",ctp_am)
    poblacio_mutada = mutation(poblacio_a_mutar, ctp_am)
    p = copy.deepcopy(poblacio_mutada)
    
    costsTeachers=[[0 for i in range(numTeachers)] for i in range(population)]
    calculatedCosts,x = costFunction(p)
    print("costM",calculatedCosts)
    
    for i in range(len(nova_poblacio)):
        print("iguals?¿¿?", nova_poblacio[i]==poblacio_mutada[i])
        

    poblacio = copy.deepcopy(poblacio_mutada)
    

===============================================================[0]
costsHoresProfes [[[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]], [[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]], [[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]], [[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]], [[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0

costsHoresProfes 2:  [[[333.25, 10.0, 44.25, 33.75, 0, 0, 0, 0, 0, 7.5, 0, 10.5, 0.0, 0.0, 4.5, 7.5, 0.0, 0.0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [55.0, 0, 75.0, 0, 0, 0, 36.75, 0, 0, 7.5, 0.0, 0, 0, 3.0, 4.5, 0.0, 0, 0.0, 9.0, 9.0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]], [[100.0, 10.0, 0, 0, 0.0, 0, 7.5, 0, 3.0, 0, 3.0, 33.75, 0, 33.75, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [90.0, 13.0, 4.5, 3.0, 7.5, 0, 3.0, 33.75, 33.75, 36.75, 33.75, 3.0, 0, 36.75, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]], [[205.0, 17.5, 0.0, 0, 0.0, 0.0, 0.0, 0, 7.5, 7.5, 0.0, 0, 10.5, 0, 4.5, 0, 3.0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [25.0, 0, 0, 15.0, 0, 3.0, 3.0, 0, 0, 0, 0, 0.0, 0.0, 0, 4.5, 0, 7.5, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]], [[204.5, 65.0, 0.0, 3.0, 4.5, 9.0, 0.0, 9.0, 0.0, 3.0, 7.5, 0, 0, 7.5, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [89.5, 7.5, 3.0, 0.0, 3.0, 0, 7

NameError: name 'm_idx_tp' is not defined

*Teacher unavailability: For each teacher and for each time period this teacher is assigned to a class, while he/she is unavailable at school the corresponding day, the following cost is added: HCW ∗ BASE3.

*Teacher assigned in more than one class: For each teacher and for each time period, if this teacher is assigned to more than one class, for example, to k classes, the following cost is added: HCW ∗ BASEk


Teacher lessons’ dispersion: For each teacher the following subcost is added: IDWT ∗ HOURS ∗ BASEDAYS, where
HOURS is the total number of time periods that are different compared to the ideal dispersion teacher’s timetable
and DAYS is the number of days in the teacher’s timetable that such a declination from the ideal case exists.