In [71]:
import pandas as pd
import numpy as np
import random
from random import randrange
import copy

In [72]:
#Inicialitzacions
classes=2
TimeP=35
Chromo=[]
#Chromo=np.zeros((classes, TimeP),dtype=int)
#Chromo=Chromo.tolist()
Chromo=[[[0,0] for i in range(TimeP)] for i in range(classes)]
population=5
TeachingHours=np.array([11,6,7,10,9,5])
ZerosT=np.zeros((len(TeachingHours),),dtype=int)
ZerosT=TeachingHours*0
ClassesProfe=[]
numTeachers=6
Thours=np.zeros((classes, numTeachers),dtype=int)
AssigsProfe=[[[] for i in range(numTeachers)] for i in range(classes)]
Thours=Thours.tolist()
#0->Profe a l'institut, 1-> profe no és a l'institut
TeacherNoDays=[[1,0,0,0,0],[0,1,0,0,0],[0,0,0,0,0],[0,0,0,0,0],[0,0,0,0,0],[0,0,0,0,0]]
Total_Teachers=6
#TeachersTimeTable=[[[] for i in range(TimeP)] for i in range(numTeachers)]
TeachersTimeTable=[[0 for i in range(TimeP)] for i in range(numTeachers)]

In [137]:
ClasseAssignatura2=[[[3,1,0,0],[2,2,0,0],[4,3,0,0],[3,1,0,0],[3,4,5,0],[3,4,0,7],[3,6,0,6]],
                    [[3,1,0,0],[4,2,0,4],[3,3,0,0],[4,4,0,2],[6,5,0,0],[2,6,0,0],[2,1,0,0]]]
print(ClasseAssignatura2)
print(" ")
#ClasseAssignatura3 = ClasseAssignatura2[:]
ClasseAssignatura3 = copy.deepcopy(ClasseAssignatura2)
print(ClasseAssignatura3)
print(" ")
print(Chromo)

[[[3, 1, 0, 0], [2, 2, 0, 0], [4, 3, 0, 0], [3, 1, 0, 0], [3, 4, 5, 0], [3, 4, 0, 7], [3, 6, 0, 6]], [[3, 1, 0, 0], [4, 2, 0, 4], [3, 3, 0, 0], [4, 4, 0, 2], [6, 5, 0, 0], [2, 6, 0, 0], [2, 1, 0, 0]]]
 
[[[3, 1, 0, 0], [2, 2, 0, 0], [4, 3, 0, 0], [3, 1, 0, 0], [3, 4, 5, 0], [3, 4, 0, 7], [3, 6, 0, 6]], [[3, 1, 0, 0], [4, 2, 0, 4], [3, 3, 0, 0], [4, 4, 0, 2], [6, 5, 0, 0], [2, 6, 0, 0], [2, 1, 0, 0]]]
 
[[[6, 4], [1, 0], [1, 0], [3, 0], [2, 0], [3, 0], [3, 0], [1, 0], [1, 0], [6, 4], [3, 0], [1, 0], [1, 0], [4, 5], [6, 4], [4, 5], [2, 0], [4, 5], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0]], [[3, 0], [6, 0], [2, 4], [3, 0], [4, 2], [2, 4], [6, 0], [5, 0], [1, 0], [2, 4], [1, 0], [1, 0], [1, 0], [3, 0], [5, 0], [1, 0], [5, 0], [5, 0], [5, 0], [5, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0]]]


In [140]:
def getDictProfes():
    dctKTeach=[]
    dctVTeach=[]
    for classe in ClasseAssignatura2:
        idx_Assig=0
        ProfesK=[]
        Profesv=[]
        for assignatura in classe:
            #Clau del diccionari profes 
            profes=[0,0]
            profes[0]=assignatura[1]
            if assignatura[2]!=0:
                profes[1]=assignatura[2]
            if assignatura[3]!=0:
                ProfeCT=classe[assignatura[3]-1][1]
                profes[1]=ProfeCT 
            #Quan hi hagi coteaching posam només el numero de una de les assignatures l'altra està assignada de manera implicita
            #Contingut a afegir (dictvalue)
            numhores=assignatura[0]
            #[Numassignatura, hores, utilitzat]
            infoAssig=[idx_Assig+1,numhores,0]
            
            if profes in ProfesK:
                Profesv[ProfesK.index(profes)].append(infoAssig)
            else:
                ProfesK.append(profes)
                Profesv.append([infoAssig])
                

            idx_Assig=idx_Assig+1
        dctKTeach.append(ProfesK)
        dctVTeach.append(Profesv)
        
    return dctKTeach,dctVTeach


In [144]:
d_TeachersK,d_TeachersV=getDictProfes()
print(d_TeachersK)
print(" ")
print(ClasseAssignatura2)
print(" ")
#[Numassignatura, hores, utilitzat]
print(d_TeachersV)

[[[1, 0], [2, 0], [3, 0], [4, 5], [4, 6], [6, 4]], [[1, 0], [2, 4], [3, 0], [4, 2], [5, 0], [6, 0]]]
 
[[[3, 1, 0, 0], [2, 2, 0, 0], [4, 3, 0, 0], [3, 1, 0, 0], [3, 4, 5, 0], [3, 4, 0, 7], [3, 6, 0, 6]], [[3, 1, 0, 0], [4, 2, 0, 4], [3, 3, 0, 0], [4, 4, 0, 2], [6, 5, 0, 0], [2, 6, 0, 0], [2, 1, 0, 0]]]
 
[[[[1, 3, 0], [4, 3, 0]], [[2, 2, 0]], [[3, 4, 0]], [[5, 3, 0]], [[6, 3, 0]], [[7, 3, 0]]], [[[1, 3, 0], [7, 2, 0]], [[2, 4, 0]], [[3, 3, 0]], [[4, 4, 0]], [[5, 6, 0]], [[6, 2, 0]]]]


In [82]:
print(poblacio[0])
min()

[[[2, 0], [6, 4], [1, 0], [1, 0], [4, 5], [3, 0], [3, 0], [6, 4], [2, 0], [3, 0], [1, 0], [6, 4], [4, 5], [1, 0], [3, 0], [1, 0], [1, 0], [4, 5], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0]], [[3, 0], [1, 0], [6, 0], [5, 0], [1, 0], [1, 0], [6, 0], [2, 4], [1, 0], [5, 0], [5, 0], [2, 4], [4, 2], [3, 0], [5, 0], [5, 0], [5, 0], [1, 0], [2, 4], [3, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0]]]


In [185]:
#Crea els horaris per cada classe i calcula lesson dispersion
def createClassTimetable(individu):
    classTimeT=[[0 for i in range(TimeP)] for i in range(classes)]
    
    dtKeys=copy.deepcopy(d_TeachersK)
    dtValues=copy.deepcopy(d_TeachersV)
    i_class=0
    costClLessonDisp=0
  
    for classe in individu:
        h=0
        c_hours=0
        c_days=0
        h2=0
        for day in range(5):
            for hour in range(7):
                teachers=individu[i_class][h]
                if teachers==[0,0]:
                    classTimeT[i_class][h]=0
                else:
                    indx=dtKeys[i_class].index(teachers)
                    #Buscam la assignatura d'aquest profe/s amb valor d 'utilitzat menor
                    #que encara tengui hores per assignar
                    AssigProfe=copy.deepcopy(dtValues[i_class][indx])
                    #Ordenam de menor a major segons el valor d'utilitzat:
                    #print("profes ",teachers)
                    #print("index",indx)
                    #print("AsigProfes= ",AssigProfe)
                    #print("hora ", h)
                    AssigProfe.sort(key=lambda x: x[2])
                    #Assignam una hora d'aquesta assignatura i la marcam com utilitzada
                    #Buscam una assignatura a la que encara li quedin hores
                    i=0
                    while AssigProfe[i][1]==0:
                        i=i+1
                        
                    #print("AsigProfesOrdenat= ",AssigProfe)
                    #print("Assignatura seleccionada ",AssigProfe[i][0])
                    #Guardam numAssignatura
                    classTimeT[i_class][h]=AssigProfe[i][0]
                    i_assig=dtValues[i_class][indx].index(AssigProfe[i])
                    #print("i_assig ",i_assig)
                    
                    #incrementam utilitzat
                    dtValues[i_class][indx][i_assig][2]=dtValues[i_class][indx][i_assig][2]+1
                    #idx,numhores,utilitzat
                    #Decrementam les hores 
                    dtValues[i_class][indx][i_assig][1]=dtValues[i_class][indx][i_assig][1]-1
                    #print("classTimeT ",classTimeT)
                    #print("dtValues ",dtValues)
                    #print("---------------------------")
                h=h+1
            #Canvi de dia:
            
            DaySubjects=classTimeT[i_class][h2:h2+7]
            DaySubjects=[elem for elem in DaySubjects if elem!=0]
            NumRepeatedS=len(DaySubjects)-len(set(DaySubjects))
            print("horesDIA",NumRepeatedS)
            c_hours=c_hours+NumRepeatedS
            if NumRepeatedS >0:
                c_days=c_days+1
            h2=h2+7
           
            #Reset de utilitzat:
            t=0
            for AssigT in dtValues[i_class]:
                for assig in range(len(AssigT)):
                    dtValues[i_class][t][assig][2]=0
                t=t+1 
        #Calculam el cost del dia  IDWC ∗ HOURS ∗ BASE^DAYS:
        costClLessonDisp=costClLessonDisp+IDWC*c_hours*(BASE**c_days)
        print("cost hores ", c_hours)
        print("cost dies ",c_days)
        i_class=i_class+1
            
    return classTimeT,costClLessonDisp
    
    


In [186]:
print(poblacio[0])
print(" ")
print("keys",d_TeachersK)
print(" ")
print("values",d_TeachersV)
print(" ")
cTT, cost=createClassTimetable(poblacio[0])
print(cTT[0])
print(cTT[0][0:7])
print(cTT[0][7:14])
print(cTT[0][14:21])
print(" ")
print(cTT[1])
print(cTT[1][0:7])
print(cTT[1][7:14])
print(cTT[1][14:21])

[[[2, 0], [6, 4], [1, 0], [1, 0], [4, 5], [3, 0], [3, 0], [6, 4], [2, 0], [3, 0], [1, 0], [6, 4], [4, 5], [1, 0], [3, 0], [1, 0], [1, 0], [4, 5], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0]], [[3, 0], [1, 0], [6, 0], [5, 0], [1, 0], [1, 0], [6, 0], [2, 4], [1, 0], [5, 0], [5, 0], [2, 4], [4, 2], [3, 0], [5, 0], [5, 0], [5, 0], [1, 0], [2, 4], [3, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0]]]
 
keys [[[1, 0], [2, 0], [3, 0], [4, 5], [4, 6], [6, 4]], [[1, 0], [2, 4], [3, 0], [4, 2], [5, 0], [6, 0]]]
 
values [[[[1, 3, 0], [4, 3, 0]], [[2, 2, 0]], [[3, 4, 0]], [[5, 3, 0]], [[6, 3, 0]], [[7, 3, 0]]], [[[1, 3, 0], [7, 2, 0]], [[2, 4, 0]], [[3, 3, 0]], [[4, 4, 0]], [[5, 6, 0]], [[6, 2, 0]]]]
 
horesDIA 1
horesDIA 1
horesDIA 0
horesDIA 0
horesDIA 0


NameError: name 'IDWC' is not defined

In [ ]:
#Crea els horaris per cada classe i calcula lesson dispersion
#Aixo crea els horaris bé
def createClassTimetable(individu):
    classTimeT=[[0 for i in range(TimeP)] for i in range(classes)]
    
    dtKeys=copy.deepcopy(d_TeachersK)
    dtValues=copy.deepcopy(d_TeachersV)
    i_class=0
    for classe in individu:
        h=0
        for day in range(5):
            for hour in range(7):
                teachers=individu[i_class][h]
                if teachers==[0,0]:
                    classTimeT[i_class][h]=0
                else:
                    indx=dtKeys[i_class].index(teachers)
                    #Buscam la assignatura d'aquest profe/s amb valor d 'utilitzat menor
                    #que encara tengui hores per assignar
                    AssigProfe=copy.deepcopy(dtValues[i_class][indx])
                    #Ordenam de menor a major segons el valor d'utilitzat:
                    print("profes ",teachers)
                    print("index",indx)
                    print("AsigProfes= ",AssigProfe)
                    print("hora ", h)
                    AssigProfe.sort(key=lambda x: x[2])
                    #Assignam una hora d'aquesta assignatura i la marcam com utilitzada
                    #Buscam una assignatura a la que encara li quedin hores
                    i=0
                    while AssigProfe[i][1]==0:
                        i=i+1
                        #Sempre quedaran hores, no?
                    print("AsigProfesOrdenat= ",AssigProfe)
                    print("Assignatura seleccionada ",AssigProfe[i][0])
                    #Guardam numAssignatura
                    classTimeT[i_class][h]=AssigProfe[i][0]
                    i_assig=dtValues[i_class][indx].index(AssigProfe[i])
                    print("i_assig ",i_assig)
                    
                    #incrementam utilitzat
                    dtValues[i_class][indx][i_assig][2]=dtValues[i_class][indx][i_assig][2]+1
                    #idx,numhores,utilitzat
                    #Decrementam les hores 
                    dtValues[i_class][indx][i_assig][1]=dtValues[i_class][indx][i_assig][1]-1
                    print("classTimeT ",classTimeT)
                    print("dtValues ",dtValues)
                    print("---------------------------")
                h=h+1
            #Canvi de dia:
            #Reset de utilitzat:
            t=0
            for AssigT in dtValues[i_class]:
                for assig in range(len(AssigT)):
                    dtValues[i_class][t][assig][2]=0
                t=t+1 
                    
        i_class=i_class+1
            
    return classTimeT
    
    


In [76]:
def Calculate_TeachingHours():
    c=0
    
    for classe in ClasseAssignatura2:
        
        for assignatura in classe:
            professor=assignatura[1]
            hores=assignatura[0]
            #Per casa assignatura sumam en 1 el num d'assignatures al profe que la dona
            #Només calculam les hores de profe "principal"-> REVISAR SI AIXÒ SUPOSA ALGUN PROBLEMA
            #ANAR ALERTA!!!!!!!!!!!!!!!!!!!!!!
            #Aquest valor l'utilitzarem al cost de les classes
            #print(AssigsProfe)
            #AssigsProfeh[c][professor-1].append([hores])
            #AssigProfeU[c][professor-1].append([0])
            #print(AssigsProfe)
            Thours[c][professor-1]=Thours[c][professor-1]+hores
            #Si hi ha SC:
            if assignatura[2]!=0:
                profeSC=assignatura[2]
                Thours[c][profeSC-1]=Thours[c][profeSC-1]+hores  
            
        c=c+1;

    print(Thours)
    #print(AssigsProfe)
#print(" ")
#print(ClasseAssignatura2)

In [77]:
Thours=np.zeros((classes, numTeachers),dtype=int)
#numAssigProfe=np.zeros((classes, numTeachers),dtype=int)
AssigsProfe=[[[] for i in range(numTeachers)] for i in range(classes)]
print(AssigsProfe)
print(" ")
print(ClasseAssignatura2)
print(" ")
Calculate_TeachingHours()


[[[], [], [], [], [], []], [[], [], [], [], [], []]]
 
[[[3, 1, 0, 0], [2, 2, 0, 0], [4, 3, 0, 0], [3, 1, 0, 0], [3, 4, 5, 0], [3, 4, 0, 7], [3, 6, 0, 6]], [[3, 1, 0, 0], [4, 2, 0, 4], [3, 3, 0, 0], [4, 4, 0, 2], [6, 5, 0, 0], [2, 6, 0, 0], [2, 1, 0, 0]]]
 
[[6 2 4 6 3 3]
 [5 4 3 4 6 2]]


In [4]:
a=[1 ,2 ,3]
b=a.index(max(a))
print(b)

2


In [78]:
#Recorrem les assignatures d'una classe
#[slots,professor1,professorSC,AssignaturaCT]

def decrementarHores(teacher,classe,Thours):
    #Recorrem les assignatures de la classe buscant les que fa el profe teacher
    #c= assignatures de la classe 1
    
    idxAssigntr=0
    print("profe= ", teacher)
    c=ClasseAssignatura3[classe][:]
    print("c",c)
    for assignatura in c:
        print("assignatura[1]==teacher",assignatura[1]==teacher)
        print("assignatura[0]>0",assignatura[0]>0)
        if assignatura[1]==teacher and assignatura[0]>0:
            print("idxAssigntr",idxAssigntr)
            print("classe",classe)
            #Decrementam 
            ClasseAssignatura3[classe][idxAssigntr][0]=ClasseAssignatura3[classe][idxAssigntr][0]-1
            Thours[classe][teacher-1]=Thours[classe][teacher-1]-1
            teachers=[teacher,0]
            print("cas1")
            
            #si hi ha SC les decrementam de Thours
            if ClasseAssignatura3[classe][idxAssigntr][2]!=0:
                
                teacher2=ClasseAssignatura3[classe][idxAssigntr][2]
                print("teacher2= ",teacher2)
                Thours[classe][teacher2-1]=Thours[classe][teacher2-1]-1
                teachers=[teacher,teacher2]
                print("cas2")
                
            #Si hi ha coteaching llevam les hores de l'altra assignatura:
            if ClasseAssignatura3[classe][idxAssigntr][3]!=0:
                #Seleccionam el valor de l'index de l'assignatura amb la que hi ha coteaching
                AssigCT=ClasseAssignatura3[classe][idxAssigntr][3]
                print("AssigCT",AssigCT)
                #Decrementam en 1h les hores pendents d'assignar de l'assignatura de CT
                ClasseAssignatura3[classe][AssigCT-1][0]=ClasseAssignatura3[classe][AssigCT-1][0]-1
                teacherCT=ClasseAssignatura3[classe][AssigCT-1][1]
                Thours[classe][teacherCT-1]=Thours[classe][teacherCT-1]-1
                teachers=[teacher,teacherCT]
                print("cas3")
            
            break
                
        idxAssigntr=idxAssigntr+1
    #c=ClasseAssignatura3[classe][:]
    print("c",c)
    #print("ClasseAssignatura3 decrem",ClasseAssignatura3)
    return Thours,teachers
                
        

In [79]:
poblacio=[0 for i in range(population)]
for i in range(population):
    Thours=np.zeros((classes, numTeachers),dtype=int)
    Calculate_TeachingHours()
    ClasseAssignatura3=copy.deepcopy(ClasseAssignatura2)
    for classe in range(classes):
        for hour in range(TimeP):
            c=ClasseAssignatura2[classe]
            ok=False
            #Chose a teacher at random 
            print("classe= ",classe)
            print(Thours[classe])
            
            # Miram si s'han assignat totes les hores d'una classe.
            if np.array_equal(ZerosT,Thours[classe])==False:
                while ok==False:#mirar que no sigui que no et quedin profes i se quedi aqui infinitament
                    teacher=randrange(1, numTeachers+1)
                    print("teacher",teacher)
                    for j in c:
                        #print("i",i) 
                        #print("c",c)
                        #print("i[1]",i[1])
                        #print(Thours[classe][teacher-1])
                        if(j[1]==teacher) and Thours[classe][teacher-1]!=0:
                            ok=True
                    #ok=True       
                print("thours",Thours[classe][teacher-1])
                print("selected teacher", teacher)
                print("decrementam ")
                Thours,teachers=decrementarHores(teacher,classe,Thours)
                print("classe",classe)
                print("hours",hour)                
                Chromo[classe][hour]=teachers
                print("TeacherHours, teachers :",Thours[classe], teachers)

                print(teachers)
                
            
                #Assignar slot buit
            print("buit")
    print("index",i)      
    poblacio[i]=copy.deepcopy(Chromo)
    #break

                            
                

                        
                #Now we have a teacher!!!
                #print(teacher)

                #Decrementam les hores agafant una hora en concret d'una assignatura
                
                #TeachingHours[teacher-1]=TeachingHours[teacher-1]-1
                #TeachingHours=a
      

        
#Si algun teacher només està de subclasse mai el decrementa directament !Alerta!  

[[6 2 4 6 3 3]
 [5 4 3 4 6 2]]
classe=  0
[6 2 4 6 3 3]
teacher 5
teacher 2
thours 2
selected teacher 2
decrementam 
profe=  2
c [[3, 1, 0, 0], [2, 2, 0, 0], [4, 3, 0, 0], [3, 1, 0, 0], [3, 4, 5, 0], [3, 4, 0, 7], [3, 6, 0, 6]]
assignatura[1]==teacher False
assignatura[0]>0 True
assignatura[1]==teacher True
assignatura[0]>0 True
idxAssigntr 1
classe 0
cas1
c [[3, 1, 0, 0], [1, 2, 0, 0], [4, 3, 0, 0], [3, 1, 0, 0], [3, 4, 5, 0], [3, 4, 0, 7], [3, 6, 0, 6]]
classe 0
hours 0
TeacherHours, teachers : [6 1 4 6 3 3] [2, 0]
[2, 0]
buit
classe=  0
[6 1 4 6 3 3]
teacher 6
thours 3
selected teacher 6
decrementam 
profe=  6
c [[3, 1, 0, 0], [1, 2, 0, 0], [4, 3, 0, 0], [3, 1, 0, 0], [3, 4, 5, 0], [3, 4, 0, 7], [3, 6, 0, 6]]
assignatura[1]==teacher False
assignatura[0]>0 True
assignatura[1]==teacher False
assignatura[0]>0 True
assignatura[1]==teacher False
assignatura[0]>0 True
assignatura[1]==teacher False
assignatura[0]>0 True
assignatura[1]==teacher False
assignatura[0]>0 True
assignatura[1]==te

hours 2
TeacherHours, teachers : [4 4 2 4 6 1] [6, 0]
[6, 0]
buit
classe=  1
[4 4 2 4 6 1]
teacher 5
thours 6
selected teacher 5
decrementam 
profe=  5
c [[2, 1, 0, 0], [4, 2, 0, 4], [2, 3, 0, 0], [4, 4, 0, 2], [6, 5, 0, 0], [1, 6, 0, 0], [2, 1, 0, 0]]
assignatura[1]==teacher False
assignatura[0]>0 True
assignatura[1]==teacher False
assignatura[0]>0 True
assignatura[1]==teacher False
assignatura[0]>0 True
assignatura[1]==teacher False
assignatura[0]>0 True
assignatura[1]==teacher True
assignatura[0]>0 True
idxAssigntr 4
classe 1
cas1
c [[2, 1, 0, 0], [4, 2, 0, 4], [2, 3, 0, 0], [4, 4, 0, 2], [5, 5, 0, 0], [1, 6, 0, 0], [2, 1, 0, 0]]
classe 1
hours 3
TeacherHours, teachers : [4 4 2 4 5 1] [5, 0]
[5, 0]
buit
classe=  1
[4 4 2 4 5 1]
teacher 1
thours 4
selected teacher 1
decrementam 
profe=  1
c [[2, 1, 0, 0], [4, 2, 0, 4], [2, 3, 0, 0], [4, 4, 0, 2], [5, 5, 0, 0], [1, 6, 0, 0], [2, 1, 0, 0]]
assignatura[1]==teacher True
assignatura[0]>0 True
idxAssigntr 0
classe 1
cas1
c [[1, 1, 0, 0], [

assignatura[0]>0 True
assignatura[1]==teacher True
assignatura[0]>0 True
idxAssigntr 6
classe 0
cas1
AssigCT 6
cas3
c [[1, 1, 0, 0], [0, 2, 0, 0], [3, 3, 0, 0], [3, 1, 0, 0], [0, 4, 5, 0], [0, 4, 0, 7], [0, 6, 0, 6]]
classe 0
hours 10
TeacherHours, teachers : [4 0 3 0 0 0] [6, 4]
[6, 4]
buit
classe=  0
[4 0 3 0 0 0]
teacher 2
teacher 6
teacher 4
teacher 1
thours 4
selected teacher 1
decrementam 
profe=  1
c [[1, 1, 0, 0], [0, 2, 0, 0], [3, 3, 0, 0], [3, 1, 0, 0], [0, 4, 5, 0], [0, 4, 0, 7], [0, 6, 0, 6]]
assignatura[1]==teacher True
assignatura[0]>0 True
idxAssigntr 0
classe 0
cas1
c [[0, 1, 0, 0], [0, 2, 0, 0], [3, 3, 0, 0], [3, 1, 0, 0], [0, 4, 5, 0], [0, 4, 0, 7], [0, 6, 0, 6]]
classe 0
hours 11
TeacherHours, teachers : [3 0 3 0 0 0] [1, 0]
[1, 0]
buit
classe=  0
[3 0 3 0 0 0]
teacher 5
teacher 4
teacher 5
teacher 6
teacher 3
thours 3
selected teacher 3
decrementam 
profe=  3
c [[0, 1, 0, 0], [0, 2, 0, 0], [3, 3, 0, 0], [3, 1, 0, 0], [0, 4, 5, 0], [0, 4, 0, 7], [0, 6, 0, 6]]
assigna

thours 1
selected teacher 1
decrementam 
profe=  1
c [[0, 1, 0, 0], [0, 2, 0, 4], [1, 3, 0, 0], [0, 4, 0, 2], [1, 5, 0, 0], [0, 6, 0, 0], [1, 1, 0, 0]]
assignatura[1]==teacher True
assignatura[0]>0 False
assignatura[1]==teacher False
assignatura[0]>0 False
assignatura[1]==teacher False
assignatura[0]>0 True
assignatura[1]==teacher False
assignatura[0]>0 False
assignatura[1]==teacher False
assignatura[0]>0 True
assignatura[1]==teacher False
assignatura[0]>0 False
assignatura[1]==teacher True
assignatura[0]>0 True
idxAssigntr 6
classe 1
cas1
c [[0, 1, 0, 0], [0, 2, 0, 4], [1, 3, 0, 0], [0, 4, 0, 2], [1, 5, 0, 0], [0, 6, 0, 0], [0, 1, 0, 0]]
classe 1
hours 17
TeacherHours, teachers : [0 0 1 0 1 0] [1, 0]
[1, 0]
buit
classe=  1
[0 0 1 0 1 0]
teacher 4
teacher 6
teacher 4
teacher 5
thours 1
selected teacher 5
decrementam 
profe=  5
c [[0, 1, 0, 0], [0, 2, 0, 4], [1, 3, 0, 0], [0, 4, 0, 2], [1, 5, 0, 0], [0, 6, 0, 0], [0, 1, 0, 0]]
assignatura[1]==teacher False
assignatura[0]>0 False
assigna

assignatura[1]==teacher False
assignatura[0]>0 True
assignatura[1]==teacher False
assignatura[0]>0 True
assignatura[1]==teacher False
assignatura[0]>0 True
assignatura[1]==teacher False
assignatura[0]>0 True
assignatura[1]==teacher True
assignatura[0]>0 True
idxAssigntr 5
classe 1
cas1
c [[3, 1, 0, 0], [4, 2, 0, 4], [1, 3, 0, 0], [4, 4, 0, 2], [6, 5, 0, 0], [0, 6, 0, 0], [2, 1, 0, 0]]
classe 1
hours 3
TeacherHours, teachers : [5 4 1 4 6 0] [6, 0]
[6, 0]
buit
classe=  1
[5 4 1 4 6 0]
teacher 4
thours 4
selected teacher 4
decrementam 
profe=  4
c [[3, 1, 0, 0], [4, 2, 0, 4], [1, 3, 0, 0], [4, 4, 0, 2], [6, 5, 0, 0], [0, 6, 0, 0], [2, 1, 0, 0]]
assignatura[1]==teacher False
assignatura[0]>0 True
assignatura[1]==teacher False
assignatura[0]>0 True
assignatura[1]==teacher False
assignatura[0]>0 True
assignatura[1]==teacher True
assignatura[0]>0 True
idxAssigntr 3
classe 1
cas1
AssigCT 2
cas3
c [[3, 1, 0, 0], [3, 2, 0, 4], [1, 3, 0, 0], [3, 4, 0, 2], [6, 5, 0, 0], [0, 6, 0, 0], [2, 1, 0, 0]]

assignatura[0]>0 True
idxAssigntr 1
classe 0
cas1
c [[0, 1, 0, 0], [1, 2, 0, 0], [1, 3, 0, 0], [2, 1, 0, 0], [3, 4, 5, 0], [1, 4, 0, 7], [1, 6, 0, 6]]
classe 0
hours 9
TeacherHours, teachers : [2 1 1 4 3 1] [2, 0]
[2, 0]
buit
classe=  0
[2 1 1 4 3 1]
teacher 4
thours 4
selected teacher 4
decrementam 
profe=  4
c [[0, 1, 0, 0], [1, 2, 0, 0], [1, 3, 0, 0], [2, 1, 0, 0], [3, 4, 5, 0], [1, 4, 0, 7], [1, 6, 0, 6]]
assignatura[1]==teacher False
assignatura[0]>0 False
assignatura[1]==teacher False
assignatura[0]>0 True
assignatura[1]==teacher False
assignatura[0]>0 True
assignatura[1]==teacher False
assignatura[0]>0 True
assignatura[1]==teacher True
assignatura[0]>0 True
idxAssigntr 4
classe 0
cas1
teacher2=  5
cas2
c [[0, 1, 0, 0], [1, 2, 0, 0], [1, 3, 0, 0], [2, 1, 0, 0], [2, 4, 5, 0], [1, 4, 0, 7], [1, 6, 0, 6]]
classe 0
hours 10
TeacherHours, teachers : [2 1 1 3 2 1] [4, 5]
[4, 5]
buit
classe=  0
[2 1 1 3 2 1]
teacher 5
teacher 6
thours 1
selected teacher 6
decrementam 
profe=  6
c [[0, 1

[0 0 0 0 0 0]
buit
classe=  1
[0 0 0 0 0 0]
buit
classe=  1
[0 0 0 0 0 0]
buit
classe=  1
[0 0 0 0 0 0]
buit
classe=  1
[0 0 0 0 0 0]
buit
classe=  1
[0 0 0 0 0 0]
buit
classe=  1
[0 0 0 0 0 0]
buit
classe=  1
[0 0 0 0 0 0]
buit
classe=  1
[0 0 0 0 0 0]
buit
classe=  1
[0 0 0 0 0 0]
buit
classe=  1
[0 0 0 0 0 0]
buit
classe=  1
[0 0 0 0 0 0]
buit
index 3
[[6 2 4 6 3 3]
 [5 4 3 4 6 2]]
classe=  0
[6 2 4 6 3 3]
teacher 6
thours 3
selected teacher 6
decrementam 
profe=  6
c [[3, 1, 0, 0], [2, 2, 0, 0], [4, 3, 0, 0], [3, 1, 0, 0], [3, 4, 5, 0], [3, 4, 0, 7], [3, 6, 0, 6]]
assignatura[1]==teacher False
assignatura[0]>0 True
assignatura[1]==teacher False
assignatura[0]>0 True
assignatura[1]==teacher False
assignatura[0]>0 True
assignatura[1]==teacher False
assignatura[0]>0 True
assignatura[1]==teacher False
assignatura[0]>0 True
assignatura[1]==teacher False
assignatura[0]>0 True
assignatura[1]==teacher True
assignatura[0]>0 True
idxAssigntr 6
classe 0
cas1
AssigCT 6
cas3
c [[3, 1, 0, 0], [2

profe=  2
c [[2, 1, 0, 0], [1, 2, 0, 4], [1, 3, 0, 0], [1, 4, 0, 2], [5, 5, 0, 0], [0, 6, 0, 0], [2, 1, 0, 0]]
assignatura[1]==teacher False
assignatura[0]>0 True
assignatura[1]==teacher True
assignatura[0]>0 True
idxAssigntr 1
classe 1
cas1
AssigCT 4
cas3
c [[2, 1, 0, 0], [0, 2, 0, 4], [1, 3, 0, 0], [0, 4, 0, 2], [5, 5, 0, 0], [0, 6, 0, 0], [2, 1, 0, 0]]
classe 1
hours 9
TeacherHours, teachers : [4 0 1 0 5 0] [2, 4]
[2, 4]
buit
classe=  1
[4 0 1 0 5 0]
teacher 4
teacher 6
teacher 4
teacher 4
teacher 2
teacher 1
thours 4
selected teacher 1
decrementam 
profe=  1
c [[2, 1, 0, 0], [0, 2, 0, 4], [1, 3, 0, 0], [0, 4, 0, 2], [5, 5, 0, 0], [0, 6, 0, 0], [2, 1, 0, 0]]
assignatura[1]==teacher True
assignatura[0]>0 True
idxAssigntr 0
classe 1
cas1
c [[1, 1, 0, 0], [0, 2, 0, 4], [1, 3, 0, 0], [0, 4, 0, 2], [5, 5, 0, 0], [0, 6, 0, 0], [2, 1, 0, 0]]
classe 1
hours 10
TeacherHours, teachers : [3 0 1 0 5 0] [1, 0]
[1, 0]
buit
classe=  1
[3 0 1 0 5 0]
teacher 2
teacher 1
thours 3
selected teacher 1
d

In [80]:
print(Chromo)
print(poblacio[0])

[[[6, 4], [1, 0], [1, 0], [3, 0], [2, 0], [3, 0], [3, 0], [1, 0], [1, 0], [6, 4], [3, 0], [1, 0], [1, 0], [4, 5], [6, 4], [4, 5], [2, 0], [4, 5], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0]], [[3, 0], [6, 0], [2, 4], [3, 0], [4, 2], [2, 4], [6, 0], [5, 0], [1, 0], [2, 4], [1, 0], [1, 0], [1, 0], [3, 0], [5, 0], [1, 0], [5, 0], [5, 0], [5, 0], [5, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0]]]
[[[2, 0], [6, 4], [1, 0], [1, 0], [4, 5], [3, 0], [3, 0], [6, 4], [2, 0], [3, 0], [1, 0], [6, 4], [4, 5], [1, 0], [3, 0], [1, 0], [1, 0], [4, 5], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0]], [[3, 0], [1, 0], [6, 0], [5, 0], [1, 0], [1, 0], [6, 0], [2, 4], [1, 0], [5, 0], [5, 0], [2, 4], [4, 2], [3, 0], [5, 0], [5, 0], [5, 0], [1, 0], [2, 4],

*Teacher unavailability: For each teacher and for each time period this teacher is assigned to a class, while he/she is unavailable at school the corresponding day, the following cost is added: HCW ∗ BASE3.

*Teacher assigned in more than one class: For each teacher and for each time period, if this teacher is assigned to more than one class, for example, to k classes, the following cost is added: HCW ∗ BASEk


In [73]:
BASE=1.5
HCW=10#??????
IDWT=3
TEPW=2
a=[2,3]
a.count(2)

1

In [42]:
def CTeacherUnable(teachers,hora,individu):
    #print("hora",hora)
    dia=int(hora/7)
    #print("dia",dia)
    cost=0
    #print("profes",teachers)
    for teacher in teachers:
        if teacher != 0: 
            #print("at School?")
            #print(teacher,dia)
            #print(TeacherNoDays[teacher-1][dia])
            cost=cost+TeacherNoDays[teacher-1][dia]
            costsTeachers[individu][teacher-1]=costsTeachers[individu][teacher-1]+(HCW*(BASE**3))
    return cost
    

In [43]:
#TeachersTimeTable=np.zeros((numTeachers,TimeP), dtype=int).tolist()
#print(TeachersTimeTable)
#Funció per crear l'horari de cada un dels profes per cada individu :)
#Crec que funciona bé però s'ha de repassar!!!
def createTeachersTimeP(teachers,i_classe,i_timePeriod):
    for teacher in teachers:
        if teacher!=0:
            #Guardam la classe que fa aquest profe en aquesta hora
            TeachersTimeTable[teacher-1][i_timePeriod]=i_classe+1
            #TeachersTimeTable[teacher-1][i_timePeriod].append(i_classe+1)

In [15]:
#Cost Teacher empty spaces and dispersion
def CostTeacherE_i_D():
    costTeacherEmpty=[]
    costTeacherDisp=[]
    cTeacherDisph=0
    cTeacherDispd=0
    hoursTeacher=0#num hores que fa un profe cada dia
    TotalcostTeacherDisp=0
    EmptyFound=False
    t=0#index del professor
    for teacher in TeachersTimeTable:
        h=0
        chours=0#cost hores
        cdays=0 #cost dies
        for day in range(5):
            for hour in range(7):
                
                if teacher[h]!=0:
                    hoursTeacher=hoursTeacher+1
                    #Si trobam una hora ocupada després de trobar un espai buit
                    if EmptyFound==True:
                        chours=chours+1
                        incr=True
                        EmptyFound=False
                    
                elif teacher[h]==0:
                    EmptyFound=True
                    
                h=h+1#index de les hores
                
            #Quan canviam de dia incrementam el cost del dia i resetejam els paràmetres:
            #Si les hores que fa un professor un dia es desvien en més de 1 de la mitjana ideal:
            hour_difference=abs(hoursTeacher-TeacherIdealHours[t])
            if hour_difference > 1:
                cTeacherDisph=cTeacherDisph+hour_difference
                cTeacherDispd=cTeacherDispd+1
            if incr>0:
                cdays=cdays+1
            hoursTeacher=0
            incr=False
            EmptyFound=False
        #Aquí calcul del cost
        
        t=t+1
        costTeacherDisp.append([cTeacherDisph,cTeacherDispd])
        cTeacherDisph=0
        cTeacherDispd=0
        costTeacherEmpty.append([chours,cdays])
        chours=0
        cdays=0
        #En lloc d'això aquí aniria la part de la funció de cost corresponent
    return costTeacherEmpty 
            

In [54]:
#Cost 1 i cost 2 calculats i funcionen correctament :)

def calc_C1_C2(individu,indx_individu):
    costUnable=0
    costMore1class=0
    #TeachersTimeTable=[[[] for i in range(TimeP)] for i in range(numTeachers)]
    TeachersTimeTable=[[0 for i in range(TimeP)] for i in range(numTeachers)]
    
    #llista dels profes assignats a una hora
    teacher_timeP=[]
    #for individu in population:
    for i_timePeriod in range(TimeP):
        teacher_timeP=[]
        for i_classe in range(classes):

            teachers=individu[i_classe][i_timePeriod]
            #Cream els horaris dels profes -> Aixo no ho empleam pero vaja
            createTeachersTimeP(teachers,i_classe,i_timePeriod)
            #Calculam el cost de si el profe no és a l'institut
            costU=CTeacherUnable(teachers,i_timePeriod,indx_individu)
            #if costU!=0:
                #print("--------------------")
                #print(i_timePeriod)
                #print("teachers",teachers)
                #print("costU",costU)
                #print("costUnable",costUnable)
            teacher_timeP.extend(teachers)
            costUnable=costUnable+costU
            #print("cost, i_timePeriod",costU,i_timePeriod)

        #Eliminam de la llista els buits(teacher 0) ja que teacher 0 no és cap teacher
        teacher_timeP=[elem for elem in teacher_timeP if elem != 0]
        #print(set(teacher_timeP))
        #print(teacher_timeP)
        cM1c_K=len(teacher_timeP)-len(set(teacher_timeP))
        costMore1class=costMore1class+HCW*(BASE**cM1c_K)
        #Calculate the cost for each teacher
        for t in teacher_timeP:
            k=teacher_timeP.count(t)-1
            teachersM1c_Cost=HCW*(BASE**k)
            costsTeachers[indx_individu][teacher-1]=costTeachers[indx_individu][teacher-1]+HCW*(BASE**k)


    print(costUnable)   
    costUnable=costUnable*(HCW*(BASE**3))
    print("c1 ",costUnable)
    print("c2 ",costMore1class)
    return(costUnable,costMore1class)


In [66]:
def IdealTeachingDayHours():
    TeacherIdealHours=[]
    for t in range (numTeachers):
        horesideals=TeachingHours[t]/(5-np.count_nonzero(TeacherNoDays[t]))
        TeacherIdealHours.append(horesideals)
    return TeacherIdealHours

Teacher’s empty spaces: For each teacher the following subcost is added:
TEPW ∗ HOURS ∗ BASE^DAYS, where
HOURS is the total number of empty time periods in the teacher’s timetable and DAYS is the number of days that empty time periods exist in the timetable of this specific teacher


In [80]:
print(TeachersTimeTable)

[[1, 0, 0, 0, 0, 0, 0, 0, 2, 2, 2, 0, 0, 1, 2, 1, 1, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [2, 0, 0, 0, 0, 2, 2, 0, 0, 0, 1, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 1, 0, 2, 2, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [2, 0, 1, 1, 0, 2, 2, 1, 1, 1, 0, 2, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 2, 2, 1, 0, 0, 0, 2, 0, 1, 0, 0, 1, 0, 0, 0, 2, 0, 2, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 2, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]]


In [81]:
#Cost Teacher empty spaces and dispersion
def CostTeacherE_i_D(idx_individu):
    costTeacherEmpty=0
    costTeacherLDisp=0
    cTeacherDisph=0
    cTeacherDispd=0
    hoursTeacher=0#num hores que fa un profe cada dia
    TotalcostTeacherDisp=0
    EmptyFound=False
    TeacherIdealHours=IdealTeachingDayHours()
    t=0#index del professor
    
    for teacher in TeachersTimeTable:
        h=0
        chours=0#cost hores
        cdays=0 #cost dies
        for day in range(5):
            incr=False
            for hour in range(7):
                
                if teacher[h]!=0:
                    hoursTeacher=hoursTeacher+1
                    #Si trobam una hora ocupada després de trobar un espai buit
                    if EmptyFound==True:
                        chours=chours+1
                        incr=True
                        EmptyFound=False
                    
                elif teacher[h]==0:
                    EmptyFound=True
                    
                h=h+1#index de les hores
                
            #Quan canviam de dia incrementam el cost del dia i resetejam els paràmetres:
            #Si les hores que fa un professor un dia es desvien en més de 1 de la mitjana ideal:
            hour_difference=abs(hoursTeacher-TeacherIdealHours[t])
            if hour_difference > 1:
                cTeacherDisph=cTeacherDisph+hour_difference
                cTeacherDispd=cTeacherDispd+1
            if incr==True:
                cdays=cdays+1
            hoursTeacher=0
            incr=False
            EmptyFound=False
            
        #Càlcul del cost de lesson's dispersion
        costTLD=IDWT*cTeacherDisph*(BASE**cTeacherDispd)
        costTeacherLDisp=costTeacherLDisp+costTLD
        costsTeachers[idx_individu][t-1]=costsTeachers[idx_individu][t-1]+costTLD
        
        #Aquí calcul del cost de Empty Scpaces
        costES=TEPW*chours*(BASE**cdays)
        costTeacherEmpty=costTeacherEmpty+costES
        costsTeachers[idx_individu][t-1]=costsTeachers[idx_individu][t-1]+costES
        
        t=t+1
        cTeacherDisph=0
        cTeacherDispd=0
        
    return costTeacherLDisp,costTeacherEmpty
            

In [50]:
#Class’s empty spaces cost calculat i funciona correctament :)
#HCW*BASE^BASE
def C_classEmptySpaces(individu):
    costClEmptySpaces=0
    emptyHour=False
    
    for classe in individu:
        timeP=0
        #cLessonDispersion=costClLessDispersion(classe)
        for teachers in classe:
            #Si canviam de dia resetejam les variables          
            if timeP%7==0:
                emptyHour=False
            #Si hi ha una hora buida activam empty hour  
            if teachers==[0,0]:
                emptyHour=True
            #Si hi ha una hora ocupada i prèviament hi ha hagut una hora buida el mateix dia sumam 1 al cost
            elif emptyHour==True:
                emptyHour=False
                costClEmptySpaces=costClEmptySpaces+1
            timeP=timeP+1
    cost=costClEmptySpaces*HCW*(BASE**BASE)
    return cost  

. Teacher lessons’ dispersion: For each teacher the following subcost is added: 
IDWT ∗ HOURS ∗ BASE^DAYS
, where HOURS is the total number of time periods that are different compared to the ideal dispersion teacher’s timetable and DAYS is the number of days in the teacher’s timetable that such a declination from the ideal case exists

In [83]:
def CostFunction(poblacio):
    costsTeachers=[[0 for i in range(numTeachers)] for i in range(population)]
    costs=[0 for i in range(population)]
    idx_individu=0
    c_TeachUnable=0
    c_TMore1class=0
    c_ClassEmptySp=0
    c_TeacherEmpty=0
    c_TeacherLD=0
    
    for individu in poblacio:
        TeachersTimeTable=[[0 for i in range(TimeP)] for i in range(numTeachers)]

        [cTU,cM1cl]=calc_C1_C2(individu,idx_individu)
        print("-----------------------------")
        print(individu)
        print(cTU)
        print(cM1cl)

        c_TeachUnable=c_TeachUnable+cTU

        c_TMore1class=c_TMore1class+cM1cl

        cES=C_classEmptySpaces(individu)
        c_ClassEmptySp=c_ClassEmptySp+cES

        cTE,cTLD=CostTeacherE_i_D(idx_individu)

        c_TeacherEmpty=c_TeacherEmpty+cTE
        c_TeacherLD=c_TeacherLD+cTLD

        TotalCost=c_TeachUnable+c_TMore1class+c_ClassEmptySp+c_TeacherEmpty
        idx_individu=idx_individu+1
        costs[idx_individu]=TotalCost
        print(costsTeachers)
return costs
    

3
c1  101.25
c2  370.0
-----------------------------
[[[1, 0], [3, 0], [6, 4], [4, 5], [3, 0], [2, 0], [3, 0], [6, 4], [6, 4], [4, 5], [2, 0], [3, 0], [4, 5], [1, 0], [1, 0], [1, 0], [1, 0], [1, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0]], [[4, 2], [5, 0], [5, 0], [3, 0], [3, 0], [2, 4], [2, 4], [5, 0], [1, 0], [1, 0], [1, 0], [2, 4], [6, 0], [6, 0], [1, 0], [3, 0], [5, 0], [1, 0], [5, 0], [5, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0]]]
101.25
370.0
[[160.125, 290.925, 523.125, 535.275, 326.25, 396.8671875], [0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0]]
5
c1  168.75
c2  375.0
-----------------------------
[[[2, 0], [6, 4], [4, 5], [6, 4], [3, 0], [4, 5], [6, 4], [3, 0], [2, 0], [3, 0], [4, 5], [3, 0], [1, 0], [1, 0], [1, 0], [1, 0], [1, 0], [1, 0], [0, 0], [0, 0], [0, 0], [0, 0]

In [22]:
#Funció de cost-> això haurà de ser una funció
costsTeachers=[[0 for i in range(numTeachers)] for i in range(population)]
costs=[0 for i in range(population)]
#for individu in poblacio:
costsTeachers   
    

[[0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0]]

In [10]:
print(TeachersTimeTable[0])
print(poblacio[0])
print(" ")
print(poblacio[1])
print(" ")

[[], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], []]
[[[3, 0], [1, 0], [2, 0], [1, 0], [2, 0], [1, 0], [1, 0], [6, 4], [6, 4], [6, 4], [3, 0], [3, 0], [3, 0], [4, 5], [4, 5], [1, 0], [1, 0], [4, 5], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0]], [[2, 4], [4, 2], [1, 0], [4, 2], [3, 0], [4, 2], [3, 0], [6, 0], [6, 0], [1, 0], [3, 0], [5, 0], [1, 0], [1, 0], [5, 0], [1, 0], [5, 0], [5, 0], [5, 0], [5, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0]]]
 
[[[6, 4], [2, 0], [4, 5], [1, 0], [3, 0], [1, 0], [1, 0], [6, 4], [4, 5], [2, 0], [6, 4], [4, 5], [1, 0], [3, 0], [1, 0], [3, 0], [1, 0], [3, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0]], [[4, 2], 

Teacher lessons’ dispersion: For each teacher the following subcost is added: IDWT ∗ HOURS ∗ BASEDAYS, where
HOURS is the total number of time periods that are different compared to the ideal dispersion teacher’s timetable
and DAYS is the number of days in the teacher’s timetable that such a declination from the ideal case exists.

In [17]:
#Cost 1 i cost 2 calculats i funcionen correctament :)
#def c
individu=copy.deepcopy(Chromo)#-------------------
costUnable=0
costMore1class=0
TeachersTimeTable=[[[] for i in range(TimeP)] for i in range(numTeachers)]
#TeachersTimeTable=np.zeros((numTeachers,TimeP), dtype=int)
#llista dels profes assignats a una hora
teacher_timeP=[]
#for individu in population:
for i_timePeriod in range(TimeP):
    teacher_timeP=[]
    for i_classe in range(classes):
        
        teachers=individu[i_classe][i_timePeriod]
        #Cream els horaris dels profes
        createTeachersTimeP(teachers,i_classe,i_timePeriod)
        #Calculam el cost de si el profe no és a l'institut
        costU=CTeacherUnable(teachers,i_timePeriod,indx_individu)
        #if costU!=0:
            #print("--------------------")
            #print(i_timePeriod)
            #print("teachers",teachers)
            #print("costU",costU)
            #print("costUnable",costUnable)
        teacher_timeP.extend(teachers)
        costUnable=costUnable+costU
        #print("cost, i_timePeriod",costU,i_timePeriod)
        
    #Eliminam de la llista els buits(teacher 0) ja que teacher 0 no és cap teacher
    teacher_timeP=[elem for elem in teacher_timeP if elem != 0]
    #print(set(teacher_timeP))
    #print(teacher_timeP)
    cM1c_K=len(teacher_timeP)-len(set(teacher_timeP))
    costMore1class=costMore1class+HCW*(BASE**cM1c_K)
    #Calculate the cost for each teacher
    for t in teacher_timeP:
        k=teacher_timeP.count(t)-set(teacher_timeP).count(t)
        teachersM1c_Cost=HCW∗(BASE**k)
        costTeachers[indx_individu][teacher-1]=costTeachers[indx_individu][teacher-1]+HCW∗(BASE**k)
    
    
print(costUnable)   
costUnable=costUnable*(HCW*(BASE**3))
print("c1 ",costUnable)
print("c2 ",costMore1class)


c1  3
c2  4
[[2, 0], [4, 5], [6, 4], [1, 0], [6, 4], [2, 0], [3, 0], [4, 5], [6, 4], [1, 0], [3, 0], [1, 0], [4, 5], [3, 0], [3, 0]]
[[3, 0], [1, 0], [1, 0], [4, 2], [2, 4], [2, 4], [6, 0], [5, 0], [1, 0], [5, 0], [3, 0], [6, 0], [1, 0], [5, 0], [5, 0]]
[[1, 0, 0, 0, 0], [0, 1, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0]]


In [16]:
#Class’s empty spaces: For each class and for each time period that no lesson is assigned to this class, if this time
#period is not the last of the corresponding day, then the following cost is added: HCW ∗ BASEBASE.
#Cost Teacher empty spaces and dispersion
def CostTeacherEmpySpaces():
    costTeacherEmpty=[]
    EmptyFound=False
    for teacher in TeachersTimeTable:
        h=0
        chours=0#cost hores
        cdays=0 #cost dies
        for day in range(5):
            for hour in range(7):
                #Si trobam una hora ocupada després de trobar un espai buit
                if teacher[h]!=0 and EmptyFound==True:
                    chours=chours+1
                    incr=True
                    EmptyFound=False
                    
                elif teacher[h]==0:
                    EmptyFound=True
                    
                h=h+1#index de les hores
                
            #Quan canviam de dia incrementam el cost del dia i resetejam els paràmetres:
            if incr>0:
                cdays=cdays+1
            incr=False
            EmptyFound=False
        costTeacherEmpty.append([chours,cdays])
        #En lloc d'això aquí aniria la part de la funció de cost corresponent
    return costTeacherEmpty 
            

In [17]:
#print(Chromo[0][:])
classe1=Chromo[0][:]
len(classe1)
a=[5,5,6]
a.remove(5)
h=0
classe1[7]=1
classe1[0:7]
print(classe1)
classe1[7:7+7]

[[0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], 1, [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0]]


[1, [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0]]

In [18]:
AssigsProfe

[[[], [], [], [], [], []], [[], [], [], [], [], []]]

In [19]:
#1 Llevar els 0 xq els buits no interessen
classe1=Chromo[0][:]#Igual aixo ha de ser un copy
print(teacherP)
h=0
c=0#index de la classe
for day in range(5):
    AssigDia=classe1[h:h+7]
    teach=[elem for elem in teacherP if elem != [0,0]]
    teachset=set(teach)
    for elem in teachset:
        teach.remove(elem)
    #Ara tenim el conjunt original únicament amb aquells elements que estan repetits
    for elem in teach:
        AssigsProfe[c][]
        
    h=h+7
    
    

SyntaxError: invalid syntax (<ipython-input-19-2c6e3bca2a73>, line 14)

In [20]:
classe1=[[4, 5], [6, 4], [3, 0], [1, 0], [6, 4], [1, 0], [2, 0], [4, 5], [3, 0], [1, 0], [3, 0], [2, 0], [1, 0], [4, 5], [1, 0], [1, 0], [3, 0]]

In [21]:
from copy import deepcopy
print(AssigsProfe[0][0])
a=deepcopy(AssigsProfe[0][0])
print(a)
a[0][1]=7
print(AssigsProfe[0][0])
print(a)


[]
[]


IndexError: list index out of range

In [60]:
#Cost Teacher empty spaces and dispersion
def CostTeacherEmpySpaces(indx_individu):
    costTeacherEmpty=0
    EmptyFound=False
    for teacher in TeachersTimeTable:
        h=0
        chours=0#cost hores
        cdays=0 #cost dies
        for day in range(5):
            for hour in range(7):
                #Si trobam una hora ocupada després de trobar un espai buit
                if teacher[h]!=0 and EmptyFound==True:
                    chours=chours+1
                    incr=True
                    EmptyFound=False
                    
                elif teacher[h]==0:
                    EmptyFound=True
                    
                h=h+1#index de les hores
                
            #Quan canviam de dia incrementam el cost del dia i resetejam els paràmetres:
            if incr>0:
                cdays=cdays+1
            incr=False
            EmptyFound=False
            
        cost=TEPW*chours*(BASE**cdays)
        costTeacherEmpty=costTeacherEmpty+cost
        costsTeachers[indx_individu][teacher-1]=costsTeachers[indx_individu][teacher-1]+cost
        
    return costTeacherEmpty 
            

In [22]:
classe=classe1.copy()
h=0
c=0#index de la classe
#Recorrem cada hora
for teachers in classe:
    AssigDia=classe[h:h+7]
    teach=[elem for elem in teacherP if elem != [0,0]]
    for profe in teach:
        profe=teach[0]-1
        assigs=deepcopy(AssigsProfe[c][profe])
        i=0
        for t in AssigsProfe[c][profe]:
        #Recorr les assignatures que fa aquest profe les hores
        AssigsProfe[c][profe][i]
        i=i+1
    teachers
    h=h+7

IndentationError: expected an indented block (<ipython-input-22-49d72fd1f890>, line 14)

In [23]:
#Per cada classe mirar les hores que ha de fer el profe i repartirles entre els dies que el profe és a l'institut i mirar 
#i mirar amb això si es repeteixen assignatures 
def costClLessDispersion(classe,c):
    h=0
    #Recorrem cada hora
    for teachers in classe:
        if h%7==0:
            #canvi de dia
        profe=teachers[0]
        teachers
        h=h+1
        
    

IndentationError: expected an indented block (<ipython-input-23-cabd7798a202>, line 9)

In [24]:
#Class’s empty spaces cost calculat i funciona correctament :)
individu=Chromo[:]
costClEmptySpaces=0
emptyHour=False
    
for classe in individu:
    timeP=0
    cLessonDispersion=costClLessDispersion(classe)
    for teachers in classe:
        #Si canviam de dia resetejam les variables          
        if timeP%7==0:
            emptyHour=False
        #Si hi ha una hora buida activam empty hour  
        if teachers==[0,0]:
            emptyHour=True
        #Si hi ha una hora ocupada i prèviament hi ha hagut una hora buida el mateix dia sumam 1 al cost
        elif emptyHour==True:
            emptyHour=False
            costClEmptySpaces=costClEmptySpaces+1
        timeP=timeP+1
costClEmptySpaces    

NameError: name 'costClLessDispersion' is not defined

In [25]:
TeachersTimeTable=[[[] for i in range(TimeP)] for i in range(numTeachers)]
#print(TeachersTimeTable)

In [26]:
#Cost 1 i cost 2 calculats i funcionen correctament :)
individu=Chromo[:]
costUnable=0
costMore1class=0
TeachersTimeTable=[[[] for i in range(TimeP)] for i in range(numTeachers)]
#TeachersTimeTable=np.zeros((numTeachers,TimeP), dtype=int)
#llista dels profes assignats a una hora
teacher_timeP=[]
#for individu in population:
for i_timePeriod in range(TimeP):
    teacher_timeP=[]
    for i_classe in range(classes):
        
        teachers=individu[i_classe][i_timePeriod]
        #Cream els horaris dels profes
        createTeachersTimeP(teachers,i_classe,i_timePeriod)
        #Calculam el cost de si el profe no és a l'institut
        costU=CTeacherUnable(teachers,i_timePeriod)
        #if costU!=0:
            #print("--------------------")
            #print(i_timePeriod)
            #print("teachers",teachers)
            #print("costU",costU)
            #print("costUnable",costUnable)
            
           
        teacher_timeP.extend(teachers)
        costUnable=costUnable+costU
        #print("cost, i_timePeriod",costU,i_timePeriod)
        
    #Eliminam de la llista els buits(teacher 0) ja que teacher 0 no és cap teacher
    teacher_timeP=[elem for elem in teacher_timeP if elem != 0]
    #print(set(teacher_timeP))
    #print(teacher_timeP)
    costM1c=len(teacher_timeP)-len(set(teacher_timeP))
    costMore1class=costMore1class+costM1c
print("c1 ",costUnable)
print("c2 ",costMore1class)
print(individu[0][0:15])
print(individu[1][0:15])
#print(individu[0][8:15])
#print(individu[1][8:15])
print(TeacherNoDays)

c1  0
c2  0
[[0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0]]
[[0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0]]
[[1, 0, 0, 0, 0], [0, 1, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0]]


In [27]:
Calculate_TeachingHours()
numAssigProfe

NameError: name 'AssigsProfeh' is not defined

In [28]:
individu=Chromo[:]
print(individu)
costUnable=0
for classe in individu:
    hora=0
    for TimePeriod in classe:
        costU=CTeacherUnable(TimePeriod,hora)
        costUnable=costUnable+costU
        print("cost, parella de profes",costU,TimePeriod)
        hora=hora+1
print(costUnable)

[[[0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0]], [[0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0]]]
cost, parella de profes 0 [0, 0]
cost, parella de profes 0 [0, 0]
cost, parella de profes 0 [0, 0]
cost, parella de profes 0 [0, 0]
cost, parella de profes 0 [0, 0]
cost, parella de profes 0 [0, 0]
cost, parella de profes 0 [0, 0]
cost, parella de profes 0 [0, 0]
cost, parella de profes 0 [0, 0]
cost, parella de profes 0 [0, 0]
cost, parella de profes 0 [0, 0]
cost, parella de profes 0 [0, 0]
cost, parella de profes 0 [0, 0]
cost, 

In [29]:
individu=Chromo[:]
print(individu)
costUnable=0
for classe in individu:
    hora=0
    for TimePeriod in classe:
        costU=CTeacherUnable(TimePeriod,hora)
        costUnable=costUnable+costU
        print("cost, parella de profes",costU,TimePeriod)
        hora=hora+1
print(costUnable)
    

[[[0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0]], [[0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0]]]
cost, parella de profes 0 [0, 0]
cost, parella de profes 0 [0, 0]
cost, parella de profes 0 [0, 0]
cost, parella de profes 0 [0, 0]
cost, parella de profes 0 [0, 0]
cost, parella de profes 0 [0, 0]
cost, parella de profes 0 [0, 0]
cost, parella de profes 0 [0, 0]
cost, parella de profes 0 [0, 0]
cost, parella de profes 0 [0, 0]
cost, parella de profes 0 [0, 0]
cost, parella de profes 0 [0, 0]
cost, parella de profes 0 [0, 0]
cost, 

In [30]:
print(Chromo[0][0:7])
print(Chromo[1][0:7])
print(Chromo[0][7:14])
print(Chromo[1][7:14])

[[0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0]]
[[0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0]]
[[0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0]]
[[0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0]]


In [31]:
#Ojo!!!
#c=ClasseAssignatura2[0]-> Això causa problemes!!!!
c=ClasseAssignatura2[0][:]
c[1]="hello"
print(ClasseAssignatura2)

[[[3, 1, 0, 0], [2, 2, 0, 0], [4, 3, 0, 0], [3, 1, 0, 0], [3, 4, 5, 0], [3, 4, 0, 7], [3, 6, 0, 6]], [[3, 1, 0, 0], [4, 2, 0, 4], [3, 3, 0, 0], [4, 4, 0, 2], [6, 5, 0, 0], [2, 6, 0, 0], [2, 1, 0, 0]]]


In [ ]:
Chromo=[[[0,0] for i in range(TimeP)] for i in range(classes)]


In [ ]:
Calculate_TeachingHours()
print(Thours)

In [ ]:
Chromo

In [ ]:
Chromo

In [ ]:
print(poblacio)
print(" ")
Chromo

In [ ]:
poblacio[-1][0]

In [ ]:


TeacherNoDays=[[1,0,1,1,1],[1,1,1,1,1],[0,1,1,1,1],[1,1,1,1,0],[1,1,1,1,1],[1,1,1,1,1]]

def calc_teacher_unable():
    

In [11]:
import random
costs=[[],[]]
costs[0] = [i for i in range (population)]
costs[1] = [random.randint(0,10) for i in range (population)]


costs

[[0, 1, 2, 3, 4], [8, 4, 7, 4, 3]]

In [12]:
costs1 = [random.randint(0,10) for i in range (population)]
costs1

[7, 6, 0, 3, 4]

In [13]:
import operator

costs={}
for i in range(population):
    costs[i]=costs1[i]
print(costs)

sorted_costs = sorted(costs.items(), key=operator.itemgetter(1))
sorted_costs.reverse()
print(sorted_costs)

{0: 7, 1: 6, 2: 0, 3: 3, 4: 4}
[(0, 7), (1, 6), (4, 4), (3, 3), (2, 0)]


In [17]:
nova_poblacio = []

N = population
n_min = 0.2
n_max = 2 - n_min

print(len(sorted_costs))
probability = []

for i in range(N):
    
    probability.append((1/N)*(n_min+(n_max - n_min)*(i)/(N-1)))
    #probability.append(np.divide(1,N)*np.divide(n_min+(n_max - n_min)*(i-1),(N-1)))
    
print(probability)
print(sum(probability))

mapped = []
mapped.append(0)

for i in range(len(probability)-1):
    mapped.append(mapped[i] + probability[i])

mapped.append(1)
print(mapped)

for i in range(N):
    rand = random.random()
    print(rand)

    for i in range(len(probability)):
        if (rand > mapped[i]) & (rand <= mapped[i+1]):
            cromo_index = i
            break
            
    print(cromo_index)
    # Aqui s'ha triat el cromosoma que s'ha de reproduir. Ara l'hem de reproduir
    
    nova_poblacio.append(poblacio[sorted_costs[cromo_index][0]])

print(poblacio[0])
print("------------")
print(poblacio[1])
print("------------")
print(poblacio[2])
print("------------")
print(poblacio[3])
print("------------")
print(poblacio[4])
print("----------------------------------------------------------------")

print(nova_poblacio[0])
print("------------")
print(nova_poblacio[1])
print("------------")
print(nova_poblacio[2])
print("------------")
print(nova_poblacio[3])

5
[0.04000000000000001, 0.12000000000000002, 0.2, 0.28, 0.36000000000000004]
1.0000000000000002
[0, 0.04000000000000001, 0.16000000000000003, 0.36000000000000004, 0.6400000000000001, 1]
0.9828706772992597
4
0.7476444297218156
4
0.007139715806536051
0
0.7430583096748892
4
0.7449079359335413
4
[[[3, 0], [1, 0], [2, 0], [1, 0], [2, 0], [1, 0], [1, 0], [6, 4], [6, 4], [6, 4], [3, 0], [3, 0], [3, 0], [4, 5], [4, 5], [1, 0], [1, 0], [4, 5], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0]], [[2, 4], [4, 2], [1, 0], [4, 2], [3, 0], [4, 2], [3, 0], [6, 0], [6, 0], [1, 0], [3, 0], [5, 0], [1, 0], [1, 0], [5, 0], [1, 0], [5, 0], [5, 0], [5, 0], [5, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0]]]
------------
[[[6, 4], [2, 0], [4, 5], [1, 0], [3, 0], [1, 0], [1, 0], [6, 4], [4, 5], [2, 0], [6, 4], [4, 5], [1, 0], [3, 0], [1, 0], [3, 0],