In [1]:
import pandas as pd
import numpy as np
from random import randrange
import copy

In [2]:
#Inicialitzacions
classes=2
TimeP=35
Chromo=[]
#Chromo=np.zeros((classes, TimeP),dtype=int)
#Chromo=Chromo.tolist()
Chromo=[[[0,0] for i in range(TimeP)] for i in range(classes)]
population=5
TeachingHours=np.array([11,6,7,10,9,5])
ZerosT=np.zeros((len(TeachingHours),),dtype=int)
ZerosT=TeachingHours*0
ClassesProfe=[]
numTeachers=6
Thours=np.zeros((classes, numTeachers),dtype=int)
AssigsProfe=[[[] for i in range(numTeachers)] for i in range(classes)]
Thours=Thours.tolist()
#0->Profe a l'institut, 1-> profe no és a l'institut
TeacherNoDays=[[1,0,0,0,0],[0,1,0,0,0],[0,0,0,0,0],[0,0,0,0,0],[0,0,0,0,0],[0,0,0,0,0]]
Total_Teachers=6
TeachersTimeTable=[[[] for i in range(TimeP)] for i in range(numTeachers)]

In [3]:
import copy
ClasseAssignatura2=[[[3,1,0,0],[2,2,0,0],[4,3,0,0],[3,1,0,0],[3,4,5,0],[3,4,0,7],[3,6,0,6]],
                    [[3,1,0,0],[4,2,0,4],[3,3,0,0],[4,4,0,2],[6,5,0,0],[2,6,0,0],[2,1,0,0]]]
print(ClasseAssignatura2)
print(" ")
ClasseAssignatura3=copy.deepcopy(ClasseAssignatura2)
#ClasseAssignatura3 = ClasseAssignatura2[:]
print(ClasseAssignatura3)
print(" ")
print(Chromo)

[[[3, 1, 0, 0], [2, 2, 0, 0], [4, 3, 0, 0], [3, 1, 0, 0], [3, 4, 5, 0], [3, 4, 0, 7], [3, 6, 0, 6]], [[3, 1, 0, 0], [4, 2, 0, 4], [3, 3, 0, 0], [4, 4, 0, 2], [6, 5, 0, 0], [2, 6, 0, 0], [2, 1, 0, 0]]]
 
[[[3, 1, 0, 0], [2, 2, 0, 0], [4, 3, 0, 0], [3, 1, 0, 0], [3, 4, 5, 0], [3, 4, 0, 7], [3, 6, 0, 6]], [[3, 1, 0, 0], [4, 2, 0, 4], [3, 3, 0, 0], [4, 4, 0, 2], [6, 5, 0, 0], [2, 6, 0, 0], [2, 1, 0, 0]]]
 
[[[0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0]], [[0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0]]]


In [4]:
def Calculate_TeachingHours():
    c=0
    
    for classe in ClasseAssignatura2:
        
        for assignatura in classe:
            professor=assignatura[1]
            hores=assignatura[0]
            #Per casa assignatura sumam en 1 el num d'assignatures al profe que la dona
            #Només calculam les hores de profe "principal"-> REVISAR SI AIXÒ SUPOSA ALGUN PROBLEMA
            #ANAR ALERTA!!!!!!!!!!!!!!!!!!!!!!
            #Aquest valor l'utilitzarem al cost de les classes
            #print(AssigsProfe)
            #AssigsProfeh[c][professor-1].append([hores])
            #AssigProfeU[c][professor-1].append([0])
            #print(AssigsProfe)
            Thours[c][professor-1]=Thours[c][professor-1]+hores
            #Si hi ha SC:
            if assignatura[2]!=0:
                profeSC=assignatura[2]
                Thours[c][profeSC-1]=Thours[c][profeSC-1]+hores  
            
        c=c+1;

    print(Thours)
    #print(AssigsProfe)
#print(" ")
#print(ClasseAssignatura2)

In [5]:
Thours=np.zeros((classes, numTeachers),dtype=int)
#numAssigProfe=np.zeros((classes, numTeachers),dtype=int)
AssigsProfe=[[[] for i in range(numTeachers)] for i in range(classes)]
print(AssigsProfe)
print(" ")
print(ClasseAssignatura2)
print(" ")
Calculate_TeachingHours()
print(Thours)

[[[], [], [], [], [], []], [[], [], [], [], [], []]]
 
[[[3, 1, 0, 0], [2, 2, 0, 0], [4, 3, 0, 0], [3, 1, 0, 0], [3, 4, 5, 0], [3, 4, 0, 7], [3, 6, 0, 6]], [[3, 1, 0, 0], [4, 2, 0, 4], [3, 3, 0, 0], [4, 4, 0, 2], [6, 5, 0, 0], [2, 6, 0, 0], [2, 1, 0, 0]]]
 
[[6 2 4 6 3 3]
 [5 4 3 4 6 2]]
[[6 2 4 6 3 3]
 [5 4 3 4 6 2]]


In [6]:
import copy

In [7]:
#Recorrem les assignatures d'una classe
#[slots,professor1,professorSC,AssignaturaCT]

def decrementarHores(teacher,classe,Thours):
    #Recorrem les assignatures de la classe buscant les que fa el profe teacher
    #c= assignatures de la classe 1
    
    idxAssigntr=0
    print("profe= ", teacher)
    c=ClasseAssignatura3[classe][:]
    print("c",c)
    for assignatura in c:
        print("assignatura[1]==teacher",assignatura[1]==teacher)
        print("assignatura[0]>0",assignatura[0]>0)
        if assignatura[1]==teacher and assignatura[0]>0:
            print("idxAssigntr",idxAssigntr)
            print("classe",classe)
            #Decrementam 
            ClasseAssignatura3[classe][idxAssigntr][0]=ClasseAssignatura3[classe][idxAssigntr][0]-1
            Thours[classe][teacher-1]=Thours[classe][teacher-1]-1
            teachers=[teacher,0]
            print("cas1")
            
            #si hi ha SC les decrementam de Thours
            if ClasseAssignatura3[classe][idxAssigntr][2]!=0:
                
                teacher2=ClasseAssignatura3[classe][idxAssigntr][2]
                print("teacher2= ",teacher2)
                Thours[classe][teacher2-1]=Thours[classe][teacher2-1]-1
                teachers=[teacher,teacher2]
                print("cas2")
                
            #Si hi ha coteaching llevam les hores de l'altra assignatura:
            if ClasseAssignatura3[classe][idxAssigntr][3]!=0:
                #Seleccionam el valor de l'index de l'assignatura amb la que hi ha coteaching
                AssigCT=ClasseAssignatura3[classe][idxAssigntr][3]
                print("AssigCT",AssigCT)
                #Decrementam en 1h les hores pendents d'assignar de l'assignatura de CT
                ClasseAssignatura3[classe][AssigCT-1][0]=ClasseAssignatura3[classe][AssigCT-1][0]-1
                teacherCT=ClasseAssignatura3[classe][AssigCT-1][1]
                Thours[classe][teacherCT-1]=Thours[classe][teacherCT-1]-1
                teachers=[teacher,teacherCT]
                print("cas3")
            
            break
                
        idxAssigntr=idxAssigntr+1
    #c=ClasseAssignatura3[classe][:]
    print("c",c)
    #print("ClasseAssignatura3 decrem",ClasseAssignatura3)
    return Thours,teachers
                
        

In [8]:
poblacio=[0 for i in range(population)]
for i in range(population):
    Thours=np.zeros((classes, numTeachers),dtype=int)
    Calculate_TeachingHours()
    ClasseAssignatura3=copy.deepcopy(ClasseAssignatura2)
    print(Thours)
    for classe in range(classes):
        for hour in range(TimeP):
            c=ClasseAssignatura2[classe]
            ok=False
            #Chose a teacher at random 
            print("classe= ",classe)
            print("Thours",Thours[classe])
            
            # Miram si s'han assignat totes les hores d'una classe.
            if np.array_equal(ZerosT,Thours[classe])==False:
                while ok==False:#mirar que no sigui que no et quedin profes i se quedi aqui infinitament
                    teacher=randrange(1, numTeachers+1)
                    print("teacher",teacher)
                    for j in c:
                        #print("i",i) 
                        #print("c",c)
                        #print("i[1]",i[1])
                        #print(Thours[classe][teacher-1])
                        if(j[1]==teacher) and Thours[classe][teacher-1]!=0:
                            ok=True
                #ok=False       
                print("thours",Thours[classe][teacher-1])
                print("selected teacher", teacher)
                print("decrementam ")
                Thours,teachers=decrementarHores(teacher,classe,Thours)
                print("classe",classe)
                print("hours",hour)                
                Chromo[classe][hour]=teachers
                print("TeacherHours, teachers :",Thours[classe], teachers)

                print("profes",teachers)
                
            
                #Assignar slot buit
            #print("buit")
    print("index",i)
    print("--------------------------------------------------------------------------------------")
    print(Chromo)
    poblacio[i]=copy.deepcopy(Chromo)
    #poblacio[i]=Chromo.    
    #break

                            
                

                        
                #Now we have a teacher!!!
                #print(teacher)

                #Decrementam les hores agafant una hora en concret d'una assignatura
                
                #TeachingHours[teacher-1]=TeachingHours[teacher-1]-1
                #TeachingHours=a
      

        
#Si algun teacher només està de subclasse mai el decrementa directament !Alerta!  

[[6 2 4 6 3 3]
 [5 4 3 4 6 2]]
[[6 2 4 6 3 3]
 [5 4 3 4 6 2]]
classe=  0
Thours [6 2 4 6 3 3]
teacher 4
thours 6
selected teacher 4
decrementam 
profe=  4
c [[3, 1, 0, 0], [2, 2, 0, 0], [4, 3, 0, 0], [3, 1, 0, 0], [3, 4, 5, 0], [3, 4, 0, 7], [3, 6, 0, 6]]
assignatura[1]==teacher False
assignatura[0]>0 True
assignatura[1]==teacher False
assignatura[0]>0 True
assignatura[1]==teacher False
assignatura[0]>0 True
assignatura[1]==teacher False
assignatura[0]>0 True
assignatura[1]==teacher True
assignatura[0]>0 True
idxAssigntr 4
classe 0
cas1
teacher2=  5
cas2
c [[3, 1, 0, 0], [2, 2, 0, 0], [4, 3, 0, 0], [3, 1, 0, 0], [2, 4, 5, 0], [3, 4, 0, 7], [3, 6, 0, 6]]
classe 0
hours 0
TeacherHours, teachers : [6 2 4 5 2 3] [4, 5]
profes [4, 5]
classe=  0
Thours [6 2 4 5 2 3]
teacher 2
thours 2
selected teacher 2
decrementam 
profe=  2
c [[3, 1, 0, 0], [2, 2, 0, 0], [4, 3, 0, 0], [3, 1, 0, 0], [2, 4, 5, 0], [3, 4, 0, 7], [3, 6, 0, 6]]
assignatura[1]==teacher False
assignatura[0]>0 True
assignatura[1]=

assignatura[1]==teacher True
assignatura[0]>0 True
idxAssigntr 6
classe 1
cas1
c [[0, 1, 0, 0], [0, 2, 0, 4], [0, 3, 0, 0], [0, 4, 0, 2], [5, 5, 0, 0], [0, 6, 0, 0], [1, 1, 0, 0]]
classe 1
hours 13
TeacherHours, teachers : [1 0 0 0 5 0] [1, 0]
profes [1, 0]
classe=  1
Thours [1 0 0 0 5 0]
teacher 6
teacher 2
teacher 1
thours 1
selected teacher 1
decrementam 
profe=  1
c [[0, 1, 0, 0], [0, 2, 0, 4], [0, 3, 0, 0], [0, 4, 0, 2], [5, 5, 0, 0], [0, 6, 0, 0], [1, 1, 0, 0]]
assignatura[1]==teacher True
assignatura[0]>0 False
assignatura[1]==teacher False
assignatura[0]>0 False
assignatura[1]==teacher False
assignatura[0]>0 False
assignatura[1]==teacher False
assignatura[0]>0 False
assignatura[1]==teacher False
assignatura[0]>0 True
assignatura[1]==teacher False
assignatura[0]>0 False
assignatura[1]==teacher True
assignatura[0]>0 True
idxAssigntr 6
classe 1
cas1
c [[0, 1, 0, 0], [0, 2, 0, 4], [0, 3, 0, 0], [0, 4, 0, 2], [5, 5, 0, 0], [0, 6, 0, 0], [0, 1, 0, 0]]
classe 1
hours 14
TeacherHours, 

Thours [0 0 0 0 0 0]
classe=  0
Thours [0 0 0 0 0 0]
classe=  0
Thours [0 0 0 0 0 0]
classe=  0
Thours [0 0 0 0 0 0]
classe=  0
Thours [0 0 0 0 0 0]
classe=  0
Thours [0 0 0 0 0 0]
classe=  1
Thours [5 4 3 4 6 2]
teacher 5
thours 6
selected teacher 5
decrementam 
profe=  5
c [[3, 1, 0, 0], [4, 2, 0, 4], [3, 3, 0, 0], [4, 4, 0, 2], [6, 5, 0, 0], [2, 6, 0, 0], [2, 1, 0, 0]]
assignatura[1]==teacher False
assignatura[0]>0 True
assignatura[1]==teacher False
assignatura[0]>0 True
assignatura[1]==teacher False
assignatura[0]>0 True
assignatura[1]==teacher False
assignatura[0]>0 True
assignatura[1]==teacher True
assignatura[0]>0 True
idxAssigntr 4
classe 1
cas1
c [[3, 1, 0, 0], [4, 2, 0, 4], [3, 3, 0, 0], [4, 4, 0, 2], [5, 5, 0, 0], [2, 6, 0, 0], [2, 1, 0, 0]]
classe 1
hours 0
TeacherHours, teachers : [5 4 3 4 5 2] [5, 0]
profes [5, 0]
classe=  1
Thours [5 4 3 4 5 2]
teacher 2
thours 4
selected teacher 2
decrementam 
profe=  2
c [[3, 1, 0, 0], [4, 2, 0, 4], [3, 3, 0, 0], [4, 4, 0, 2], [5, 5, 0

assignatura[1]==teacher True
assignatura[0]>0 True
idxAssigntr 0
classe 0
cas1
c [[0, 1, 0, 0], [0, 2, 0, 0], [4, 3, 0, 0], [3, 1, 0, 0], [2, 4, 5, 0], [0, 4, 0, 7], [0, 6, 0, 6]]
classe 0
hours 8
TeacherHours, teachers : [3 0 4 2 2 0] [1, 0]
profes [1, 0]
classe=  0
Thours [3 0 4 2 2 0]
teacher 3
thours 4
selected teacher 3
decrementam 
profe=  3
c [[0, 1, 0, 0], [0, 2, 0, 0], [4, 3, 0, 0], [3, 1, 0, 0], [2, 4, 5, 0], [0, 4, 0, 7], [0, 6, 0, 6]]
assignatura[1]==teacher False
assignatura[0]>0 False
assignatura[1]==teacher False
assignatura[0]>0 False
assignatura[1]==teacher True
assignatura[0]>0 True
idxAssigntr 2
classe 0
cas1
c [[0, 1, 0, 0], [0, 2, 0, 0], [3, 3, 0, 0], [3, 1, 0, 0], [2, 4, 5, 0], [0, 4, 0, 7], [0, 6, 0, 6]]
classe 0
hours 9
TeacherHours, teachers : [3 0 3 2 2 0] [3, 0]
profes [3, 0]
classe=  0
Thours [3 0 3 2 2 0]
teacher 6
teacher 4
thours 2
selected teacher 4
decrementam 
profe=  4
c [[0, 1, 0, 0], [0, 2, 0, 0], [3, 3, 0, 0], [3, 1, 0, 0], [2, 4, 5, 0], [0, 4, 0, 

assignatura[0]>0 True
idxAssigntr 2
classe 1
cas1
c [[0, 1, 0, 0], [0, 2, 0, 4], [0, 3, 0, 0], [0, 4, 0, 2], [0, 5, 0, 0], [0, 6, 0, 0], [0, 1, 0, 0]]
classe 1
hours 19
TeacherHours, teachers : [0 0 0 0 0 0] [3, 0]
profes [3, 0]
classe=  1
Thours [0 0 0 0 0 0]
classe=  1
Thours [0 0 0 0 0 0]
classe=  1
Thours [0 0 0 0 0 0]
classe=  1
Thours [0 0 0 0 0 0]
classe=  1
Thours [0 0 0 0 0 0]
classe=  1
Thours [0 0 0 0 0 0]
classe=  1
Thours [0 0 0 0 0 0]
classe=  1
Thours [0 0 0 0 0 0]
classe=  1
Thours [0 0 0 0 0 0]
classe=  1
Thours [0 0 0 0 0 0]
classe=  1
Thours [0 0 0 0 0 0]
classe=  1
Thours [0 0 0 0 0 0]
classe=  1
Thours [0 0 0 0 0 0]
classe=  1
Thours [0 0 0 0 0 0]
classe=  1
Thours [0 0 0 0 0 0]
index 2
--------------------------------------------------------------------------------------
[[[6, 4], [4, 5], [2, 0], [1, 0], [1, 0], [6, 4], [6, 4], [2, 0], [1, 0], [3, 0], [4, 5], [1, 0], [3, 0], [3, 0], [3, 0], [1, 0], [1, 0], [4, 5], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0

assignatura[1]==teacher False
assignatura[0]>0 True
assignatura[1]==teacher False
assignatura[0]>0 True
assignatura[1]==teacher False
assignatura[0]>0 True
assignatura[1]==teacher False
assignatura[0]>0 True
assignatura[1]==teacher True
assignatura[0]>0 True
idxAssigntr 4
classe 1
cas1
c [[3, 1, 0, 0], [2, 2, 0, 4], [1, 3, 0, 0], [2, 4, 0, 2], [2, 5, 0, 0], [0, 6, 0, 0], [2, 1, 0, 0]]
classe 1
hours 9
TeacherHours, teachers : [5 2 1 2 2 0] [5, 0]
profes [5, 0]
classe=  1
Thours [5 2 1 2 2 0]
teacher 1
thours 5
selected teacher 1
decrementam 
profe=  1
c [[3, 1, 0, 0], [2, 2, 0, 4], [1, 3, 0, 0], [2, 4, 0, 2], [2, 5, 0, 0], [0, 6, 0, 0], [2, 1, 0, 0]]
assignatura[1]==teacher True
assignatura[0]>0 True
idxAssigntr 0
classe 1
cas1
c [[2, 1, 0, 0], [2, 2, 0, 4], [1, 3, 0, 0], [2, 4, 0, 2], [2, 5, 0, 0], [0, 6, 0, 0], [2, 1, 0, 0]]
classe 1
hours 10
TeacherHours, teachers : [4 2 1 2 2 0] [1, 0]
profes [1, 0]
classe=  1
Thours [4 2 1 2 2 0]
teacher 6
teacher 1
thours 4
selected teacher 1
dec

Thours [0 0 0 0 0 0]
classe=  0
Thours [0 0 0 0 0 0]
classe=  0
Thours [0 0 0 0 0 0]
classe=  0
Thours [0 0 0 0 0 0]
classe=  0
Thours [0 0 0 0 0 0]
classe=  0
Thours [0 0 0 0 0 0]
classe=  0
Thours [0 0 0 0 0 0]
classe=  0
Thours [0 0 0 0 0 0]
classe=  0
Thours [0 0 0 0 0 0]
classe=  1
Thours [5 4 3 4 6 2]
teacher 5
thours 6
selected teacher 5
decrementam 
profe=  5
c [[3, 1, 0, 0], [4, 2, 0, 4], [3, 3, 0, 0], [4, 4, 0, 2], [6, 5, 0, 0], [2, 6, 0, 0], [2, 1, 0, 0]]
assignatura[1]==teacher False
assignatura[0]>0 True
assignatura[1]==teacher False
assignatura[0]>0 True
assignatura[1]==teacher False
assignatura[0]>0 True
assignatura[1]==teacher False
assignatura[0]>0 True
assignatura[1]==teacher True
assignatura[0]>0 True
idxAssigntr 4
classe 1
cas1
c [[3, 1, 0, 0], [4, 2, 0, 4], [3, 3, 0, 0], [4, 4, 0, 2], [5, 5, 0, 0], [2, 6, 0, 0], [2, 1, 0, 0]]
classe 1
hours 0
TeacherHours, teachers : [5 4 3 4 5 2] [5, 0]
profes [5, 0]
classe=  1
Thours [5 4 3 4 5 2]
teacher 3
thours 3
selected teac

In [9]:
print(Chromo)
print(" ")
print(poblacio[1])
print(" ")
print(poblacio[2])
print(" ")
print(poblacio[3])
print(" ")
print(poblacio[4])

[[[6, 4], [3, 0], [1, 0], [4, 5], [4, 5], [4, 5], [2, 0], [1, 0], [4, 6], [4, 6], [1, 0], [1, 0], [3, 0], [1, 0], [3, 0], [3, 0], [1, 0], [2, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0]], [[5, 0], [3, 0], [5, 0], [4, 2], [5, 0], [5, 0], [4, 2], [6, 0], [2, 4], [5, 0], [1, 0], [1, 0], [2, 4], [3, 0], [3, 0], [6, 0], [1, 0], [1, 0], [5, 0], [1, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0]]]
 
[[[2, 0], [6, 4], [4, 5], [3, 0], [3, 0], [2, 0], [6, 4], [1, 0], [4, 5], [4, 5], [1, 0], [6, 4], [3, 0], [1, 0], [1, 0], [3, 0], [1, 0], [1, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0]], [[5, 0], [2, 4], [2, 4], [2, 4], [1, 0], [4, 2], [3, 0], [3, 0], [5, 0], [1, 0], [3, 0], [6, 0], [5, 0], [5, 0], [5, 0], [6, 0], [1, 0], [1, 0], [1, 0

In [10]:
def CTeacherUnable(teachers,hora):
    #print("hora",hora)
    dia=int(hora/7)
    #print("dia",dia)
    cost=0
    #print("profes",teachers)
    
    for teacher in teachers:
        if teacher != 0: 
            #print("at School?")
            #print(teacher,dia)
            #print(TeacherNoDays[teacher-1][dia])
            cost=cost+TeacherNoDays[teacher-1][dia]
    return cost
    

In [11]:
#for i in range(len(individu[0])):
#    print(individu[0][i])
#    print(individu[1][i])
#    print("--------")
#print(individu[0][7:13])
#print(individu[1][7:13])
print(individu[0][0])
a=individu[:]
a[0][0]=[0,0]
TeachersTimeTable=np.zeros((numTeachers,TimeP), dtype=int)

NameError: name 'individu' is not defined

In [ ]:
print(TeachersTimeTable[0])


In [ ]:
#TeachersTimeTable=np.zeros((numTeachers,TimeP), dtype=int).tolist()
#print(TeachersTimeTable)
#Funció per crear l'horari de cada un dels profes per cada individu :)
#Crec que funciona bé però s'ha de repassar!!!
def createTeachersTimeP(teachers,i_classe,i_timePeriod):
    for teacher in teachers:
        if teacher!=0:
            #Guardam la classe que fa aquest profe en aquesta hora
            TeachersTimeTable[teacher-1][i_timePeriod]=i_classe+1
            #TeachersTimeTable[teacher-1][i_timePeriod].append(i_classe+1)

Teacher lessons’ dispersion: For each teacher the following subcost is added: IDWT ∗ HOURS ∗ BASEDAYS, where
HOURS is the total number of time periods that are different compared to the ideal dispersion teacher’s timetable
and DAYS is the number of days in the teacher’s timetable that such a declination from the ideal case exists.

In [ ]:
TeacherIdealHours=IdealTeachingDayHours()
print(TeachingHours)
TeacherIdealHours

In [ ]:
def IdealTeachingDayHours():
    TeacherIdealHours=[]
    for t in range (numTeachers):
        horesideals=TeachingHours[t]/(5-np.count_nonzero(TeacherNoDays[t]))
        TeacherIdealHours.append(horesideals)
    return TeacherIdealHours

In [ ]:
#Cost Teacher empty spaces and dispersion
def CostTeacherE_i_D():
    costTeacherEmpty=[]
    costTeacherDisp=[]
    cTeacherDisph=0
    cTeacherDispd=0
    hoursTeacher=0#num hores que fa un profe cada dia
    TotalcostTeacherDisp=0
    EmptyFound=False
    t=0#index del professor
    for teacher in TeachersTimeTable:
        h=0
        chours=0#cost hores
        cdays=0 #cost dies
        for day in range(5):
            for hour in range(7):
                
                if teacher[h]!=0:
                    hoursTeacher=hoursTeacher+1
                    #Si trobam una hora ocupada després de trobar un espai buit
                    if EmptyFound==True:
                        chours=chours+1
                        incr=True
                        EmptyFound=False
                    
                elif teacher[h]==0:
                    EmptyFound=True
                    
                h=h+1#index de les hores
                
            #Quan canviam de dia incrementam el cost del dia i resetejam els paràmetres:
            #Si les hores que fa un professor un dia es desvien en més de 1 de la mitjana ideal:
            hour_difference=abs(hoursTeacher-TeacherIdealHours[t])
            if hour_difference > 1:
                cTeacherDisph=cTeacherDisph+hour_difference
                cTeacherDispd=cTeacherDispd+1
            if incr>0:
                cdays=cdays+1
            hoursTeacher=0
            incr=False
            EmptyFound=False
        #Aquí calcul del cost
        
        t=t+1
        costTeacherDisp.append([cTeacherDisph,cTeacherDispd])
        cTeacherDisph=0
        cTeacherDispd=0
        costTeacherEmpty.append([chours,cdays])
        chours=0
        cdays=0
        #En lloc d'això aquí aniria la part de la funció de cost corresponent
    return costTeacherEmpty 
            

In [ ]:
#Cost Teacher empty spaces and dispersion
def CostTeacherEmpySpaces():
    costTeacherEmpty=[]
    EmptyFound=False
    for teacher in TeachersTimeTable:
        h=0
        chours=0#cost hores
        cdays=0 #cost dies
        for day in range(5):
            for hour in range(7):
                #Si trobam una hora ocupada després de trobar un espai buit
                if teacher[h]!=0 and EmptyFound==True:
                    chours=chours+1
                    incr=True
                    EmptyFound=False
                    
                elif teacher[h]==0:
                    EmptyFound=True
                    
                h=h+1#index de les hores
                
            #Quan canviam de dia incrementam el cost del dia i resetejam els paràmetres:
            if incr>0:
                cdays=cdays+1
            incr=False
            EmptyFound=False
        costTeacherEmpty.append([chours,cdays])
        #En lloc d'això aquí aniria la part de la funció de cost corresponent
    return costTeacherEmpty 
            

In [ ]:
#print(Chromo[0][:])
classe1=Chromo[0][:]
len(classe1)
a=[5,5,6]
a.remove(5)
h=0
classe1[7]=1
classe1[0:7]
print(classe1)
classe1[7:7+7]

In [ ]:
AssigsProfe

In [ ]:
#1 Llevar els 0 xq els buits no interessen
classe1=Chromo[0][:]#Igual aixo ha de ser un copy
print(teacherP)
h=0
c=0#index de la classe
for day in range(5):
    AssigDia=classe1[h:h+7]
    teach=[elem for elem in teacherP if elem != [0,0]]
    teachset=set(teach)
    for elem in teachset:
        teach.remove(elem)
    #Ara tenim el conjunt original únicament amb aquells elements que estan repetits
    for elem in teach:
        AssigsProfe[c][]
        
    h=h+7
    
    

In [ ]:
classe1=[[4, 5], [6, 4], [3, 0], [1, 0], [6, 4], [1, 0], [2, 0], [4, 5], [3, 0], [1, 0], [3, 0], [2, 0], [1, 0], [4, 5], [1, 0], [1, 0], [3, 0]]

In [ ]:
from copy import deepcopy
print(AssigsProfe[0][0])
a=deepcopy(AssigsProfe[0][0])
print(a)
a[0][1]=7
print(AssigsProfe[0][0])
print(a)


In [ ]:
classe=classe1.copy()
h=0
c=0#index de la classe
#Recorrem cada hora
for teachers in classe:
    AssigDia=classe[h:h+7]
    teach=[elem for elem in teacherP if elem != [0,0]]
    for profe in teach:
        profe=teach[0]-1
        assigs=deepcopy(AssigsProfe[c][profe])
        i=0
        for t in AssigsProfe[c][profe]:
        #Recorr les assignatures que fa aquest profe les hores
        AssigsProfe[c][profe][i]
        i=i+1
    teachers
    h=h+7

In [ ]:
#Per cada classe mirar les hores que ha de fer el profe i repartirles entre els dies que el profe és a l'institut i mirar 
#i mirar amb això si es repeteixen assignatures 
def costClLessDispersion(classe,c):
    h=0
    #Recorrem cada hora
    for teachers in classe:
        if h%7==0:
            #canvi de dia
        profe=teachers[0]
        teachers
        h=h+1
        
    

In [ ]:
#Class’s empty spaces cost calculat i funciona correctament :)
individu=Chromo[:]
costClEmptySpaces=0
emptyHour=False
    
for classe in individu:
    timeP=0
    cLessonDispersion=costClLessDispersion(classe)
    for teachers in classe:
        #Si canviam de dia resetejam les variables          
        if timeP%7==0:
            emptyHour=False
        #Si hi ha una hora buida activam empty hour  
        if teachers==[0,0]:
            emptyHour=True
        #Si hi ha una hora ocupada i prèviament hi ha hagut una hora buida el mateix dia sumam 1 al cost
        elif emptyHour==True:
            emptyHour=False
            costClEmptySpaces=costClEmptySpaces+1
        timeP=timeP+1
costClEmptySpaces    

In [ ]:
TeachersTimeTable=[[[] for i in range(TimeP)] for i in range(numTeachers)]
#print(TeachersTimeTable)

In [ ]:
#Cost 1 i cost 2 calculats i funcionen correctament :)
individu=Chromo[:]
costUnable=0
costMore1class=0
TeachersTimeTable=[[[] for i in range(TimeP)] for i in range(numTeachers)]
#TeachersTimeTable=np.zeros((numTeachers,TimeP), dtype=int)
#llista dels profes assignats a una hora
teacher_timeP=[]
#for individu in population:
for i_timePeriod in range(TimeP):
    teacher_timeP=[]
    for i_classe in range(classes):
        
        teachers=individu[i_classe][i_timePeriod]
        #Cream els horaris dels profes
        createTeachersTimeP(teachers,i_classe,i_timePeriod)
        #Calculam el cost de si el profe no és a l'institut
        costU=CTeacherUnable(teachers,i_timePeriod)
        #if costU!=0:
            #print("--------------------")
            #print(i_timePeriod)
            #print("teachers",teachers)
            #print("costU",costU)
            #print("costUnable",costUnable)
            
           
        teacher_timeP.extend(teachers)
        costUnable=costUnable+costU
        #print("cost, i_timePeriod",costU,i_timePeriod)
        
    #Eliminam de la llista els buits(teacher 0) ja que teacher 0 no és cap teacher
    teacher_timeP=[elem for elem in teacher_timeP if elem != 0]
    #print(set(teacher_timeP))
    #print(teacher_timeP)
    costM1c=len(teacher_timeP)-len(set(teacher_timeP))
    costMore1class=costMore1class+costM1c
print("c1 ",costUnable)
print("c2 ",costMore1class)
print(individu[0][0:15])
print(individu[1][0:15])
#print(individu[0][8:15])
#print(individu[1][8:15])
print(TeacherNoDays)

In [ ]:
Calculate_TeachingHours()
numAssigProfe

In [ ]:
individu=Chromo[:]
print(individu)
costUnable=0
for classe in individu:
    hora=0
    for TimePeriod in classe:
        costU=CTeacherUnable(TimePeriod,hora)
        costUnable=costUnable+costU
        print("cost, parella de profes",costU,TimePeriod)
        hora=hora+1
print(costUnable)

In [ ]:
individu=Chromo[:]
print(individu)
costUnable=0
for classe in individu:
    hora=0
    for TimePeriod in classe:
        costU=CTeacherUnable(TimePeriod,hora)
        costUnable=costUnable+costU
        print("cost, parella de profes",costU,TimePeriod)
        hora=hora+1
print(costUnable)
    

In [ ]:
print(Chromo[0][0:7])
print(Chromo[1][0:7])
print(Chromo[0][7:14])
print(Chromo[1][7:14])

In [ ]:
#Ojo!!!
#c=ClasseAssignatura2[0]-> Això causa problemes!!!!
c=ClasseAssignatura2[0][:]
c[1]="hello"
print(ClasseAssignatura2)

In [ ]:
Chromo=[[[0,0] for i in range(TimeP)] for i in range(classes)]


In [ ]:
Calculate_TeachingHours()
print(Thours)

In [ ]:
Chromo

In [ ]:
Chromo

In [ ]:
print(poblacio)
print(" ")
Chromo

In [ ]:
poblacio[-1][0]

In [ ]:
TeacherNoDays=[[1,0,1,1,1],[1,1,1,1,1],[0,1,1,1,1],[1,1,1,1,0],[1,1,1,1,1],[1,1,1,1,1]]

def calc_teacher_unable():
    