## Inicialitzacions

In [1]:
import pandas as pd
import numpy as np
from random import randrange
import copy
import random
import operator

In [2]:
#Inicialitzacions
classes=2
TimeP=35
Chromo=[]
#Chromo=np.zeros((classes, TimeP),dtype=int)
#Chromo=Chromo.tolist()
Chromo=[[[0,0] for i in range(TimeP)] for i in range(classes)]
population=5
TeachingHours=np.array([11,6,7,10,9,5])
ZerosT=np.zeros((len(TeachingHours),),dtype=int)
ZerosT=TeachingHours*0
ClassesProfe=[]
numTeachers=6
Thours=np.zeros((classes, numTeachers),dtype=int)
AssigsProfe=[[[] for i in range(numTeachers)] for i in range(classes)]
Thours=Thours.tolist()
#0->Profe a l'institut, 1-> profe no és a l'institut
TeacherNoDays=[[1,0,0,0,0],[0,1,0,0,0],[0,0,0,1,1],[0,0,0,0,0],[0,0,1,0,0],[0,0,0,0,0]]
Total_Teachers=6
#TeachersTimeTable=[[[] for i in range(TimeP)] for i in range(numTeachers)]
TeachersTimeTable=[[0 for i in range(TimeP)] for i in range(numTeachers)]

In [3]:
ClasseAssignatura2=[[[3,1,0,0],[2,2,0,0],[4,3,0,0],[3,1,0,0],[3,4,5,0],[3,4,0,7],[3,6,0,6]],
                    [[3,1,0,0],[4,2,0,4],[3,3,0,0],[4,4,0,2],[6,5,0,0],[2,6,0,0],[2,1,0,0]]]
print(ClasseAssignatura2)
print(" ")
#ClasseAssignatura3 = ClasseAssignatura2[:]
ClasseAssignatura3 = copy.deepcopy(ClasseAssignatura2)
print(ClasseAssignatura3)
print(" ")
print(Chromo)

[[[3, 1, 0, 0], [2, 2, 0, 0], [4, 3, 0, 0], [3, 1, 0, 0], [3, 4, 5, 0], [3, 4, 0, 7], [3, 6, 0, 6]], [[3, 1, 0, 0], [4, 2, 0, 4], [3, 3, 0, 0], [4, 4, 0, 2], [6, 5, 0, 0], [2, 6, 0, 0], [2, 1, 0, 0]]]
 
[[[3, 1, 0, 0], [2, 2, 0, 0], [4, 3, 0, 0], [3, 1, 0, 0], [3, 4, 5, 0], [3, 4, 0, 7], [3, 6, 0, 6]], [[3, 1, 0, 0], [4, 2, 0, 4], [3, 3, 0, 0], [4, 4, 0, 2], [6, 5, 0, 0], [2, 6, 0, 0], [2, 1, 0, 0]]]
 
[[[0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0]], [[0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0]]]


In [4]:
def Calculate_TeachingHours():    
    c=0
    for classe in ClasseAssignatura2:

        for assignatura in classe:
            professor=assignatura[1]
            hores=assignatura[0]
            #Per casa assignatura sumam en 1 el num d'assignatures al profe que la dona
            #Només calculam les hores de profe "principal"-> REVISAR SI AIXÒ SUPOSA ALGUN PROBLEMA
            #ANAR ALERTA!!!!!!!!!!!!!!!!!!!!!!
            #Aquest valor l'utilitzarem al cost de les classes
            #print(AssigsProfe)
            #AssigsProfeh[c][professor-1].append([hores])
            #AssigProfeU[c][professor-1].append([0])
            #print(AssigsProfe)
            Thours[c][professor-1]=Thours[c][professor-1]+hores
            #Si hi ha SC:
            if assignatura[2]!=0:
                profeSC=assignatura[2]
                Thours[c][profeSC-1]=Thours[c][profeSC-1]+hores  

        c=c+1;

    print(Thours)
    

In [5]:
Thours=np.zeros((classes, numTeachers),dtype=int)
#numAssigProfe=np.zeros((classes, numTeachers),dtype=int)
AssigsProfe=[[[] for i in range(numTeachers)] for i in range(classes)]
print(AssigsProfe)
print(" ")
print(ClasseAssignatura2)
print(" ")
Calculate_TeachingHours()


[[[], [], [], [], [], []], [[], [], [], [], [], []]]
 
[[[3, 1, 0, 0], [2, 2, 0, 0], [4, 3, 0, 0], [3, 1, 0, 0], [3, 4, 5, 0], [3, 4, 0, 7], [3, 6, 0, 6]], [[3, 1, 0, 0], [4, 2, 0, 4], [3, 3, 0, 0], [4, 4, 0, 2], [6, 5, 0, 0], [2, 6, 0, 0], [2, 1, 0, 0]]]
 
[[6 2 4 6 3 3]
 [5 4 3 4 6 2]]


## Funcions

In [6]:
BASE=1.5
HCW=10#??????
IDWT=3
TEPW=2


In [7]:
def CTeacherUnable(teachers,hora,individu):
    #print("hora",hora)
    dia=int(hora/7)
    #print("dia",dia)
    cost=0
    #print("profes",teachers)
    for teacher in teachers:
        if teacher != 0: 
            #print("at School?")
            #print(teacher,dia)
            #print(TeacherNoDays[teacher-1][dia])
            cost=cost+TeacherNoDays[teacher-1][dia]
            costsTeachers[individu][teacher-1]=costsTeachers[individu][teacher-1]+(HCW*(BASE**3))
    return cost
    

In [8]:
#TeachersTimeTable=np.zeros((numTeachers,TimeP), dtype=int).tolist()
#print(TeachersTimeTable)
#Funció per crear l'horari de cada un dels profes per cada individu :)
#Crec que funciona bé però s'ha de repassar!!!
def createTeachersTimeP(teachers,i_classe,i_timePeriod):
    #print(teachers)
    for teacher in teachers:
        if teacher!=0:
            #Guardam la classe que fa aquest profe en aquesta hora
            TeachersTimeTable[teacher-1][i_timePeriod]=i_classe+1
            #TeachersTimeTable[teacher-1][i_timePeriod].append(i_classe+1)

In [9]:
#Cost Teacher empty spaces and dispersion
def CostTeacherE_i_D():
    costTeacherEmpty=[]
    costTeacherDisp=[]
    cTeacherDisph=0
    cTeacherDispd=0
    hoursTeacher=0#num hores que fa un profe cada dia
    TotalcostTeacherDisp=0
    EmptyFound=False
    t=0#index del professor
    for teacher in TeachersTimeTable:
        h=0
        chours=0#cost hores
        cdays=0 #cost dies
        for day in range(5):
            for hour in range(7):
                
                if teacher[h]!=0:
                    hoursTeacher=hoursTeacher+1
                    #Si trobam una hora ocupada després de trobar un espai buit
                    if EmptyFound==True:
                        chours=chours+1
                        incr=True
                        EmptyFound=False
                    
                elif teacher[h]==0:
                    EmptyFound=True
                    
                h=h+1#index de les hores
                
            #Quan canviam de dia incrementam el cost del dia i resetejam els paràmetres:
            #Si les hores que fa un professor un dia es desvien en més de 1 de la mitjana ideal:
            hour_difference=abs(hoursTeacher-TeacherIdealHours[t])
            if hour_difference > 1:
                cTeacherDisph=cTeacherDisph+hour_difference
                cTeacherDispd=cTeacherDispd+1
            if incr>0:
                cdays=cdays+1
            hoursTeacher=0
            incr=False
            EmptyFound=False
        #Aquí calcul del cost
        
        t=t+1
        costTeacherDisp.append([cTeacherDisph,cTeacherDispd])
        cTeacherDisph=0
        cTeacherDispd=0
        costTeacherEmpty.append([chours,cdays])
        chours=0
        cdays=0
        #En lloc d'això aquí aniria la part de la funció de cost corresponent
    return costTeacherEmpty 
            

In [10]:
#Cost 1 i cost 2 calculats i funcionen correctament :)

def calc_C1_C2(individu,indx_individu):
    costUnable=0
    costMore1class=0
    #TeachersTimeTable=[[[] for i in range(TimeP)] for i in range(numTeachers)]
    TeachersTimeTable=[[0 for i in range(TimeP)] for i in range(numTeachers)]
    
    #llista dels profes assignats a una hora
    teacher_timeP=[]
    #for individu in population:
    for i_timePeriod in range(TimeP):
        teacher_timeP=[]
        for i_classe in range(classes):

            teachers=individu[i_classe][i_timePeriod]
            #print("profes",teachers)
            #Cream els horaris dels profes -> Aixo no ho empleam pero vaja
            createTeachersTimeP(teachers,i_classe,i_timePeriod)
            #Calculam el cost de si el profe no és a l'institut
            costU=CTeacherUnable(teachers,i_timePeriod,indx_individu)
            #if costU!=0:
                #print("--------------------")
                #print(i_timePeriod)
                #print("teachers",teachers)
                #print("costU",costU)
                #print("costUnable",costUnable)
            teacher_timeP.extend(teachers)
            costUnable=costUnable+costU
            #print("cost, i_timePeriod",costU,i_timePeriod)

        #Eliminam de la llista els buits(teacher 0) ja que teacher 0 no és cap teacher
        teacher_timeP=[elem for elem in teacher_timeP if elem != 0]
        #print(set(teacher_timeP))
        #print(teacher_timeP)
        cM1c_K=len(teacher_timeP)-len(set(teacher_timeP))
        costMore1class=costMore1class+HCW*(BASE**cM1c_K)
        #Calculate the cost for each teacher
        for t in teacher_timeP:
            k=teacher_timeP.count(t)-1
            teachersM1c_Cost=HCW*(BASE**k)
            costsTeachers[indx_individu][teacher-1]=costsTeachers[indx_individu][teacher-1]+HCW*(BASE**k)

    costUnable=costUnable*(HCW*(BASE**3))
    return(costUnable,costMore1class)


In [11]:
def IdealTeachingDayHours():
    TeacherIdealHours=[]
    for t in range (numTeachers):
        horesideals=TeachingHours[t]/(5-np.count_nonzero(TeacherNoDays[t]))
        TeacherIdealHours.append(horesideals)
    return TeacherIdealHours

Teacher’s empty spaces: For each teacher the following subcost is added:
TEPW ∗ HOURS ∗ BASE^DAYS, where
HOURS is the total number of empty time periods in the teacher’s timetable and DAYS is the number of days that empty time periods exist in the timetable of this specific teacher


In [12]:
#Cost Teacher empty spaces and dispersion
def CostTeacherE_i_D(idx_individu):
    costTeacherEmpty=0
    costTeacherLDisp=0
    cTeacherDisph=0
    cTeacherDispd=0
    hoursTeacher=0#num hores que fa un profe cada dia
    TotalcostTeacherDisp=0
    EmptyFound=False
    TeacherIdealHours=IdealTeachingDayHours()
    t=0#index del professor
    
    for teacher in TeachersTimeTable:
        h=0
        chours=0#cost hores
        cdays=0 #cost dies
        for day in range(5):
            incr=False
            for hour in range(7):
                
                if teacher[h]!=0:
                    hoursTeacher=hoursTeacher+1
                    #Si trobam una hora ocupada després de trobar un espai buit
                    if EmptyFound==True:
                        chours=chours+1
                        incr=True
                        EmptyFound=False
                    
                elif teacher[h]==0:
                    EmptyFound=True
                    
                h=h+1#index de les hores
                
            #Quan canviam de dia incrementam el cost del dia i resetejam els paràmetres:
            #Si les hores que fa un professor un dia es desvien en més de 1 de la mitjana ideal:
            hour_difference=abs(hoursTeacher-TeacherIdealHours[t])
            if hour_difference > 1:
                cTeacherDisph=cTeacherDisph+hour_difference
                cTeacherDispd=cTeacherDispd+1
            if incr==True:
                cdays=cdays+1
            hoursTeacher=0
            incr=False
            EmptyFound=False
            
        #Càlcul del cost de lesson's dispersion
        costTLD=IDWT*cTeacherDisph*(BASE**cTeacherDispd)
        costTeacherLDisp=costTeacherLDisp+costTLD
        costsTeachers[idx_individu][t-1]=costsTeachers[idx_individu][t-1]+costTLD
        
        #Aquí calcul del cost de Empty Scpaces
        costES=TEPW*chours*(BASE**cdays)
        costTeacherEmpty=costTeacherEmpty+costES
        costsTeachers[idx_individu][t-1]=costsTeachers[idx_individu][t-1]+costES
        
        t=t+1
        cTeacherDisph=0
        cTeacherDispd=0
        
    return costTeacherLDisp,costTeacherEmpty
            

In [13]:
#Class’s empty spaces cost calculat i funciona correctament :)
#HCW*BASE^BASE
def C_classEmptySpaces(individu):
    costClEmptySpaces=0
    emptyHour=False
    
    for classe in individu:
        timeP=0
        #cLessonDispersion=costClLessDispersion(classe)
        for teachers in classe:
            #Si canviam de dia resetejam les variables          
            if timeP%7==0:
                emptyHour=False
            #Si hi ha una hora buida activam empty hour  
            if teachers==[0,0]:
                emptyHour=True
            #Si hi ha una hora ocupada i prèviament hi ha hagut una hora buida el mateix dia sumam 1 al cost
            elif emptyHour==True:
                emptyHour=False
                costClEmptySpaces=costClEmptySpaces+1
            timeP=timeP+1
    cost=costClEmptySpaces*HCW*(BASE**BASE)
    return cost  

. Teacher lessons’ dispersion: For each teacher the following subcost is added: 
IDWT ∗ HOURS ∗ BASE^DAYS
, where HOURS is the total number of time periods that are different compared to the ideal dispersion teacher’s timetable and DAYS is the number of days in the teacher’s timetable that such a declination from the ideal case exists

In [14]:
def costFunction(pobl):    
    #costsTeachers=[[0 for i in range(numTeachers)] for i in range(population)] #declarar antes de cridar funcio
    costs=[0 for i in range(len(pobl))]
    idx_individu=0
    
    for individu in pobl:
        
      
        
        TeachersTimeTable=[[0 for i in range(TimeP)] for i in range(numTeachers)]

        [cTU,cM1cl]=calc_C1_C2(individu,idx_individu)

        cES=C_classEmptySpaces(individu)

        cTE,cTLD=CostTeacherE_i_D(idx_individu)

        TotalCost=cTU+cM1cl+cES+cTE+cTLD

        #print("CTEACH!",costsTeachers)
        
        costs[idx_individu] = TotalCost
        idx_individu=idx_individu+1
    
    return costs


In [15]:
#Recorrem les assignatures d'una classe
#[slots,professor1,professorSC,AssignaturaCT]

def decrementarHores(teacher,classe,Thours):
    #Recorrem les assignatures de la classe buscant les que fa el profe teacher
    #c= assignatures de la classe 1
    
    idxAssigntr=0

    c=ClasseAssignatura3[classe][:]

    for assignatura in c:

        if assignatura[1]==teacher and assignatura[0]>0:

            #Decrementam 
            ClasseAssignatura3[classe][idxAssigntr][0]=ClasseAssignatura3[classe][idxAssigntr][0]-1
            Thours[classe][teacher-1]=Thours[classe][teacher-1]-1
            teachers=[teacher,0]
          
            
            #si hi ha SC les decrementam de Thours
            if ClasseAssignatura3[classe][idxAssigntr][2]!=0:
                
                teacher2=ClasseAssignatura3[classe][idxAssigntr][2]
               
                Thours[classe][teacher2-1]=Thours[classe][teacher2-1]-1
                teachers=[teacher,teacher2]
               
                
            #Si hi ha coteaching llevam les hores de l'altra assignatura:
            if ClasseAssignatura3[classe][idxAssigntr][3]!=0:
                #Seleccionam el valor de l'index de l'assignatura amb la que hi ha coteaching
                AssigCT=ClasseAssignatura3[classe][idxAssigntr][3]
                
                #Decrementam en 1h les hores pendents d'assignar de l'assignatura de CT
                ClasseAssignatura3[classe][AssigCT-1][0]=ClasseAssignatura3[classe][AssigCT-1][0]-1
                teacherCT=ClasseAssignatura3[classe][AssigCT-1][1]
                Thours[classe][teacherCT-1]=Thours[classe][teacherCT-1]-1
                teachers=[teacher,teacherCT]
                
            
            break
                
        idxAssigntr=idxAssigntr+1
    #c=ClasseAssignatura3[classe][:]
    
    #print("ClasseAssignatura3 decrem",ClasseAssignatura3)
    return Thours,teachers
                
        

In [16]:
def mutation(poblacio, costsT):
    period_mutation_probability = 0.05
    bad_mutation_probability = 0.05
    poblacio_mutada = []
    classe_mutada = []

    # Period mutation
    #rand = random.random()
    if random.random() < period_mutation_probability:
        for chromo in poblacio:
            for classe in chromo:
                random_tp_1 = random.randrange(0, len(classe))
                random_tp_2 = random.randrange(0, len(classe))
                classe[random_tp_2], classe[random_tp_1] = classe[random_tp_1], classe[random_tp_2]
                classe_mutada.append(classe)
            poblacio_mutada.append(classe_mutada)
            classe_mutada = []
    
    # Bad mutation
    
    
     
    else:
        poblacio_mutada = poblacio
    
    return poblacio_mutada

elif random.random() < bad_mutation_probability:
        # Look for worst teacher timetable
        for individu in costsT:
            individuC=copy.deepcopy(individu)
            print("costTeacher",costsT)
            print("individu",individu)
            worst_teacher_1 = individuC.index(max(individuC))
            individuC[worst_teacher_1]=0
            worst_teacher_2 = individuC.index(max(individuC))
            print("worst teachers: ",worst_teacher_1,worst_teacher_2)
        # Swap teachers

## Creació de la primera població

In [17]:
poblacio=[0 for i in range(population)]
for i in range(population):
    Thours=np.zeros((classes, numTeachers),dtype=int)
    Calculate_TeachingHours()
    ClasseAssignatura3=copy.deepcopy(ClasseAssignatura2)
    for classe in range(classes):
        for hour in range(TimeP):
            c=ClasseAssignatura2[classe]
            ok=False
            #Chose a teacher at random 
            print("classe= ",classe)
            print(Thours[classe])
            
            # Miram si s'han assignat totes les hores d'una classe.
            if np.array_equal(ZerosT,Thours[classe])==False:
                while ok==False:#mirar que no sigui que no et quedin profes i se quedi aqui infinitament
                    teacher=randrange(1, numTeachers+1)
                    print("teacher",teacher)
                    for j in c:
                        #print("i",i) 
                        #print("c",c)
                        #print("i[1]",i[1])
                        #print(Thours[classe][teacher-1])
                        if(j[1]==teacher) and Thours[classe][teacher-1]!=0:
                            ok=True
                    #ok=True       
                print("thours",Thours[classe][teacher-1])
                print("selected teacher", teacher)
                print("decrementam ")
                Thours,teachers=decrementarHores(teacher,classe,Thours)
                print("classe",classe)
                print("hours",hour)                
                Chromo[classe][hour]=teachers
                print("TeacherHours, teachers :",Thours[classe], teachers)

                print(teachers)
                
            
                #Assignar slot buit
            print("buit")
    print("index",i)      
    poblacio[i]=copy.deepcopy(Chromo)
    #break

                            
                

                        
                #Now we have a teacher!!!
                #print(teacher)

                #Decrementam les hores agafant una hora en concret d'una assignatura
                
                #TeachingHours[teacher-1]=TeachingHours[teacher-1]-1
                #TeachingHours=a
      

        
#Si algun teacher només està de subclasse mai el decrementa directament !Alerta!  

[[6 2 4 6 3 3]
 [5 4 3 4 6 2]]
classe=  0
[6 2 4 6 3 3]
teacher 6
thours 3
selected teacher 6
decrementam 
classe 0
hours 0
TeacherHours, teachers : [6 2 4 5 3 2] [6, 4]
[6, 4]
buit
classe=  0
[6 2 4 5 3 2]
teacher 5
teacher 3
thours 4
selected teacher 3
decrementam 
classe 0
hours 1
TeacherHours, teachers : [6 2 3 5 3 2] [3, 0]
[3, 0]
buit
classe=  0
[6 2 3 5 3 2]
teacher 1
thours 6
selected teacher 1
decrementam 
classe 0
hours 2
TeacherHours, teachers : [5 2 3 5 3 2] [1, 0]
[1, 0]
buit
classe=  0
[5 2 3 5 3 2]
teacher 2
thours 2
selected teacher 2
decrementam 
classe 0
hours 3
TeacherHours, teachers : [5 1 3 5 3 2] [2, 0]
[2, 0]
buit
classe=  0
[5 1 3 5 3 2]
teacher 1
thours 5
selected teacher 1
decrementam 
classe 0
hours 4
TeacherHours, teachers : [4 1 3 5 3 2] [1, 0]
[1, 0]
buit
classe=  0
[4 1 3 5 3 2]
teacher 6
thours 2
selected teacher 6
decrementam 
classe 0
hours 5
TeacherHours, teachers : [4 1 3 4 3 1] [6, 4]
[6, 4]
buit
classe=  0
[4 1 3 4 3 1]
teacher 2
thours 1
selected 

buit
classe=  0
[0 0 0 0 0 0]
buit
classe=  0
[0 0 0 0 0 0]
buit
classe=  0
[0 0 0 0 0 0]
buit
classe=  0
[0 0 0 0 0 0]
buit
classe=  0
[0 0 0 0 0 0]
buit
classe=  0
[0 0 0 0 0 0]
buit
classe=  0
[0 0 0 0 0 0]
buit
classe=  0
[0 0 0 0 0 0]
buit
classe=  0
[0 0 0 0 0 0]
buit
classe=  1
[5 4 3 4 6 2]
teacher 1
thours 5
selected teacher 1
decrementam 
classe 1
hours 0
TeacherHours, teachers : [4 4 3 4 6 2] [1, 0]
[1, 0]
buit
classe=  1
[4 4 3 4 6 2]
teacher 4
thours 4
selected teacher 4
decrementam 
classe 1
hours 1
TeacherHours, teachers : [4 3 3 3 6 2] [4, 2]
[4, 2]
buit
classe=  1
[4 3 3 3 6 2]
teacher 6
thours 2
selected teacher 6
decrementam 
classe 1
hours 2
TeacherHours, teachers : [4 3 3 3 6 1] [6, 0]
[6, 0]
buit
classe=  1
[4 3 3 3 6 1]
teacher 3
thours 3
selected teacher 3
decrementam 
classe 1
hours 3
TeacherHours, teachers : [4 3 2 3 6 1] [3, 0]
[3, 0]
buit
classe=  1
[4 3 2 3 6 1]
teacher 1
thours 4
selected teacher 1
decrementam 
classe 1
hours 4
TeacherHours, teachers : [3 

[4, 2]
buit
classe=  1
[2 1 2 1 6 0]
teacher 4
thours 1
selected teacher 4
decrementam 
classe 1
hours 9
TeacherHours, teachers : [2 0 2 0 6 0] [4, 2]
[4, 2]
buit
classe=  1
[2 0 2 0 6 0]
teacher 4
teacher 3
thours 2
selected teacher 3
decrementam 
classe 1
hours 10
TeacherHours, teachers : [2 0 1 0 6 0] [3, 0]
[3, 0]
buit
classe=  1
[2 0 1 0 6 0]
teacher 4
teacher 4
teacher 6
teacher 4
teacher 2
teacher 1
thours 2
selected teacher 1
decrementam 
classe 1
hours 11
TeacherHours, teachers : [1 0 1 0 6 0] [1, 0]
[1, 0]
buit
classe=  1
[1 0 1 0 6 0]
teacher 6
teacher 6
teacher 5
thours 6
selected teacher 5
decrementam 
classe 1
hours 12
TeacherHours, teachers : [1 0 1 0 5 0] [5, 0]
[5, 0]
buit
classe=  1
[1 0 1 0 5 0]
teacher 2
teacher 3
thours 1
selected teacher 3
decrementam 
classe 1
hours 13
TeacherHours, teachers : [1 0 0 0 5 0] [3, 0]
[3, 0]
buit
classe=  1
[1 0 0 0 5 0]
teacher 5
thours 5
selected teacher 5
decrementam 
classe 1
hours 14
TeacherHours, teachers : [1 0 0 0 4 0] [5, 0]

[1 0 0 0 3 0]
teacher 1
thours 1
selected teacher 1
decrementam 
classe 1
hours 16
TeacherHours, teachers : [0 0 0 0 3 0] [1, 0]
[1, 0]
buit
classe=  1
[0 0 0 0 3 0]
teacher 5
thours 3
selected teacher 5
decrementam 
classe 1
hours 17
TeacherHours, teachers : [0 0 0 0 2 0] [5, 0]
[5, 0]
buit
classe=  1
[0 0 0 0 2 0]
teacher 4
teacher 1
teacher 6
teacher 5
thours 2
selected teacher 5
decrementam 
classe 1
hours 18
TeacherHours, teachers : [0 0 0 0 1 0] [5, 0]
[5, 0]
buit
classe=  1
[0 0 0 0 1 0]
teacher 3
teacher 4
teacher 5
thours 1
selected teacher 5
decrementam 
classe 1
hours 19
TeacherHours, teachers : [0 0 0 0 0 0] [5, 0]
[5, 0]
buit
classe=  1
[0 0 0 0 0 0]
buit
classe=  1
[0 0 0 0 0 0]
buit
classe=  1
[0 0 0 0 0 0]
buit
classe=  1
[0 0 0 0 0 0]
buit
classe=  1
[0 0 0 0 0 0]
buit
classe=  1
[0 0 0 0 0 0]
buit
classe=  1
[0 0 0 0 0 0]
buit
classe=  1
[0 0 0 0 0 0]
buit
classe=  1
[0 0 0 0 0 0]
buit
classe=  1
[0 0 0 0 0 0]
buit
classe=  1
[0 0 0 0 0 0]
buit
classe=  1
[0 0 0 0 0 0

classe=  1
[3 2 3 2 5 0]
teacher 6
teacher 5
thours 5
selected teacher 5
decrementam 
classe 1
hours 7
TeacherHours, teachers : [3 2 3 2 4 0] [5, 0]
[5, 0]
buit
classe=  1
[3 2 3 2 4 0]
teacher 6
teacher 6
teacher 3
thours 3
selected teacher 3
decrementam 
classe 1
hours 8
TeacherHours, teachers : [3 2 2 2 4 0] [3, 0]
[3, 0]
buit
classe=  1
[3 2 2 2 4 0]
teacher 5
thours 4
selected teacher 5
decrementam 
classe 1
hours 9
TeacherHours, teachers : [3 2 2 2 3 0] [5, 0]
[5, 0]
buit
classe=  1
[3 2 2 2 3 0]
teacher 1
thours 3
selected teacher 1
decrementam 
classe 1
hours 10
TeacherHours, teachers : [2 2 2 2 3 0] [1, 0]
[1, 0]
buit
classe=  1
[2 2 2 2 3 0]
teacher 6
teacher 2
thours 2
selected teacher 2
decrementam 
classe 1
hours 11
TeacherHours, teachers : [2 1 2 1 3 0] [2, 4]
[2, 4]
buit
classe=  1
[2 1 2 1 3 0]
teacher 1
thours 2
selected teacher 1
decrementam 
classe 1
hours 12
TeacherHours, teachers : [1 1 2 1 3 0] [1, 0]
[1, 0]
buit
classe=  1
[1 1 2 1 3 0]
teacher 1
thours 1
selecte

[0 0 0 0 0 0]
buit
classe=  0
[0 0 0 0 0 0]
buit
classe=  1
[5 4 3 4 6 2]
teacher 4
thours 4
selected teacher 4
decrementam 
classe 1
hours 0
TeacherHours, teachers : [5 3 3 3 6 2] [4, 2]
[4, 2]
buit
classe=  1
[5 3 3 3 6 2]
teacher 5
thours 6
selected teacher 5
decrementam 
classe 1
hours 1
TeacherHours, teachers : [5 3 3 3 5 2] [5, 0]
[5, 0]
buit
classe=  1
[5 3 3 3 5 2]
teacher 2
thours 3
selected teacher 2
decrementam 
classe 1
hours 2
TeacherHours, teachers : [5 2 3 2 5 2] [2, 4]
[2, 4]
buit
classe=  1
[5 2 3 2 5 2]
teacher 1
thours 5
selected teacher 1
decrementam 
classe 1
hours 3
TeacherHours, teachers : [4 2 3 2 5 2] [1, 0]
[1, 0]
buit
classe=  1
[4 2 3 2 5 2]
teacher 2
thours 2
selected teacher 2
decrementam 
classe 1
hours 4
TeacherHours, teachers : [4 1 3 1 5 2] [2, 4]
[2, 4]
buit
classe=  1
[4 1 3 1 5 2]
teacher 2
thours 1
selected teacher 2
decrementam 
classe 1
hours 5
TeacherHours, teachers : [4 0 3 0 5 2] [2, 4]
[2, 4]
buit
classe=  1
[4 0 3 0 5 2]
teacher 5
thours 5
s

TeacherHours, teachers : [0 0 0 0 0 0] [3, 0]
[3, 0]
buit
classe=  0
[0 0 0 0 0 0]
buit
classe=  0
[0 0 0 0 0 0]
buit
classe=  0
[0 0 0 0 0 0]
buit
classe=  0
[0 0 0 0 0 0]
buit
classe=  0
[0 0 0 0 0 0]
buit
classe=  0
[0 0 0 0 0 0]
buit
classe=  0
[0 0 0 0 0 0]
buit
classe=  0
[0 0 0 0 0 0]
buit
classe=  0
[0 0 0 0 0 0]
buit
classe=  0
[0 0 0 0 0 0]
buit
classe=  0
[0 0 0 0 0 0]
buit
classe=  0
[0 0 0 0 0 0]
buit
classe=  0
[0 0 0 0 0 0]
buit
classe=  0
[0 0 0 0 0 0]
buit
classe=  0
[0 0 0 0 0 0]
buit
classe=  0
[0 0 0 0 0 0]
buit
classe=  0
[0 0 0 0 0 0]
buit
classe=  1
[5 4 3 4 6 2]
teacher 2
thours 4
selected teacher 2
decrementam 
classe 1
hours 0
TeacherHours, teachers : [5 3 3 3 6 2] [2, 4]
[2, 4]
buit
classe=  1
[5 3 3 3 6 2]
teacher 6
thours 2
selected teacher 6
decrementam 
classe 1
hours 1
TeacherHours, teachers : [5 3 3 3 6 1] [6, 0]
[6, 0]
buit
classe=  1
[5 3 3 3 6 1]
teacher 3
thours 3
selected teacher 3
decrementam 
classe 1
hours 2
TeacherHours, teachers : [5 3 2 3 6 1

teacher 1
thours 5
selected teacher 1
decrementam 
classe 0
hours 8
TeacherHours, teachers : [4 0 3 2 0 2] [1, 0]
[1, 0]
buit
classe=  0
[4 0 3 2 0 2]
teacher 3
thours 3
selected teacher 3
decrementam 
classe 0
hours 9
TeacherHours, teachers : [4 0 2 2 0 2] [3, 0]
[3, 0]
buit
classe=  0
[4 0 2 2 0 2]
teacher 1
thours 4
selected teacher 1
decrementam 
classe 0
hours 10
TeacherHours, teachers : [3 0 2 2 0 2] [1, 0]
[1, 0]
buit
classe=  0
[3 0 2 2 0 2]
teacher 6
thours 2
selected teacher 6
decrementam 
classe 0
hours 11
TeacherHours, teachers : [3 0 2 1 0 1] [6, 4]
[6, 4]
buit
classe=  0
[3 0 2 1 0 1]
teacher 5
teacher 1
thours 3
selected teacher 1
decrementam 
classe 0
hours 12
TeacherHours, teachers : [2 0 2 1 0 1] [1, 0]
[1, 0]
buit
classe=  0
[2 0 2 1 0 1]
teacher 3
thours 2
selected teacher 3
decrementam 
classe 0
hours 13
TeacherHours, teachers : [2 0 1 1 0 1] [3, 0]
[3, 0]
buit
classe=  0
[2 0 1 1 0 1]
teacher 6
thours 1
selected teacher 6
decrementam 
classe 0
hours 14
TeacherHour

classe 0
hours 16
TeacherHours, teachers : [0 1 0 0 0 0] [1, 0]
[1, 0]
buit
classe=  0
[0 1 0 0 0 0]
teacher 4
teacher 5
teacher 4
teacher 4
teacher 1
teacher 5
teacher 5
teacher 5
teacher 4
teacher 2
thours 1
selected teacher 2
decrementam 
classe 0
hours 17
TeacherHours, teachers : [0 0 0 0 0 0] [2, 0]
[2, 0]
buit
classe=  0
[0 0 0 0 0 0]
buit
classe=  0
[0 0 0 0 0 0]
buit
classe=  0
[0 0 0 0 0 0]
buit
classe=  0
[0 0 0 0 0 0]
buit
classe=  0
[0 0 0 0 0 0]
buit
classe=  0
[0 0 0 0 0 0]
buit
classe=  0
[0 0 0 0 0 0]
buit
classe=  0
[0 0 0 0 0 0]
buit
classe=  0
[0 0 0 0 0 0]
buit
classe=  0
[0 0 0 0 0 0]
buit
classe=  0
[0 0 0 0 0 0]
buit
classe=  0
[0 0 0 0 0 0]
buit
classe=  0
[0 0 0 0 0 0]
buit
classe=  0
[0 0 0 0 0 0]
buit
classe=  0
[0 0 0 0 0 0]
buit
classe=  0
[0 0 0 0 0 0]
buit
classe=  0
[0 0 0 0 0 0]
buit
classe=  1
[5 4 3 4 6 2]
teacher 6
thours 2
selected teacher 6
decrementam 
classe 1
hours 0
TeacherHours, teachers : [5 4 3 4 6 1] [6, 0]
[6, 0]
buit
classe=  1
[5 4 3 4 6

teacher 1
thours 4
selected teacher 1
decrementam 
classe 1
hours 9
TeacherHours, teachers : [3 0 3 0 4 0] [1, 0]
[1, 0]
buit
classe=  1
[3 0 3 0 4 0]
teacher 1
thours 3
selected teacher 1
decrementam 
classe 1
hours 10
TeacherHours, teachers : [2 0 3 0 4 0] [1, 0]
[1, 0]
buit
classe=  1
[2 0 3 0 4 0]
teacher 4
teacher 2
teacher 2
teacher 6
teacher 5
thours 4
selected teacher 5
decrementam 
classe 1
hours 11
TeacherHours, teachers : [2 0 3 0 3 0] [5, 0]
[5, 0]
buit
classe=  1
[2 0 3 0 3 0]
teacher 4
teacher 5
thours 3
selected teacher 5
decrementam 
classe 1
hours 12
TeacherHours, teachers : [2 0 3 0 2 0] [5, 0]
[5, 0]
buit
classe=  1
[2 0 3 0 2 0]
teacher 6
teacher 5
thours 2
selected teacher 5
decrementam 
classe 1
hours 13
TeacherHours, teachers : [2 0 3 0 1 0] [5, 0]
[5, 0]
buit
classe=  1
[2 0 3 0 1 0]
teacher 4
teacher 1
thours 2
selected teacher 1
decrementam 
classe 1
hours 14
TeacherHours, teachers : [1 0 3 0 1 0] [1, 0]
[1, 0]
buit
classe=  1
[1 0 3 0 1 0]
teacher 1
thours 1


[5, 0]
buit
classe=  1
[3 0 0 0 2 0]
teacher 3
teacher 1
thours 3
selected teacher 1
decrementam 
classe 1
hours 15
TeacherHours, teachers : [2 0 0 0 2 0] [1, 0]
[1, 0]
buit
classe=  1
[2 0 0 0 2 0]
teacher 6
teacher 4
teacher 5
thours 2
selected teacher 5
decrementam 
classe 1
hours 16
TeacherHours, teachers : [2 0 0 0 1 0] [5, 0]
[5, 0]
buit
classe=  1
[2 0 0 0 1 0]
teacher 3
teacher 2
teacher 2
teacher 6
teacher 3
teacher 2
teacher 4
teacher 1
thours 2
selected teacher 1
decrementam 
classe 1
hours 17
TeacherHours, teachers : [1 0 0 0 1 0] [1, 0]
[1, 0]
buit
classe=  1
[1 0 0 0 1 0]
teacher 6
teacher 2
teacher 3
teacher 4
teacher 3
teacher 5
thours 1
selected teacher 5
decrementam 
classe 1
hours 18
TeacherHours, teachers : [1 0 0 0 0 0] [5, 0]
[5, 0]
buit
classe=  1
[1 0 0 0 0 0]
teacher 5
teacher 6
teacher 2
teacher 6
teacher 3
teacher 1
thours 1
selected teacher 1
decrementam 
classe 1
hours 19
TeacherHours, teachers : [0 0 0 0 0 0] [1, 0]
[1, 0]
buit
classe=  1
[0 0 0 0 0 0]
bui

teacher 5
teacher 2
teacher 1
thours 4
selected teacher 1
decrementam 
classe 0
hours 7
TeacherHours, teachers : [3 0 2 5 3 2] [1, 0]
[1, 0]
buit
classe=  0
[3 0 2 5 3 2]
teacher 3
thours 2
selected teacher 3
decrementam 
classe 0
hours 8
TeacherHours, teachers : [3 0 1 5 3 2] [3, 0]
[3, 0]
buit
classe=  0
[3 0 1 5 3 2]
teacher 6
thours 2
selected teacher 6
decrementam 
classe 0
hours 9
TeacherHours, teachers : [3 0 1 4 3 1] [6, 4]
[6, 4]
buit
classe=  0
[3 0 1 4 3 1]
teacher 2
teacher 6
thours 1
selected teacher 6
decrementam 
classe 0
hours 10
TeacherHours, teachers : [3 0 1 3 3 0] [6, 4]
[6, 4]
buit
classe=  0
[3 0 1 3 3 0]
teacher 3
thours 1
selected teacher 3
decrementam 
classe 0
hours 11
TeacherHours, teachers : [3 0 0 3 3 0] [3, 0]
[3, 0]
buit
classe=  0
[3 0 0 3 3 0]
teacher 4
thours 3
selected teacher 4
decrementam 
classe 0
hours 12
TeacherHours, teachers : [3 0 0 2 2 0] [4, 5]
[4, 5]
buit
classe=  0
[3 0 0 2 2 0]
teacher 5
teacher 5
teacher 1
thours 3
selected teacher 1
dec

TeacherHours, teachers : [4 0 1 0 6 2] [1, 0]
[1, 0]
buit
classe=  1
[4 0 1 0 6 2]
teacher 6
thours 2
selected teacher 6
decrementam 
classe 1
hours 7
TeacherHours, teachers : [4 0 1 0 6 1] [6, 0]
[6, 0]
buit
classe=  1
[4 0 1 0 6 1]
teacher 5
thours 6
selected teacher 5
decrementam 
classe 1
hours 8
TeacherHours, teachers : [4 0 1 0 5 1] [5, 0]
[5, 0]
buit
classe=  1
[4 0 1 0 5 1]
teacher 4
teacher 6
thours 1
selected teacher 6
decrementam 
classe 1
hours 9
TeacherHours, teachers : [4 0 1 0 5 0] [6, 0]
[6, 0]
buit
classe=  1
[4 0 1 0 5 0]
teacher 1
thours 4
selected teacher 1
decrementam 
classe 1
hours 10
TeacherHours, teachers : [3 0 1 0 5 0] [1, 0]
[1, 0]
buit
classe=  1
[3 0 1 0 5 0]
teacher 5
thours 5
selected teacher 5
decrementam 
classe 1
hours 11
TeacherHours, teachers : [3 0 1 0 4 0] [5, 0]
[5, 0]
buit
classe=  1
[3 0 1 0 4 0]
teacher 1
thours 3
selected teacher 1
decrementam 
classe 1
hours 12
TeacherHours, teachers : [2 0 1 0 4 0] [1, 0]
[1, 0]
buit
classe=  1
[2 0 1 0 4 0

teacher 2
teacher 4
teacher 2
teacher 1
teacher 5
thours 1
selected teacher 5
decrementam 
classe 1
hours 19
TeacherHours, teachers : [0 0 0 0 0 0] [5, 0]
[5, 0]
buit
classe=  1
[0 0 0 0 0 0]
buit
classe=  1
[0 0 0 0 0 0]
buit
classe=  1
[0 0 0 0 0 0]
buit
classe=  1
[0 0 0 0 0 0]
buit
classe=  1
[0 0 0 0 0 0]
buit
classe=  1
[0 0 0 0 0 0]
buit
classe=  1
[0 0 0 0 0 0]
buit
classe=  1
[0 0 0 0 0 0]
buit
classe=  1
[0 0 0 0 0 0]
buit
classe=  1
[0 0 0 0 0 0]
buit
classe=  1
[0 0 0 0 0 0]
buit
classe=  1
[0 0 0 0 0 0]
buit
classe=  1
[0 0 0 0 0 0]
buit
classe=  1
[0 0 0 0 0 0]
buit
classe=  1
[0 0 0 0 0 0]
buit
index 18
[[6 2 4 6 3 3]
 [5 4 3 4 6 2]]
classe=  0
[6 2 4 6 3 3]
teacher 1
thours 6
selected teacher 1
decrementam 
classe 0
hours 0
TeacherHours, teachers : [5 2 4 6 3 3] [1, 0]
[1, 0]
buit
classe=  0
[5 2 4 6 3 3]
teacher 3
thours 4
selected teacher 3
decrementam 
classe 0
hours 1
TeacherHours, teachers : [5 2 3 6 3 3] [3, 0]
[3, 0]
buit
classe=  0
[5 2 3 6 3 3]
teacher 5
teache

## Loop iteratiu

In [18]:
N = population
n_min = 0.2
n_max = 2 - n_min
    
probability = []

# Calcul de probabilitat de reproduccio
for i in range(N):
    probability.append((1/N)*(n_min+(n_max - n_min)*(i)/(N-1)))
    #probability.append(np.divide(1,N)*np.divide(n_min+(n_max - n_min)*(i-1),(N-1)))
    
# Vector de probabilitats de reproduccio
mapped = []
mapped.append(0)

for i in range(len(probability)-1):
    mapped.append(mapped[i] + probability[i])

mapped.append(1)

In [19]:
for i in range(100):
    costsTeachers=[[0 for i in range(numTeachers)] for i in range(population)]
    calculatedCosts=costFunction(poblacio)
        
    costsTeachers=[[0 for i in range(numTeachers)] for i in range(population)]
    calculatedCosts=costFunction(poblacio)
    print("COST 2",calculatedCosts)


    costs={}
    for i in range(population):
        costs[i]=calculatedCosts[i]
    print(costs)

    sorted_costs = sorted(costs.items(), key=operator.itemgetter(1))
    sorted_costs.reverse()
    print(sorted_costs)
    nova_poblacio = []

    # Elitism: aseguram que el millor cromosoma pasa a la següent generacio
    nova_poblacio.append(poblacio[sorted_costs[-1][0]])
    print("MINIM",sorted_costs[-1])
    #print(poblacio[sorted_costs[-1][0]])
    #print(nova_poblacio[0])


    #costsTeachers=[[0 for i in range(numTeachers)] for i in range(population)]
    #print(costFunction(nova_poblacio))
    
    # Selecció dels individus a reproduir
    for i in range(N-1):
        rand = random.random()
        for i in range(len(probability)):
            if (rand > mapped[i]) & (rand <= mapped[i+1]):
                cromo_index = i
                break
        # Aqui s'ha triat el cromosoma que s'ha de reproduir. Ara l'hem de reproduir
        
        nova_poblacio.append(poblacio[sorted_costs[cromo_index][0]])
    #print("poblacio",poblacio)
    #print("nova poblacio",nova_poblacio)
    
    #poblacio_mutada = mutation(nova_poblacio, costsTeachers)
    #costsTeachers=[[0 for i in range(numTeachers)] for i in range(population)]
    #print("costsNP",costFunction(poblacio))
    #costsTeachers=[[0 for i in range(numTeachers)] for i in range(population)]
    #print("costsNP_2",costFunction(poblacio))
    #poblacio = copy.deepcopy(poblacio_mutada)
    poblacio=copy.deepcopy(nova_poblacio)

COST 2 [2617.671875, 2636.421875, 2747.671875, 2853.921875, 2588.921875, 2742.671875, 2676.421875, 2578.921875, 2742.671875, 2747.671875, 2550.171875, 2670.171875, 2685.171875, 2573.921875, 2637.671875, 2612.671875, 2708.921875, 2516.421875, 2737.671875, 2713.921875]
{0: 2617.671875, 1: 2636.421875, 2: 2747.671875, 3: 2853.921875, 4: 2588.921875, 5: 2742.671875, 6: 2676.421875, 7: 2578.921875, 8: 2742.671875, 9: 2747.671875, 10: 2550.171875, 11: 2670.171875, 12: 2685.171875, 13: 2573.921875, 14: 2637.671875, 15: 2612.671875, 16: 2708.921875, 17: 2516.421875, 18: 2737.671875, 19: 2713.921875}
[(3, 2853.921875), (9, 2747.671875), (2, 2747.671875), (8, 2742.671875), (5, 2742.671875), (18, 2737.671875), (19, 2713.921875), (16, 2708.921875), (12, 2685.171875), (6, 2676.421875), (11, 2670.171875), (14, 2637.671875), (1, 2636.421875), (0, 2617.671875), (15, 2612.671875), (4, 2588.921875), (7, 2578.921875), (13, 2573.921875), (10, 2550.171875), (17, 2516.421875)]
MINIM (17, 2516.421875)
COST 2

MINIM (0, 2516.421875)
COST 2 [2516.421875, 2516.421875, 2516.421875, 2516.421875, 2516.421875, 2516.421875, 2516.421875, 2516.421875, 2516.421875, 2516.421875, 2516.421875, 2516.421875, 2516.421875, 2516.421875, 2516.421875, 2516.421875, 2516.421875, 2516.421875, 2516.421875, 2516.421875]
{0: 2516.421875, 1: 2516.421875, 2: 2516.421875, 3: 2516.421875, 4: 2516.421875, 5: 2516.421875, 6: 2516.421875, 7: 2516.421875, 8: 2516.421875, 9: 2516.421875, 10: 2516.421875, 11: 2516.421875, 12: 2516.421875, 13: 2516.421875, 14: 2516.421875, 15: 2516.421875, 16: 2516.421875, 17: 2516.421875, 18: 2516.421875, 19: 2516.421875}
[(19, 2516.421875), (18, 2516.421875), (17, 2516.421875), (16, 2516.421875), (15, 2516.421875), (14, 2516.421875), (13, 2516.421875), (12, 2516.421875), (11, 2516.421875), (10, 2516.421875), (9, 2516.421875), (8, 2516.421875), (7, 2516.421875), (6, 2516.421875), (5, 2516.421875), (4, 2516.421875), (3, 2516.421875), (2, 2516.421875), (1, 2516.421875), (0, 2516.421875)]
MINIM (

COST 2 [2516.421875, 2516.421875, 2516.421875, 2516.421875, 2516.421875, 2516.421875, 2516.421875, 2516.421875, 2516.421875, 2516.421875, 2516.421875, 2516.421875, 2516.421875, 2516.421875, 2516.421875, 2516.421875, 2516.421875, 2516.421875, 2516.421875, 2516.421875]
{0: 2516.421875, 1: 2516.421875, 2: 2516.421875, 3: 2516.421875, 4: 2516.421875, 5: 2516.421875, 6: 2516.421875, 7: 2516.421875, 8: 2516.421875, 9: 2516.421875, 10: 2516.421875, 11: 2516.421875, 12: 2516.421875, 13: 2516.421875, 14: 2516.421875, 15: 2516.421875, 16: 2516.421875, 17: 2516.421875, 18: 2516.421875, 19: 2516.421875}
[(19, 2516.421875), (18, 2516.421875), (17, 2516.421875), (16, 2516.421875), (15, 2516.421875), (14, 2516.421875), (13, 2516.421875), (12, 2516.421875), (11, 2516.421875), (10, 2516.421875), (9, 2516.421875), (8, 2516.421875), (7, 2516.421875), (6, 2516.421875), (5, 2516.421875), (4, 2516.421875), (3, 2516.421875), (2, 2516.421875), (1, 2516.421875), (0, 2516.421875)]
MINIM (0, 2516.421875)
COST 2 

COST 2 [2516.421875, 2516.421875, 2516.421875, 2516.421875, 2516.421875, 2516.421875, 2516.421875, 2516.421875, 2516.421875, 2516.421875, 2516.421875, 2516.421875, 2516.421875, 2516.421875, 2516.421875, 2516.421875, 2516.421875, 2516.421875, 2516.421875, 2516.421875]
{0: 2516.421875, 1: 2516.421875, 2: 2516.421875, 3: 2516.421875, 4: 2516.421875, 5: 2516.421875, 6: 2516.421875, 7: 2516.421875, 8: 2516.421875, 9: 2516.421875, 10: 2516.421875, 11: 2516.421875, 12: 2516.421875, 13: 2516.421875, 14: 2516.421875, 15: 2516.421875, 16: 2516.421875, 17: 2516.421875, 18: 2516.421875, 19: 2516.421875}
[(19, 2516.421875), (18, 2516.421875), (17, 2516.421875), (16, 2516.421875), (15, 2516.421875), (14, 2516.421875), (13, 2516.421875), (12, 2516.421875), (11, 2516.421875), (10, 2516.421875), (9, 2516.421875), (8, 2516.421875), (7, 2516.421875), (6, 2516.421875), (5, 2516.421875), (4, 2516.421875), (3, 2516.421875), (2, 2516.421875), (1, 2516.421875), (0, 2516.421875)]
MINIM (0, 2516.421875)
COST 2 

COST 2 [2516.421875, 2516.421875, 2516.421875, 2516.421875, 2516.421875, 2516.421875, 2516.421875, 2516.421875, 2516.421875, 2516.421875, 2516.421875, 2516.421875, 2516.421875, 2516.421875, 2516.421875, 2516.421875, 2516.421875, 2516.421875, 2516.421875, 2516.421875]
{0: 2516.421875, 1: 2516.421875, 2: 2516.421875, 3: 2516.421875, 4: 2516.421875, 5: 2516.421875, 6: 2516.421875, 7: 2516.421875, 8: 2516.421875, 9: 2516.421875, 10: 2516.421875, 11: 2516.421875, 12: 2516.421875, 13: 2516.421875, 14: 2516.421875, 15: 2516.421875, 16: 2516.421875, 17: 2516.421875, 18: 2516.421875, 19: 2516.421875}
[(19, 2516.421875), (18, 2516.421875), (17, 2516.421875), (16, 2516.421875), (15, 2516.421875), (14, 2516.421875), (13, 2516.421875), (12, 2516.421875), (11, 2516.421875), (10, 2516.421875), (9, 2516.421875), (8, 2516.421875), (7, 2516.421875), (6, 2516.421875), (5, 2516.421875), (4, 2516.421875), (3, 2516.421875), (2, 2516.421875), (1, 2516.421875), (0, 2516.421875)]
MINIM (0, 2516.421875)
COST 2 

COST 2 [2516.421875, 2516.421875, 2516.421875, 2516.421875, 2516.421875, 2516.421875, 2516.421875, 2516.421875, 2516.421875, 2516.421875, 2516.421875, 2516.421875, 2516.421875, 2516.421875, 2516.421875, 2516.421875, 2516.421875, 2516.421875, 2516.421875, 2516.421875]
{0: 2516.421875, 1: 2516.421875, 2: 2516.421875, 3: 2516.421875, 4: 2516.421875, 5: 2516.421875, 6: 2516.421875, 7: 2516.421875, 8: 2516.421875, 9: 2516.421875, 10: 2516.421875, 11: 2516.421875, 12: 2516.421875, 13: 2516.421875, 14: 2516.421875, 15: 2516.421875, 16: 2516.421875, 17: 2516.421875, 18: 2516.421875, 19: 2516.421875}
[(19, 2516.421875), (18, 2516.421875), (17, 2516.421875), (16, 2516.421875), (15, 2516.421875), (14, 2516.421875), (13, 2516.421875), (12, 2516.421875), (11, 2516.421875), (10, 2516.421875), (9, 2516.421875), (8, 2516.421875), (7, 2516.421875), (6, 2516.421875), (5, 2516.421875), (4, 2516.421875), (3, 2516.421875), (2, 2516.421875), (1, 2516.421875), (0, 2516.421875)]
MINIM (0, 2516.421875)
COST 2 

COST 2 [2516.421875, 2516.421875, 2516.421875, 2516.421875, 2516.421875, 2516.421875, 2516.421875, 2516.421875, 2516.421875, 2516.421875, 2516.421875, 2516.421875, 2516.421875, 2516.421875, 2516.421875, 2516.421875, 2516.421875, 2516.421875, 2516.421875, 2516.421875]
{0: 2516.421875, 1: 2516.421875, 2: 2516.421875, 3: 2516.421875, 4: 2516.421875, 5: 2516.421875, 6: 2516.421875, 7: 2516.421875, 8: 2516.421875, 9: 2516.421875, 10: 2516.421875, 11: 2516.421875, 12: 2516.421875, 13: 2516.421875, 14: 2516.421875, 15: 2516.421875, 16: 2516.421875, 17: 2516.421875, 18: 2516.421875, 19: 2516.421875}
[(19, 2516.421875), (18, 2516.421875), (17, 2516.421875), (16, 2516.421875), (15, 2516.421875), (14, 2516.421875), (13, 2516.421875), (12, 2516.421875), (11, 2516.421875), (10, 2516.421875), (9, 2516.421875), (8, 2516.421875), (7, 2516.421875), (6, 2516.421875), (5, 2516.421875), (4, 2516.421875), (3, 2516.421875), (2, 2516.421875), (1, 2516.421875), (0, 2516.421875)]
MINIM (0, 2516.421875)
COST 2 

COST 2 [2516.421875, 2516.421875, 2516.421875, 2516.421875, 2516.421875, 2516.421875, 2516.421875, 2516.421875, 2516.421875, 2516.421875, 2516.421875, 2516.421875, 2516.421875, 2516.421875, 2516.421875, 2516.421875, 2516.421875, 2516.421875, 2516.421875, 2516.421875]
{0: 2516.421875, 1: 2516.421875, 2: 2516.421875, 3: 2516.421875, 4: 2516.421875, 5: 2516.421875, 6: 2516.421875, 7: 2516.421875, 8: 2516.421875, 9: 2516.421875, 10: 2516.421875, 11: 2516.421875, 12: 2516.421875, 13: 2516.421875, 14: 2516.421875, 15: 2516.421875, 16: 2516.421875, 17: 2516.421875, 18: 2516.421875, 19: 2516.421875}
[(19, 2516.421875), (18, 2516.421875), (17, 2516.421875), (16, 2516.421875), (15, 2516.421875), (14, 2516.421875), (13, 2516.421875), (12, 2516.421875), (11, 2516.421875), (10, 2516.421875), (9, 2516.421875), (8, 2516.421875), (7, 2516.421875), (6, 2516.421875), (5, 2516.421875), (4, 2516.421875), (3, 2516.421875), (2, 2516.421875), (1, 2516.421875), (0, 2516.421875)]
MINIM (0, 2516.421875)
COST 2 

COST 2 [2516.421875, 2516.421875, 2516.421875, 2516.421875, 2516.421875, 2516.421875, 2516.421875, 2516.421875, 2516.421875, 2516.421875, 2516.421875, 2516.421875, 2516.421875, 2516.421875, 2516.421875, 2516.421875, 2516.421875, 2516.421875, 2516.421875, 2516.421875]
{0: 2516.421875, 1: 2516.421875, 2: 2516.421875, 3: 2516.421875, 4: 2516.421875, 5: 2516.421875, 6: 2516.421875, 7: 2516.421875, 8: 2516.421875, 9: 2516.421875, 10: 2516.421875, 11: 2516.421875, 12: 2516.421875, 13: 2516.421875, 14: 2516.421875, 15: 2516.421875, 16: 2516.421875, 17: 2516.421875, 18: 2516.421875, 19: 2516.421875}
[(19, 2516.421875), (18, 2516.421875), (17, 2516.421875), (16, 2516.421875), (15, 2516.421875), (14, 2516.421875), (13, 2516.421875), (12, 2516.421875), (11, 2516.421875), (10, 2516.421875), (9, 2516.421875), (8, 2516.421875), (7, 2516.421875), (6, 2516.421875), (5, 2516.421875), (4, 2516.421875), (3, 2516.421875), (2, 2516.421875), (1, 2516.421875), (0, 2516.421875)]
MINIM (0, 2516.421875)
COST 2 

*Teacher unavailability: For each teacher and for each time period this teacher is assigned to a class, while he/she is unavailable at school the corresponding day, the following cost is added: HCW ∗ BASE3.

*Teacher assigned in more than one class: For each teacher and for each time period, if this teacher is assigned to more than one class, for example, to k classes, the following cost is added: HCW ∗ BASEk


Teacher lessons’ dispersion: For each teacher the following subcost is added: IDWT ∗ HOURS ∗ BASEDAYS, where
HOURS is the total number of time periods that are different compared to the ideal dispersion teacher’s timetable
and DAYS is the number of days in the teacher’s timetable that such a declination from the ideal case exists.