## Inicialitzacions

In [1]:
import pandas as pd
import numpy as np
from random import randrange
import copy
import random
import operator

In [2]:
#Inicialitzacions
classes=2
TimeP=35
Chromo=[]
#Chromo=np.zeros((classes, TimeP),dtype=int)
#Chromo=Chromo.tolist()
Chromo=[[[0,0] for i in range(TimeP)] for i in range(classes)]
population=5
TeachingHours=np.array([11,6,7,10,9,5])
ZerosT=np.zeros((len(TeachingHours),),dtype=int)
ZerosT=TeachingHours*0
ClassesProfe=[]
numTeachers=6
Thours=np.zeros((classes, numTeachers),dtype=int)
AssigsProfe=[[[] for i in range(numTeachers)] for i in range(classes)]
Thours=Thours.tolist()
#0->Profe a l'institut, 1-> profe no és a l'institut
TeacherNoDays=[[1,0,0,0,0],[0,1,0,0,0],[0,0,0,1,1],[0,0,0,0,0],[0,0,1,0,0],[0,0,0,0,0]]
Total_Teachers=6
#TeachersTimeTable=[[[] for i in range(TimeP)] for i in range(numTeachers)]
#TeachersTimeTable=[[0 for i in range(TimeP)] for i in range(numTeachers)]

In [3]:
ClasseAssignatura2=[[[3,1,0,0],[2,2,0,0],[4,3,0,0],[3,1,0,0],[3,4,5,0],[3,4,0,7],[3,6,0,6]],
                    [[3,1,0,0],[4,2,0,4],[3,3,0,0],[4,4,0,2],[6,5,0,0],[2,6,0,0],[2,1,0,0]]]
print(ClasseAssignatura2)
print(" ")
#ClasseAssignatura3 = ClasseAssignatura2[:]
ClasseAssignatura3 = copy.deepcopy(ClasseAssignatura2)
print(ClasseAssignatura3)
print(" ")
print(Chromo)

[[[3, 1, 0, 0], [2, 2, 0, 0], [4, 3, 0, 0], [3, 1, 0, 0], [3, 4, 5, 0], [3, 4, 0, 7], [3, 6, 0, 6]], [[3, 1, 0, 0], [4, 2, 0, 4], [3, 3, 0, 0], [4, 4, 0, 2], [6, 5, 0, 0], [2, 6, 0, 0], [2, 1, 0, 0]]]
 
[[[3, 1, 0, 0], [2, 2, 0, 0], [4, 3, 0, 0], [3, 1, 0, 0], [3, 4, 5, 0], [3, 4, 0, 7], [3, 6, 0, 6]], [[3, 1, 0, 0], [4, 2, 0, 4], [3, 3, 0, 0], [4, 4, 0, 2], [6, 5, 0, 0], [2, 6, 0, 0], [2, 1, 0, 0]]]
 
[[[0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0]], [[0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0]]]


In [4]:
def Calculate_TeachingHours():    
    c=0
    for classe in ClasseAssignatura2:

        for assignatura in classe:
            professor=assignatura[1]
            hores=assignatura[0]
            #Per casa assignatura sumam en 1 el num d'assignatures al profe que la dona
            #Només calculam les hores de profe "principal"-> REVISAR SI AIXÒ SUPOSA ALGUN PROBLEMA
            #ANAR ALERTA!!!!!!!!!!!!!!!!!!!!!!
            #Aquest valor l'utilitzarem al cost de les classes
            #print(AssigsProfe)
            #AssigsProfeh[c][professor-1].append([hores])
            #AssigProfeU[c][professor-1].append([0])
            #print(AssigsProfe)
            Thours[c][professor-1]=Thours[c][professor-1]+hores
            #Si hi ha SC:
            if assignatura[2]!=0:
                profeSC=assignatura[2]
                Thours[c][profeSC-1]=Thours[c][profeSC-1]+hores  

        c=c+1;

    print(Thours)
    

In [5]:
def getDictProfes():
    dctKTeach=[]
    dctVTeach=[]
    for classe in ClasseAssignatura2:
        idx_Assig=0
        ProfesK=[]
        Profesv=[]
        for assignatura in classe:
            #Clau del diccionari profes 
            profes=[0,0]
            profes[0]=assignatura[1]
            if assignatura[2]!=0:
                profes[1]=assignatura[2]
            if assignatura[3]!=0:
                ProfeCT=classe[assignatura[3]-1][1]
                profes[1]=ProfeCT 
            #Quan hi hagi coteaching posam només el numero de una de les assignatures l'altra està assignada de manera implicita
            #Contingut a afegir (dictvalue)
            numhores=assignatura[0]
            #[Numassignatura, hores, utilitzat]
            infoAssig=[idx_Assig+1,numhores,0]
            
            if profes in ProfesK:
                Profesv[ProfesK.index(profes)].append(infoAssig)
            else:
                ProfesK.append(profes)
                Profesv.append([infoAssig])
                

            idx_Assig=idx_Assig+1
        dctKTeach.append(ProfesK)
        dctVTeach.append(Profesv)
        
    return dctKTeach,dctVTeach

In [6]:
Thours=np.zeros((classes, numTeachers),dtype=int)
#numAssigProfe=np.zeros((classes, numTeachers),dtype=int)
AssigsProfe=[[[] for i in range(numTeachers)] for i in range(classes)]
print(AssigsProfe)
print(" ")
print(ClasseAssignatura2)
print(" ")
Calculate_TeachingHours()

d_TeachersK,d_TeachersV=getDictProfes()
classTimeT=[0 for i in range(population)]

[[[], [], [], [], [], []], [[], [], [], [], [], []]]
 
[[[3, 1, 0, 0], [2, 2, 0, 0], [4, 3, 0, 0], [3, 1, 0, 0], [3, 4, 5, 0], [3, 4, 0, 7], [3, 6, 0, 6]], [[3, 1, 0, 0], [4, 2, 0, 4], [3, 3, 0, 0], [4, 4, 0, 2], [6, 5, 0, 0], [2, 6, 0, 0], [2, 1, 0, 0]]]
 
[[6 2 4 6 3 3]
 [5 4 3 4 6 2]]


In [7]:
def IdealTeachingDayHours():
    TeacherIdealHours=[]
    for t in range (numTeachers):
        horesideals=TeachingHours[t]/(5-np.count_nonzero(TeacherNoDays[t]))
        TeacherIdealHours.append(horesideals)
    return TeacherIdealHours

In [8]:
TeacherIdealHours=IdealTeachingDayHours()

## Funcions

In [9]:
BASE=1.5
HCW=10#??????
IDWT=3
TEPW=2


In [10]:
def CTeacherUnable(teachers,hora,individu):
    #print("hora",hora)
    dia=int(hora/7)
    #print("dia",dia)
    cost=0
    #print("profes",teachers)
    for teacher in teachers:
        if teacher != 0: 
            #print("at School?")
            #print(teacher,dia)
            #print(TeacherNoDays[teacher-1][dia])
            cost=cost+TeacherNoDays[teacher-1][dia]
            costsTeachers[individu][teacher-1]=costsTeachers[individu][teacher-1]+(HCW*(BASE**3))
    return cost
    

Teacher’s empty spaces: For each teacher the following subcost is added:
TEPW ∗ HOURS ∗ BASE^DAYS, where
HOURS is the total number of empty time periods in the teacher’s timetable and DAYS is the number of days that empty time periods exist in the timetable of this specific teacher


In [11]:
#Class’s empty spaces cost calculat i funciona correctament :)
#HCW*BASE^BASE
def C_classEmptySpaces(individu):
    costClEmptySpaces=0
    emptyHour=False
    
    for classe in individu:
        timeP=0
        #cLessonDispersion=costClLessDispersion(classe)
        for teachers in classe:
            #Si canviam de dia resetejam les variables          
            if timeP%7==0:
                emptyHour=False
            #Si hi ha una hora buida activam empty hour  
            if teachers==[0,0]:
                emptyHour=True
            #Si hi ha una hora ocupada i prèviament hi ha hagut una hora buida el mateix dia sumam 1 al cost
            elif emptyHour==True:
                emptyHour=False
                costClEmptySpaces=costClEmptySpaces+1
            timeP=timeP+1
    cost=costClEmptySpaces*HCW*(BASE**BASE)
    return cost  

In [12]:
#Crea els horaris per cada classe i calcula lesson dispersion
def createClassTimetable(individu):
    classTimeT=[[0 for i in range(TimeP)] for i in range(classes)]
    
    dtKeys=copy.deepcopy(d_TeachersK)
    dtValues=copy.deepcopy(d_TeachersV)
    i_class=0
    costClLessonDisp=0
  
    for classe in individu:
        h=0
        c_hours=0
        c_days=0
        h2=0
        for day in range(5):
            for hour in range(7):
                teachers=individu[i_class][h]
                if teachers==[0,0]:
                    classTimeT[i_class][h]=0
                else:
                    indx=dtKeys[i_class].index(teachers)
                    #Buscam la assignatura d'aquest profe/s amb valor d 'utilitzat menor
                    #que encara tengui hores per assignar
                    AssigProfe=copy.deepcopy(dtValues[i_class][indx])
                    #Ordenam de menor a major segons el valor d'utilitzat:
                    #print("profes ",teachers)
                    #print("index",indx)
                    #print("AsigProfes= ",AssigProfe)
                    #print("hora ", h)
                    AssigProfe.sort(key=lambda x: x[2])
                    #Assignam una hora d'aquesta assignatura i la marcam com utilitzada
                    #Buscam una assignatura a la que encara li quedin hores
                    i=0
                    while AssigProfe[i][1]==0:
                        i=i+1
                        
                    #print("AsigProfesOrdenat= ",AssigProfe)
                    #print("Assignatura seleccionada ",AssigProfe[i][0])
                    #Guardam numAssignatura
                    classTimeT[i_class][h]=AssigProfe[i][0]
                    i_assig=dtValues[i_class][indx].index(AssigProfe[i])
                    #print("i_assig ",i_assig)
                    
                    #incrementam utilitzat
                    dtValues[i_class][indx][i_assig][2]=dtValues[i_class][indx][i_assig][2]+1
                    #idx,numhores,utilitzat
                    #Decrementam les hores 
                    dtValues[i_class][indx][i_assig][1]=dtValues[i_class][indx][i_assig][1]-1
                    #print("classTimeT ",classTimeT)
                    #print("dtValues ",dtValues)
                    #print("---------------------------")
                h=h+1
            #Canvi de dia:
            
            DaySubjects=classTimeT[i_class][h2:h2+7]
            DaySubjects=[elem for elem in DaySubjects if elem!=0]
            NumRepeatedS=len(DaySubjects)-len(set(DaySubjects))
            #print("horesDIA",NumRepeatedS)
            c_hours=c_hours+NumRepeatedS
            if NumRepeatedS >0:
                c_days=c_days+1
            h2=h2+7
           
            #Reset de utilitzat:
            t=0
            for AssigT in dtValues[i_class]:
                for assig in range(len(AssigT)):
                    dtValues[i_class][t][assig][2]=0
                t=t+1 
        #Calculam el cost del dia  IDWC ∗ HOURS ∗ BASE^DAYS:
        costClLessonDisp=costClLessonDisp+IDWT*c_hours*(BASE**c_days)
        #print("cost hores ", c_hours)
        #print("cost dies ",c_days)
        i_class=i_class+1
            
    return classTimeT,costClLessonDisp
    
    


In [13]:
#TeachersTimeTable=np.zeros((numTeachers,TimeP), dtype=int).tolist()
#print(TeachersTimeTable)
#Funció per crear l'horari de cada un dels profes per cada individu :)
#Crec que funciona bé però s'ha de repassar!!!
def createTeachersTimeP(teachers,i_classe,i_timePeriod,TeachersTimeTable):
    #print(teachers)
    for teacher in teachers:
        if teacher!=0:
            #Guardam la classe que fa aquest profe en aquesta hora
            TeachersTimeTable[teacher-1][i_timePeriod]=i_classe+1
            #TeachersTimeTable[teacher-1][i_timePeriod].append(i_classe+1)
    return TeachersTimeTable


In [14]:
#Cost 1 i cost 2 calculats i funcionen correctament :)

def calc_C1_C2(individu,indx_individu):
    costUnable=0
    costMore1class=0
    #TeachersTimeTable=[[[] for i in range(TimeP)] for i in range(numTeachers)]
    TeachersTimeTable=[[0 for i in range(TimeP)] for i in range(numTeachers)]
    
    #llista dels profes assignats a una hora
    teacher_timeP=[]
    #for individu in population:
    for i_timePeriod in range(TimeP):
        teacher_timeP=[]
        for i_classe in range(classes):

            teachers=individu[i_classe][i_timePeriod]
            #print("profes",teachers)
            #Cream els horaris dels profes -> Aixo no ho empleam pero vaja
            TeachersTimeTable=createTeachersTimeP(teachers,i_classe,i_timePeriod,TeachersTimeTable)
            #Calculam el cost de si el profe no és a l'institut
            costU=CTeacherUnable(teachers,i_timePeriod,indx_individu)
            #if costU!=0:
                #print("--------------------")
                #print(i_timePeriod)
                #print("teachers",teachers)
                #print("costU",costU)
                #print("costUnable",costUnable)
            teacher_timeP.extend(teachers)
            costUnable=costUnable+costU
            #print("cost, i_timePeriod",costU,i_timePeriod)

        #Eliminam de la llista els buits(teacher 0) ja que teacher 0 no és cap teacher
        teacher_timeP=[elem for elem in teacher_timeP if elem != 0]
        #print(set(teacher_timeP))
        #print(teacher_timeP)
        cM1c_K=len(teacher_timeP)-len(set(teacher_timeP))
        costMore1class=costMore1class+HCW*(BASE**cM1c_K)
        #Calculate the cost for each teacher
        for t in teacher_timeP:
            k=teacher_timeP.count(t)-1
            teachersM1c_Cost=HCW*(BASE**k)
            costsTeachers[indx_individu][teacher-1]=costsTeachers[indx_individu][teacher-1]+HCW*(BASE**k)

    costUnable=costUnable*(HCW*(BASE**3))
    return(costUnable,costMore1class,TeachersTimeTable)


In [15]:
#Cost Teacher empty spaces and dispersion
def CostTeacherE_i_D(idx_individu,TeachersTimeTable1):
    costTeacherEmpty=0
    costTeacherLDisp=0
    cTeacherDisph=0
    cTeacherDispd=0
    hoursTeacher=0#num hores que fa un profe cada dia
    TotalcostTeacherDisp=0
    EmptyFound=False
    TeacherIdealHours=IdealTeachingDayHours()
    t=0#index del professor
    
    for teacher in TeachersTimeTable1:
        h=0
        chours=0#cost hores
        cdays=0 #cost dies
        
        for day in range(5):
            incr=False
            for hour in range(7):
                
                if teacher[h]!=0:
                    hoursTeacher=hoursTeacher+1
                    #Si trobam una hora ocupada després de trobar un espai buit
                    if EmptyFound==True:
                        chours=chours+1
                        incr=True
                        EmptyFound=False
                    
                elif teacher[h]==0:
                    EmptyFound=True
                    
                h=h+1#index de les hores
                
            #Quan canviam de dia incrementam el cost del dia i resetejam els paràmetres:
            #Si les hores que fa un professor un dia es desvien en més de 1 de la mitjana ideal:
            hour_difference=abs(hoursTeacher-TeacherIdealHours[t])
            if hour_difference >= 1:
                cTeacherDisph=cTeacherDisph+hour_difference
                cTeacherDispd=cTeacherDispd+1
            if incr==True:
                cdays=cdays+1
            hoursTeacher=0
            incr=False
            EmptyFound=False
            
        #Càlcul del cost de lesson's dispersion
        costTLD=IDWT*cTeacherDisph*(BASE**cTeacherDispd)
        costTeacherLDisp=costTeacherLDisp+costTLD
        costsTeachers[idx_individu][t-1]=costsTeachers[idx_individu][t-1]+costTLD
        
        #Aquí calcul del cost de Empty Scpaces
        costES=TEPW*chours*(BASE**cdays)
        costTeacherEmpty=costTeacherEmpty+costES
        costsTeachers[idx_individu][t-1]=costsTeachers[idx_individu][t-1]+costES
        
        t=t+1
        cTeacherDisph=0
        cTeacherDispd=0
        
    return costTeacherLDisp,costTeacherEmpty
            

. Teacher lessons’ dispersion: For each teacher the following subcost is added: 
IDWT ∗ HOURS ∗ BASE^DAYS
, where HOURS is the total number of time periods that are different compared to the ideal dispersion teacher’s timetable and DAYS is the number of days in the teacher’s timetable that such a declination from the ideal case exists

In [16]:
def costFunction(pobl):    
    #costsTeachers=[[0 for i in range(numTeachers)] for i in range(population)] #declarar antes de cridar funcio
    costs=[0 for i in range(len(pobl))]
    idx_individu=0
    
    
    for individu in pobl:
        #print("costs ",costs)
        #print("idx_individu ",idx_individu)
        
        #TeachersTimeTable=[[0 for i in range(TimeP)] for i in range(numTeachers)]

        cTU,cM1cl,TeachersTimeTable=calc_C1_C2(individu,idx_individu)

        cES=C_classEmptySpaces(individu)

        cTE,cTLD=CostTeacherE_i_D(idx_individu,TeachersTimeTable)
        
        classTimeT[idx_individu],cClassLDisp=createClassTimetable(individu)
        #print("cTU ",cTU)
        #print("cM1cl ",c#M1cl)
        #print("cES ",cES)
        #print("cTE ",cTE)
        #print("cTLD ",cTLD)
        #print("cClassLDisp ",cClassLDisp)

        TotalCost=cTU+cM1cl+cES+cTE+cTLD+cClassLDisp

        #print("CTEACH!",costsTeachers)
        
        costs[idx_individu] = TotalCost
        idx_individu=idx_individu+1
    
    return costs


In [17]:
#Recorrem les assignatures d'una classe
#[slots,professor1,professorSC,AssignaturaCT]

def decrementarHores(teacher,classe,Thours):
    #Recorrem les assignatures de la classe buscant les que fa el profe teacher
    #c= assignatures de la classe 1
    
    idxAssigntr=0

    c=ClasseAssignatura3[classe][:]

    for assignatura in c:

        if assignatura[1]==teacher and assignatura[0]>0:

            #Decrementam 
            ClasseAssignatura3[classe][idxAssigntr][0]=ClasseAssignatura3[classe][idxAssigntr][0]-1
            Thours[classe][teacher-1]=Thours[classe][teacher-1]-1
            teachers=[teacher,0]
          
            
            #si hi ha SC les decrementam de Thours
            if ClasseAssignatura3[classe][idxAssigntr][2]!=0:
                
                teacher2=ClasseAssignatura3[classe][idxAssigntr][2]
               
                Thours[classe][teacher2-1]=Thours[classe][teacher2-1]-1
                teachers=[teacher,teacher2]
               
                
            #Si hi ha coteaching llevam les hores de l'altra assignatura:
            if ClasseAssignatura3[classe][idxAssigntr][3]!=0:
                #Seleccionam el valor de l'index de l'assignatura amb la que hi ha coteaching
                AssigCT=ClasseAssignatura3[classe][idxAssigntr][3]
                
                #Decrementam en 1h les hores pendents d'assignar de l'assignatura de CT
                ClasseAssignatura3[classe][AssigCT-1][0]=ClasseAssignatura3[classe][AssigCT-1][0]-1
                teacherCT=ClasseAssignatura3[classe][AssigCT-1][1]
                Thours[classe][teacherCT-1]=Thours[classe][teacherCT-1]-1
                teachers=[teacher,teacherCT]
                
            
            break
                
        idxAssigntr=idxAssigntr+1
    #c=ClasseAssignatura3[classe][:]
    
    #print("ClasseAssignatura3 decrem",ClasseAssignatura3)
    return Thours,teachers
                
        

In [18]:
# def mutation(pob, costsT):
#     period_mutation_probability = 0.05
#     bad_mutation_probability = 0.05
#     poblacio_mutada = []
#     classes_mutades = []
#     print(" ")
#     print("COst abans de fer res", costsT)
#     #print("Costs antes de mutar:")
#     #costsTeachers=[[0 for i in range(numTeachers)] for i in range(population)]
#     #cosstt=costFunction(pob)
#     #print("Costs ",cosstt)
#     print(" ")
#     print("WTF is happening Original?")
#     print(pob[0]==pob[1])
#     print(pob[1]==pob[2])
#     print(pob[2]==pob[3])
#     print(pob[3]==pob[4])
#     print("no entenc reeeees")
#     pCopia=copy.deepcopy(pob)
#     p_mutada=copy.deepcopy(pob)
    
#     # No mutam el primer individu ja que podriem perdre la millor opcio
#     #poblacio_mutada.append(pob[0])

    
#     for i_individu in range(1,len(p_mutada)):
#         for i_classe in range(len(p_mutada[i_individu])):
            
#             # Period mutation
#             if random.random() < period_mutation_probability:
#                 random_tp_1 = random.randrange(0, len(p_mutada[i_individu][i_classe]))
#                 random_tp_2 = random.randrange(0, len(p_mutada[i_individu][i_classe]))
#                 print("Antes de canviar ", p_mutada[i_individu][i_classe])
#                 print(" ")
                
#                 Tp1=p_mutada[i_individu][i_classe][random_tp_1]
#                 Tp2=p_mutada[i_individu][i_classe][random_tp_2]
                
#                 p_mutada[i_individu][i_classe][random_tp_1]=Tp2
#                 p_mutada[i_individu][i_classe][random_tp_2]=Tp1
                
#                 print("Després de canviar ", p_mutada[i_individu][i_classe])
                
#                 print("Individu mutat: ",i_individu)
#                 #print("--- CLASSE MUTADA ---", chromo.index(pob[i_individu]))
#                 print("--- CLASSE MUTADA ---", i_classe)
#                 print("Periode 1 ", random_tp_1)
#                 print("Periode 1 ", random_tp_2)
#                 print("periodes canviats: ",Tp1," ",Tp2)
#                 #print("Periode 2 ",classe.index(classe[random_tp_2]))     
        
#     for i in range(len(p_mutada)):
        
#         print("-------------------")
#         print("individu", i)
#         print("Original ",pob[i])
#         print(" ")
#         print("Pcopia ",pCopia[i])
#         #print("POriginal",p_original[i])
#         print(" ")
#         print("Mutat",p_mutada[i])
#         print(" ")
#         print("Individus iguals POB-P_MUT ? ", pob[i]==p_mutada[i])
#         #print("Individus iguals PORI-POB_MUT? ", p_original[i]==poblacio_mutada[i])
       
#     print("Son iguals_ POB-P_MUT? ",pob==p_mutada)    
#     print("Son iguals Pcopia-POB_MUT? ",pCopia==p_mutada) 
    
#     #print("Son iguals P_ORI-POB? ",p_original==pob) 
#     #print("Costs DESPRES de mutar:")
#     #cosstt=costFunction(p_mutada#)
#     #print("Costs ",cosstt)
#     #costsTeachers=[[0 for i in range(numTeachers)] for i in range(population)]
#     #c=costFunction(p_mutada)
#     #print("Costs ",c)
    
#     return p_mutada

In [19]:
a=[[[0,0],0],[0,1],[0,0]]
b=[[[0,0],0],[0,1],[0,0]]
a==b

True

In [20]:
def mutation(pob):
    period_mutation_probability = 0.05
    bad_mutation_probability = 0.05
   
    pCopia=copy.deepcopy(pob)
    p_mutada=copy.deepcopy(pob)
    
    # No mutam el primer individu ja que podriem perdre la millor opcio
    #poblacio_mutada.append(pob[0])

    for i_individu in range(1,len(pob)):
        for i_classe in range(len(pob[i_individu])):
            
            # Period mutation
            if random.random() < period_mutation_probability:
                
                random_tp_1 = random.randrange(0, len(pob[i_individu][i_classe]))
                random_tp_2 = random.randrange(0, len(pob[i_individu][i_classe]))
                
                print("Antes de canviar ", p_mutada[i_individu][i_classe])
                print(" ")
                
                Tp1=p_mutada[i_individu][i_classe][random_tp_1][:]
                Tp2=p_mutada[i_individu][i_classe][random_tp_2][:]
                
                p_mutada[i_individu][i_classe][random_tp_1]=Tp2
                p_mutada[i_individu][i_classe][random_tp_2]=Tp1
                
                print("Després de canviar ", p_mutada[i_individu][i_classe])
                
                print("---INDIVIDU mutat: ---",i_individu)
                print("--- CLASSE MUTADA ---", i_classe)
                print("Periode 1 ", random_tp_1)
                print("Periode 1 ", random_tp_2)
                print("periodes canviats: ",Tp1," ",Tp2)    
        
    for i in range(len(p_mutada)):
        
        print("-------------------")
        print("individu", i)
        print("Original ",pob[i])
        print(" ")
        print("Pcopia ",pCopia[i])
        #print("POriginal",p_original[i])
        print(" ")
        print("Mutat",p_mutada[i])
        print(" ")
        print("Individus iguals POB-P_MUT ? ", pob[i]==p_mutada[i])
        print("Individus iguals POB-P_MUT ? ", pCopia[i]==p_mutada[i])
        #print("Individus iguals PORI-POB_MUT? ", p_original[i]==poblacio_mutada[i])
       
    print("Son iguals_ POB-P_MUT? ",pob==p_mutada)    
    print("Son iguals Pcopia-POB_MUT? ",pCopia==p_mutada) 
    
    #print("Son iguals P_ORI-POB? ",p_original==pob) 
    #print("Costs DESPRES de mutar:")
    #cosstt=costFunction(p_mutada#)
    #print("Costs ",cosstt)
    #costsTeachers=[[0 for i in range(numTeachers)] for i in range(population)]
    #c=costFunction(p_mutada)
    #print("Costs ",c)
    
    return p_mutada

def mutation(poblacio, costsT):
    period_mutation_probability = 0.05
    bad_mutation_probability = 0.05
    poblacio_mutada = []
    classe_mutada = []

    # Period mutation
    #rand = random.random()
    if random.random() < period_mutation_probability:
        for chromo in poblacio:
            for classe in chromo:
                random_tp_1 = random.randrange(0, len(classe))
                random_tp_2 = random.randrange(0, len(classe))
                classe[random_tp_2], classe[random_tp_1] = classe[random_tp_1], classe[random_tp_2]
                classe_mutada.append(classe)
            poblacio_mutada.append(classe_mutada)
            classe_mutada = []
    
    # Bad mutation
    
    
     
    else:
        poblacio_mutada = poblacio
    
    return poblacio_mutada

elif random.random() < bad_mutation_probability:
        # Look for worst teacher timetable
        for individu in costsT:
            individuC=copy.deepcopy(individu)
            print("costTeacher",costsT)
            print("individu",individu)
            worst_teacher_1 = individuC.index(max(individuC))
            individuC[worst_teacher_1]=0
            worst_teacher_2 = individuC.index(max(individuC))
            print("worst teachers: ",worst_teacher_1,worst_teacher_2)
        # Swap teachers

## Creació de la primera població

In [21]:
poblacio=[0 for i in range(population)]
for i in range(population):
    Thours=np.zeros((classes, numTeachers),dtype=int)
    Calculate_TeachingHours()
    ClasseAssignatura3=copy.deepcopy(ClasseAssignatura2)
    for classe in range(classes):
        for hour in range(TimeP):
            c=copy.deepcopy(ClasseAssignatura2[classe])
            ok=False
            #Chose a teacher at random 
            print("classe= ",classe)
            print(Thours[classe])
            
            # Miram si s'han assignat totes les hores d'una classe.
            if np.array_equal(ZerosT,Thours[classe])==False:
                while ok==False:#mirar que no sigui que no et quedin profes i se quedi aqui infinitament
                    teacher=randrange(1, numTeachers+1)
                    print("teacher",teacher)
                    #Per cada assignatura d'aquesta classe:
                    for j in c:
                        #print("i",i) 
                        #print("c",c)
                        #print("i[1]",i[1])
                        #print(Thours[classe][teacher-1])
                        if(j[1]==teacher) and Thours[classe][teacher-1]!=0:
                            ok=True
                    #ok=True       
                print("thours",Thours[classe][teacher-1])
                print("selected teacher", teacher)
                print("decrementam ")
                Thours,teachers=decrementarHores(teacher,classe,Thours)
                print("classe",classe)
                print("hours",hour)                
                Chromo[classe][hour]=teachers
                print("TeacherHours, teachers :",Thours[classe], teachers)

                print(teachers)
                
            
                #Assignar slot buit
            print("buit")
    print("index",i)      
    poblacio[i]=copy.deepcopy(Chromo)
    #break

                            
                

                        
                #Now we have a teacher!!!
                #print(teacher)

                #Decrementam les hores agafant una hora en concret d'una assignatura
                
                #TeachingHours[teacher-1]=TeachingHours[teacher-1]-1
                #TeachingHours=a
      

        
#Si algun teacher només està de subclasse mai el decrementa directament !Alerta!  

[[6 2 4 6 3 3]
 [5 4 3 4 6 2]]
classe=  0
[6 2 4 6 3 3]
teacher 3
thours 4
selected teacher 3
decrementam 
classe 0
hours 0
TeacherHours, teachers : [6 2 3 6 3 3] [3, 0]
[3, 0]
buit
classe=  0
[6 2 3 6 3 3]
teacher 3
thours 3
selected teacher 3
decrementam 
classe 0
hours 1
TeacherHours, teachers : [6 2 2 6 3 3] [3, 0]
[3, 0]
buit
classe=  0
[6 2 2 6 3 3]
teacher 1
thours 6
selected teacher 1
decrementam 
classe 0
hours 2
TeacherHours, teachers : [5 2 2 6 3 3] [1, 0]
[1, 0]
buit
classe=  0
[5 2 2 6 3 3]
teacher 2
thours 2
selected teacher 2
decrementam 
classe 0
hours 3
TeacherHours, teachers : [5 1 2 6 3 3] [2, 0]
[2, 0]
buit
classe=  0
[5 1 2 6 3 3]
teacher 6
thours 3
selected teacher 6
decrementam 
classe 0
hours 4
TeacherHours, teachers : [5 1 2 5 3 2] [6, 4]
[6, 4]
buit
classe=  0
[5 1 2 5 3 2]
teacher 4
thours 5
selected teacher 4
decrementam 
classe 0
hours 5
TeacherHours, teachers : [5 1 2 4 2 2] [4, 5]
[4, 5]
buit
classe=  0
[5 1 2 4 2 2]
teacher 5
teacher 5
teacher 2
thours 1

classe=  0
[0 0 0 0 0 0]
buit
classe=  0
[0 0 0 0 0 0]
buit
classe=  1
[5 4 3 4 6 2]
teacher 2
thours 4
selected teacher 2
decrementam 
classe 1
hours 0
TeacherHours, teachers : [5 3 3 3 6 2] [2, 4]
[2, 4]
buit
classe=  1
[5 3 3 3 6 2]
teacher 3
thours 3
selected teacher 3
decrementam 
classe 1
hours 1
TeacherHours, teachers : [5 3 2 3 6 2] [3, 0]
[3, 0]
buit
classe=  1
[5 3 2 3 6 2]
teacher 4
thours 3
selected teacher 4
decrementam 
classe 1
hours 2
TeacherHours, teachers : [5 2 2 2 6 2] [4, 2]
[4, 2]
buit
classe=  1
[5 2 2 2 6 2]
teacher 4
thours 2
selected teacher 4
decrementam 
classe 1
hours 3
TeacherHours, teachers : [5 1 2 1 6 2] [4, 2]
[4, 2]
buit
classe=  1
[5 1 2 1 6 2]
teacher 2
thours 1
selected teacher 2
decrementam 
classe 1
hours 4
TeacherHours, teachers : [5 0 2 0 6 2] [2, 4]
[2, 4]
buit
classe=  1
[5 0 2 0 6 2]
teacher 2
teacher 3
thours 2
selected teacher 3
decrementam 
classe 1
hours 5
TeacherHours, teachers : [5 0 1 0 6 2] [3, 0]
[3, 0]
buit
classe=  1
[5 0 1 0 6 2]

teacher 5
thours 5
selected teacher 5
decrementam 
classe 1
hours 1
TeacherHours, teachers : [5 4 3 4 4 2] [5, 0]
[5, 0]
buit
classe=  1
[5 4 3 4 4 2]
teacher 6
thours 2
selected teacher 6
decrementam 
classe 1
hours 2
TeacherHours, teachers : [5 4 3 4 4 1] [6, 0]
[6, 0]
buit
classe=  1
[5 4 3 4 4 1]
teacher 4
thours 4
selected teacher 4
decrementam 
classe 1
hours 3
TeacherHours, teachers : [5 3 3 3 4 1] [4, 2]
[4, 2]
buit
classe=  1
[5 3 3 3 4 1]
teacher 1
thours 5
selected teacher 1
decrementam 
classe 1
hours 4
TeacherHours, teachers : [4 3 3 3 4 1] [1, 0]
[1, 0]
buit
classe=  1
[4 3 3 3 4 1]
teacher 5
thours 4
selected teacher 5
decrementam 
classe 1
hours 5
TeacherHours, teachers : [4 3 3 3 3 1] [5, 0]
[5, 0]
buit
classe=  1
[4 3 3 3 3 1]
teacher 1
thours 4
selected teacher 1
decrementam 
classe 1
hours 6
TeacherHours, teachers : [3 3 3 3 3 1] [1, 0]
[1, 0]
buit
classe=  1
[3 3 3 3 3 1]
teacher 4
thours 3
selected teacher 4
decrementam 
classe 1
hours 7
TeacherHours, teachers : [

## Loop iteratiu

In [22]:
N = population
n_min = 0.2
n_max = 2 - n_min
    
probability = []

# Calcul de probabilitat de reproduccio
for i in range(N):
    probability.append((1/N)*(n_min+(n_max - n_min)*(i)/(N-1)))
    #probability.append(np.divide(1,N)*np.divide(n_min+(n_max - n_min)*(i-1),(N-1)))
    
# Vector de probabilitats de reproduccio
mapped = []
mapped.append(0)

for i in range(len(probability)-1):
    mapped.append(mapped[i] + probability[i])

mapped.append(1)

In [23]:
#PROVA!

for i in range(4):
    costsTeachers=[[0 for i in range(numTeachers)] for i in range(population)]
    #classTimeT=[0 for i in range(population)]
    #Thours=np.zeros((classes, numTeachers),dtype=int)
    #Calculate_TeachingHours()
    #ClasseAssignatura3=copy.deepcopy(ClasseAssignatura2)
    calculatedCosts=costFunction(poblacio)
    print("Costs ",calculatedCosts)
    #print("CostsTeachers ",costsTeachers[0])
    #print("CostsTeachers ",costsTeachers[1])
    #print(" ")
#----------------------------------------Provam la mutació:
for i in range(50):
    #print("població original ", poblacio)
    poblacio_mutada = mutation(poblacio)
    for i in range(len(poblacio)):
        print(poblacio[i])
        print(" ")
        print(poblacio_mutada[i])
        print("Iguales??",poblacio[i]==poblacio_mutada[i])

Costs  [1567.75, 1697.828125, 1568.125, 1670.0546875, 1683.6875]
Costs  [1567.75, 1697.828125, 1568.125, 1670.0546875, 1683.6875]
Costs  [1567.75, 1697.828125, 1568.125, 1670.0546875, 1683.6875]
Costs  [1567.75, 1697.828125, 1568.125, 1670.0546875, 1683.6875]
-------------------
individu 0
Original  [[[3, 0], [3, 0], [1, 0], [2, 0], [6, 4], [4, 5], [2, 0], [4, 5], [6, 4], [1, 0], [6, 4], [4, 5], [3, 0], [3, 0], [1, 0], [1, 0], [1, 0], [1, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0]], [[1, 0], [4, 2], [4, 2], [6, 0], [4, 2], [5, 0], [3, 0], [3, 0], [6, 0], [2, 4], [1, 0], [5, 0], [3, 0], [1, 0], [5, 0], [1, 0], [1, 0], [5, 0], [5, 0], [5, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0]]]
 
Pcopia  [[[3, 0], [3, 0], [1, 0], [2, 0], [6, 4], [4, 5], [2, 0], [4, 5], [6, 4], [1, 0], [6, 4], [4, 5], [3, 0], [3, 0], [1, 0], [1

Mutat [[[2, 0], [2, 0], [4, 5], [3, 0], [6, 4], [3, 0], [6, 4], [4, 5], [3, 0], [4, 5], [1, 0], [1, 0], [1, 0], [6, 4], [3, 0], [1, 0], [1, 0], [1, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0]], [[5, 0], [5, 0], [6, 0], [4, 2], [1, 0], [5, 0], [1, 0], [4, 2], [4, 2], [4, 2], [6, 0], [5, 0], [3, 0], [5, 0], [1, 0], [1, 0], [5, 0], [1, 0], [3, 0], [3, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0]]]
 
Individus iguals POB-P_MUT ?  True
Individus iguals POB-P_MUT ?  True
-------------------
individu 4
Original  [[[6, 4], [2, 0], [3, 0], [6, 4], [2, 0], [1, 0], [3, 0], [6, 4], [4, 5], [4, 5], [1, 0], [1, 0], [3, 0], [3, 0], [4, 5], [1, 0], [1, 0], [1, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0]], [[3, 0], [4, 2], [2, 4], [5, 0], 

-------------------
individu 0
Original  [[[3, 0], [3, 0], [1, 0], [2, 0], [6, 4], [4, 5], [2, 0], [4, 5], [6, 4], [1, 0], [6, 4], [4, 5], [3, 0], [3, 0], [1, 0], [1, 0], [1, 0], [1, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0]], [[1, 0], [4, 2], [4, 2], [6, 0], [4, 2], [5, 0], [3, 0], [3, 0], [6, 0], [2, 4], [1, 0], [5, 0], [3, 0], [1, 0], [5, 0], [1, 0], [1, 0], [5, 0], [5, 0], [5, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0]]]
 
Pcopia  [[[3, 0], [3, 0], [1, 0], [2, 0], [6, 4], [4, 5], [2, 0], [4, 5], [6, 4], [1, 0], [6, 4], [4, 5], [3, 0], [3, 0], [1, 0], [1, 0], [1, 0], [1, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0]], [[1, 0], [4, 2], [4, 2], [6, 0], [4, 2], [5, 0], [3, 0], [3, 0], [6, 0], [2, 4], [1, 0], [5, 0], [3, 

 
[[[2, 0], [2, 0], [4, 5], [3, 0], [6, 4], [3, 0], [6, 4], [4, 5], [3, 0], [4, 5], [1, 0], [1, 0], [1, 0], [6, 4], [3, 0], [1, 0], [1, 0], [1, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0]], [[5, 0], [5, 0], [6, 0], [4, 2], [1, 0], [5, 0], [1, 0], [4, 2], [4, 2], [4, 2], [6, 0], [5, 0], [3, 0], [5, 0], [1, 0], [1, 0], [5, 0], [1, 0], [3, 0], [3, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0]]]
Iguales?? True
[[[6, 4], [2, 0], [3, 0], [6, 4], [2, 0], [1, 0], [3, 0], [6, 4], [4, 5], [4, 5], [1, 0], [1, 0], [3, 0], [3, 0], [4, 5], [1, 0], [1, 0], [1, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0]], [[3, 0], [4, 2], [2, 4], [5, 0], [4, 2], [3, 0], [3, 0], [1, 0], [6, 0], [6, 0], [5, 0], [4, 2], [1, 0], [1, 0], [5, 0], [1, 0], [5, 0]

-------------------
individu 4
Original  [[[6, 4], [2, 0], [3, 0], [6, 4], [2, 0], [1, 0], [3, 0], [6, 4], [4, 5], [4, 5], [1, 0], [1, 0], [3, 0], [3, 0], [4, 5], [1, 0], [1, 0], [1, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0]], [[3, 0], [4, 2], [2, 4], [5, 0], [4, 2], [3, 0], [3, 0], [1, 0], [6, 0], [6, 0], [5, 0], [4, 2], [1, 0], [1, 0], [5, 0], [1, 0], [5, 0], [1, 0], [5, 0], [5, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0]]]
 
Pcopia  [[[6, 4], [2, 0], [3, 0], [6, 4], [2, 0], [1, 0], [3, 0], [6, 4], [4, 5], [4, 5], [1, 0], [1, 0], [3, 0], [3, 0], [4, 5], [1, 0], [1, 0], [1, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0]], [[3, 0], [4, 2], [2, 4], [5, 0], [4, 2], [3, 0], [3, 0], [1, 0], [6, 0], [6, 0], [5, 0], [4, 2], [1, 

-------------------
individu 3
Original  [[[2, 0], [2, 0], [4, 5], [3, 0], [6, 4], [3, 0], [6, 4], [4, 5], [3, 0], [4, 5], [1, 0], [1, 0], [1, 0], [6, 4], [3, 0], [1, 0], [1, 0], [1, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0]], [[5, 0], [5, 0], [6, 0], [4, 2], [1, 0], [5, 0], [1, 0], [4, 2], [4, 2], [4, 2], [6, 0], [5, 0], [3, 0], [5, 0], [1, 0], [1, 0], [5, 0], [1, 0], [3, 0], [3, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0]]]
 
Pcopia  [[[2, 0], [2, 0], [4, 5], [3, 0], [6, 4], [3, 0], [6, 4], [4, 5], [3, 0], [4, 5], [1, 0], [1, 0], [1, 0], [6, 4], [3, 0], [1, 0], [1, 0], [1, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0]], [[5, 0], [5, 0], [6, 0], [4, 2], [1, 0], [5, 0], [1, 0], [4, 2], [4, 2], [4, 2], [6, 0], [5, 0], [3, 

Iguales?? True
Antes de canviar  [[3, 0], [4, 2], [2, 4], [5, 0], [4, 2], [3, 0], [3, 0], [1, 0], [6, 0], [6, 0], [5, 0], [4, 2], [1, 0], [1, 0], [5, 0], [1, 0], [5, 0], [1, 0], [5, 0], [5, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0]]
 
Després de canviar  [[3, 0], [4, 2], [2, 4], [5, 0], [4, 2], [3, 0], [3, 0], [1, 0], [6, 0], [6, 0], [5, 0], [4, 2], [1, 0], [1, 0], [5, 0], [1, 0], [5, 0], [1, 0], [5, 0], [5, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0]]
---INDIVIDU mutat: --- 4
--- CLASSE MUTADA --- 1
Periode 1  16
Periode 1  19
periodes canviats:  [5, 0]   [5, 0]
-------------------
individu 0
Original  [[[3, 0], [3, 0], [1, 0], [2, 0], [6, 4], [4, 5], [2, 0], [4, 5], [6, 4], [1, 0], [6, 4], [4, 5], [3, 0], [3, 0], [1, 0], [1, 0], [1, 0], [1, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0,

In [24]:
a=[[[3, 0], [6, 4], [4, 5], [1, 0], [3, 0], [6, 4], [3, 0], [1, 0], [1, 0], [3, 0], [2, 0], [2, 0], [1, 0], [4, 5], [6, 4], [1, 0], [4, 5], [1, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0]], [[1, 0], [4, 2], [3, 0], [6, 0], [6, 0], [3, 0], [3, 0], [2, 4], [5, 0], [5, 0], [1, 0], [4, 2], [5, 0], [5, 0], [4, 2], [1, 0], [1, 0], [1, 0], [5, 0], [5, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0]]]
mu=[[[3, 0], [6, 4], [4, 5], [1, 0], [3, 0], [6, 4], [3, 0], [1, 0], [1, 0], [3, 0], [2, 0], [2, 0], [1, 0], [4, 5], [6, 4], [1, 0], [4, 5], [1, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0]], [[1, 0], [4, 2], [3, 0], [6, 0], [6, 0], [3, 0], [3, 0], [2, 4], [5, 0], [5, 0], [1, 0], [4, 2], [5, 0], [5, 0], [4, 2], [1, 0], [1, 0], [1, 0], [5, 0], [5, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0]]]


In [25]:
for i in range(100):
    print("------------------------------[",i)
    costsTeachers=[[0 for i in range(numTeachers)] for i in range(population)]
    calculatedCosts=costFunction(poblacio)
    print("COST 1",calculatedCosts)
    costsTeachers=[[0 for i in range(numTeachers)] for i in range(population)]
    calculatedCosts=costFunction(poblacio)
    print("COST 2",calculatedCosts)
    costsTeachers=[[0 for i in range(numTeachers)] for i in range(population)]
    calculatedCosts=costFunction(poblacio)
    print("COST 3",calculatedCosts)

    # Creació d'un diccionari per ordenar els individus per cost.
    costs={}
    for i in range(population):
        costs[i]=calculatedCosts[i]
    print(costs)

    sorted_costs = sorted(costs.items(), key=operator.itemgetter(1))
    sorted_costs.reverse()
    print(sorted_costs)
    
    
    nova_poblacio = []

    # Elitism: aseguram que el millor cromosoma pasa a la següent generacio
    nova_poblacio.append(poblacio[sorted_costs[-1][0]])
    print("MINIM",sorted_costs[-1])
#     print("R",poblacio[sorted_costs[-1][0]])
#     print("T",nova_poblacio[0])

    
    # Selecció dels individus a reproduir
    for i in range(N-1):
        rand = random.random()
        for i in range(len(probability)):
            if (rand > mapped[i]) & (rand <= mapped[i+1]):
                cromo_index = i
                break
        # Aqui s'ha triat el cromosoma que s'ha de reproduir. Ara l'hem de reproduir
        
        nova_poblacio.append(poblacio[sorted_costs[cromo_index][0]])
#     print("poblacio",poblacio)
#     print("nova pob",nova_poblacio)
    c1=costFunction(nova_poblacio)
    a=copy.deepcopy(nova_poblacio)
   
    poblacio_mutada = mutation(a)
    print("costs abans de la funcio ",c1)
    c2=costFunction(poblacio_mutada)
    print("costs despres de la mutació ",c2)
    print("POBLACIO",nova_poblacio)
    print("-------------+++++++++++++++++++++++++++++++++++++++++++++++++++++----------")
    print("POB MUTA",poblacio_mutada)
    
    print("Iguals o q? ",a==nova_poblacio)
    print("Iguals o q2? ",nova_poblacio==poblacio_mutada)
    poblacio = copy.deepcopy(poblacio_mutada)
    #costsTeachers=[[0 for i in range(numTeachers)] for i in range(population)]
    calculatedCosts=costFunction(poblacio_mutada)
    print("COST M", calculatedCosts)
    
    #poblacio=copy.deepcopy(nova_poblacio)

------------------------------[ 0
COST 1 [1567.75, 1697.828125, 1568.125, 1670.0546875, 1683.6875]
COST 2 [1567.75, 1697.828125, 1568.125, 1670.0546875, 1683.6875]
COST 3 [1567.75, 1697.828125, 1568.125, 1670.0546875, 1683.6875]
{0: 1567.75, 1: 1697.828125, 2: 1568.125, 3: 1670.0546875, 4: 1683.6875}
[(1, 1697.828125), (4, 1683.6875), (3, 1670.0546875), (2, 1568.125), (0, 1567.75)]
MINIM (0, 1567.75)
-------------------
individu 0
Original  [[[3, 0], [3, 0], [1, 0], [2, 0], [6, 4], [4, 5], [2, 0], [4, 5], [6, 4], [1, 0], [6, 4], [4, 5], [3, 0], [3, 0], [1, 0], [1, 0], [1, 0], [1, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0]], [[1, 0], [4, 2], [4, 2], [6, 0], [4, 2], [5, 0], [3, 0], [3, 0], [6, 0], [2, 4], [1, 0], [5, 0], [3, 0], [1, 0], [5, 0], [1, 0], [1, 0], [5, 0], [5, 0], [5, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0],

COST M [1592.7423461417477, 1592.7423461417477, 1592.7423461417477, 1592.7423461417477, 1592.7423461417477]
------------------------------[ 3
COST 1 [1592.7423461417477, 1592.7423461417477, 1592.7423461417477, 1592.7423461417477, 1592.7423461417477]
COST 2 [1592.7423461417477, 1592.7423461417477, 1592.7423461417477, 1592.7423461417477, 1592.7423461417477]
COST 3 [1592.7423461417477, 1592.7423461417477, 1592.7423461417477, 1592.7423461417477, 1592.7423461417477]
{0: 1592.7423461417477, 1: 1592.7423461417477, 2: 1592.7423461417477, 3: 1592.7423461417477, 4: 1592.7423461417477}
[(4, 1592.7423461417477), (3, 1592.7423461417477), (2, 1592.7423461417477), (1, 1592.7423461417477), (0, 1592.7423461417477)]
MINIM (0, 1592.7423461417477)
Antes de canviar  [[3, 0], [3, 0], [1, 0], [2, 0], [6, 4], [4, 5], [2, 0], [4, 5], [6, 4], [1, 0], [6, 4], [4, 5], [3, 0], [3, 0], [1, 0], [1, 0], [0, 0], [1, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [1, 0], [0, 0], [0, 0], [0, 0], [0,

Individus iguals POB-P_MUT ?  True
Individus iguals POB-P_MUT ?  True
-------------------
individu 4
Original  [[[3, 0], [3, 0], [1, 0], [2, 0], [6, 4], [4, 5], [2, 0], [4, 5], [6, 4], [1, 0], [6, 4], [4, 5], [3, 0], [3, 0], [1, 0], [1, 0], [0, 0], [1, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [1, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0]], [[1, 0], [4, 2], [4, 2], [6, 0], [4, 2], [5, 0], [3, 0], [3, 0], [6, 0], [2, 4], [1, 0], [5, 0], [3, 0], [1, 0], [5, 0], [1, 0], [1, 0], [5, 0], [5, 0], [5, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0]]]
 
Pcopia  [[[3, 0], [3, 0], [1, 0], [2, 0], [6, 4], [4, 5], [2, 0], [4, 5], [6, 4], [1, 0], [6, 4], [4, 5], [3, 0], [3, 0], [1, 0], [1, 0], [0, 0], [1, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [1, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0]], [[1, 0], [4, 2], [4, 2], [6, 0]

costs despres de la mutació  [1550.1409422834954, 1550.1409422834954, 1550.1409422834954, 1550.1409422834954, 1550.1409422834954]
POBLACIO [[[[3, 0], [3, 0], [1, 0], [2, 0], [6, 4], [4, 5], [2, 0], [4, 5], [0, 0], [1, 0], [6, 4], [4, 5], [3, 0], [3, 0], [1, 0], [1, 0], [0, 0], [1, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [6, 4], [0, 0], [1, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0]], [[1, 0], [4, 2], [4, 2], [6, 0], [4, 2], [5, 0], [3, 0], [3, 0], [6, 0], [2, 4], [1, 0], [5, 0], [3, 0], [1, 0], [5, 0], [1, 0], [1, 0], [5, 0], [5, 0], [5, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0]]], [[[3, 0], [3, 0], [1, 0], [2, 0], [6, 4], [4, 5], [2, 0], [4, 5], [0, 0], [1, 0], [6, 4], [4, 5], [3, 0], [3, 0], [1, 0], [1, 0], [0, 0], [1, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [6, 4], [0, 0], [1, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0]], [[1, 0], [4

Antes de canviar  [[3, 0], [3, 0], [1, 0], [2, 0], [6, 4], [4, 5], [2, 0], [4, 5], [0, 0], [0, 0], [6, 4], [4, 5], [3, 0], [3, 0], [1, 0], [1, 0], [0, 0], [1, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [6, 4], [0, 0], [1, 0], [0, 0], [0, 0], [0, 0], [0, 0], [1, 0], [0, 0], [0, 0], [0, 0]]
 
Després de canviar  [[3, 0], [3, 0], [1, 0], [2, 0], [6, 4], [4, 5], [2, 0], [4, 5], [0, 0], [0, 0], [6, 4], [4, 5], [3, 0], [3, 0], [1, 0], [1, 0], [0, 0], [1, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [6, 4], [0, 0], [1, 0], [0, 0], [0, 0], [0, 0], [0, 0], [1, 0], [0, 0], [0, 0], [0, 0]]
---INDIVIDU mutat: --- 1
--- CLASSE MUTADA --- 0
Periode 1  14
Periode 1  15
periodes canviats:  [1, 0]   [1, 0]
-------------------
individu 0
Original  [[[3, 0], [3, 0], [1, 0], [2, 0], [6, 4], [4, 5], [2, 0], [4, 5], [0, 0], [0, 0], [6, 4], [4, 5], [3, 0], [3, 0], [1, 0], [1, 0], [0, 0], [1, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [6, 4], [0, 0], [1, 0], [0, 0], [0, 0], [0, 0], [0

COST 2 [1560.1645384252429, 1560.1645384252429, 1560.1645384252429, 1560.1645384252429, 1560.1645384252429]
COST 3 [1560.1645384252429, 1560.1645384252429, 1560.1645384252429, 1560.1645384252429, 1560.1645384252429]
{0: 1560.1645384252429, 1: 1560.1645384252429, 2: 1560.1645384252429, 3: 1560.1645384252429, 4: 1560.1645384252429}
[(4, 1560.1645384252429), (3, 1560.1645384252429), (2, 1560.1645384252429), (1, 1560.1645384252429), (0, 1560.1645384252429)]
MINIM (0, 1560.1645384252429)
-------------------
individu 0
Original  [[[3, 0], [3, 0], [1, 0], [2, 0], [6, 4], [4, 5], [2, 0], [4, 5], [0, 0], [0, 0], [6, 4], [4, 5], [3, 0], [3, 0], [1, 0], [1, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [6, 4], [0, 0], [1, 0], [0, 0], [0, 0], [0, 0], [0, 0], [1, 0], [1, 0], [0, 0], [0, 0]], [[1, 0], [4, 2], [4, 2], [6, 0], [4, 2], [5, 0], [3, 0], [3, 0], [0, 0], [2, 4], [1, 0], [5, 0], [3, 0], [1, 0], [5, 0], [1, 0], [1, 0], [5, 0], [5, 0], [5, 0], [0, 0], [0, 0], [0, 0], [0,

Antes de canviar  [[3, 0], [3, 0], [1, 0], [2, 0], [6, 4], [4, 5], [2, 0], [4, 5], [0, 0], [0, 0], [6, 4], [4, 5], [3, 0], [3, 0], [1, 0], [1, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [6, 4], [0, 0], [1, 0], [0, 0], [0, 0], [0, 0], [0, 0], [1, 0], [1, 0], [0, 0], [0, 0]]
 
Després de canviar  [[3, 0], [3, 0], [1, 0], [2, 0], [6, 4], [1, 0], [2, 0], [4, 5], [0, 0], [0, 0], [6, 4], [4, 5], [3, 0], [3, 0], [1, 0], [1, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [6, 4], [0, 0], [1, 0], [0, 0], [0, 0], [0, 0], [0, 0], [1, 0], [4, 5], [0, 0], [0, 0]]
---INDIVIDU mutat: --- 1
--- CLASSE MUTADA --- 0
Periode 1  32
Periode 1  5
periodes canviats:  [1, 0]   [4, 5]
Antes de canviar  [[1, 0], [4, 2], [4, 2], [6, 0], [4, 2], [5, 0], [3, 0], [3, 0], [0, 0], [2, 4], [1, 0], [5, 0], [3, 0], [1, 0], [5, 0], [1, 0], [1, 0], [5, 0], [5, 0], [5, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [6, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0,

COST 1 [1498.1607114961168, 1498.1607114961168, 1498.1607114961168, 1498.1607114961168, 1498.1607114961168]
COST 2 [1498.1607114961168, 1498.1607114961168, 1498.1607114961168, 1498.1607114961168, 1498.1607114961168]
COST 3 [1498.1607114961168, 1498.1607114961168, 1498.1607114961168, 1498.1607114961168, 1498.1607114961168]
{0: 1498.1607114961168, 1: 1498.1607114961168, 2: 1498.1607114961168, 3: 1498.1607114961168, 4: 1498.1607114961168}
[(4, 1498.1607114961168), (3, 1498.1607114961168), (2, 1498.1607114961168), (1, 1498.1607114961168), (0, 1498.1607114961168)]
MINIM (0, 1498.1607114961168)
-------------------
individu 0
Original  [[[3, 0], [3, 0], [1, 0], [2, 0], [6, 4], [1, 0], [2, 0], [4, 5], [0, 0], [0, 0], [6, 4], [4, 5], [3, 0], [3, 0], [1, 0], [1, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [6, 4], [0, 0], [1, 0], [0, 0], [0, 0], [0, 0], [0, 0], [1, 0], [4, 5], [0, 0], [0, 0]], [[1, 0], [4, 2], [4, 2], [6, 0], [4, 2], [5, 0], [3, 0], [3, 0], [0, 0], [2, 4],

Individus iguals POB-P_MUT ?  True
-------------------
individu 3
Original  [[[3, 0], [3, 0], [1, 0], [2, 0], [6, 4], [1, 0], [2, 0], [4, 5], [0, 0], [0, 0], [6, 4], [4, 5], [3, 0], [3, 0], [1, 0], [1, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [6, 4], [0, 0], [1, 0], [0, 0], [0, 0], [0, 0], [0, 0], [1, 0], [4, 5], [0, 0], [0, 0]], [[1, 0], [4, 2], [4, 2], [6, 0], [4, 2], [5, 0], [3, 0], [3, 0], [0, 0], [2, 4], [1, 0], [5, 0], [3, 0], [1, 0], [5, 0], [1, 0], [1, 0], [5, 0], [0, 0], [5, 0], [0, 0], [5, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [6, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0]]]
 
Pcopia  [[[3, 0], [3, 0], [1, 0], [2, 0], [6, 4], [1, 0], [2, 0], [4, 5], [0, 0], [0, 0], [6, 4], [4, 5], [3, 0], [3, 0], [1, 0], [1, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [6, 4], [0, 0], [1, 0], [0, 0], [0, 0], [0, 0], [0, 0], [1, 0], [4, 5], [0, 0], [0, 0]], [[1, 0], [4, 2], [4, 2], [6, 0], [4, 2], [5, 0], [3, 0], [3, 0], [

COST 3 [1498.1607114961168, 1498.1607114961168, 1498.1607114961168, 1498.1607114961168, 1498.1607114961168]
{0: 1498.1607114961168, 1: 1498.1607114961168, 2: 1498.1607114961168, 3: 1498.1607114961168, 4: 1498.1607114961168}
[(4, 1498.1607114961168), (3, 1498.1607114961168), (2, 1498.1607114961168), (1, 1498.1607114961168), (0, 1498.1607114961168)]
MINIM (0, 1498.1607114961168)
-------------------
individu 0
Original  [[[3, 0], [3, 0], [1, 0], [2, 0], [6, 4], [1, 0], [2, 0], [4, 5], [0, 0], [0, 0], [6, 4], [4, 5], [3, 0], [3, 0], [1, 0], [1, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [6, 4], [0, 0], [1, 0], [0, 0], [0, 0], [0, 0], [0, 0], [1, 0], [4, 5], [0, 0], [0, 0]], [[1, 0], [4, 2], [4, 2], [6, 0], [4, 2], [5, 0], [3, 0], [3, 0], [0, 0], [2, 4], [1, 0], [5, 0], [3, 0], [1, 0], [5, 0], [1, 0], [1, 0], [5, 0], [0, 0], [5, 0], [0, 0], [5, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [6, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0]]]
 
Pcopia  [[[3

Individus iguals POB-P_MUT ?  True
-------------------
individu 1
Original  [[[3, 0], [3, 0], [1, 0], [2, 0], [6, 4], [1, 0], [2, 0], [4, 5], [0, 0], [0, 0], [6, 4], [4, 5], [3, 0], [3, 0], [1, 0], [1, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [6, 4], [0, 0], [1, 0], [0, 0], [0, 0], [0, 0], [0, 0], [1, 0], [4, 5], [0, 0], [0, 0]], [[1, 0], [4, 2], [4, 2], [6, 0], [4, 2], [5, 0], [3, 0], [3, 0], [0, 0], [2, 4], [1, 0], [5, 0], [3, 0], [1, 0], [5, 0], [1, 0], [1, 0], [5, 0], [0, 0], [5, 0], [0, 0], [5, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [6, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0]]]
 
Pcopia  [[[3, 0], [3, 0], [1, 0], [2, 0], [6, 4], [1, 0], [2, 0], [4, 5], [0, 0], [0, 0], [6, 4], [4, 5], [3, 0], [3, 0], [1, 0], [1, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [6, 4], [0, 0], [1, 0], [0, 0], [0, 0], [0, 0], [0, 0], [1, 0], [4, 5], [0, 0], [0, 0]], [[1, 0], [4, 2], [4, 2], [6, 0], [4, 2], [5, 0], [3, 0], [3, 0], [

 
Individus iguals POB-P_MUT ?  True
Individus iguals POB-P_MUT ?  True
-------------------
individu 4
Original  [[[3, 0], [3, 0], [1, 0], [2, 0], [6, 4], [1, 0], [2, 0], [4, 5], [0, 0], [0, 0], [6, 4], [4, 5], [3, 0], [3, 0], [1, 0], [1, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [6, 4], [0, 0], [1, 0], [0, 0], [0, 0], [0, 0], [0, 0], [1, 0], [4, 5], [0, 0], [0, 0]], [[1, 0], [4, 2], [4, 2], [6, 0], [4, 2], [5, 0], [3, 0], [3, 0], [0, 0], [2, 4], [1, 0], [5, 0], [3, 0], [1, 0], [5, 0], [1, 0], [1, 0], [5, 0], [0, 0], [5, 0], [0, 0], [5, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [6, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0]]]
 
Pcopia  [[[3, 0], [3, 0], [1, 0], [2, 0], [6, 4], [1, 0], [2, 0], [4, 5], [0, 0], [0, 0], [6, 4], [4, 5], [3, 0], [3, 0], [1, 0], [1, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [6, 4], [0, 0], [1, 0], [0, 0], [0, 0], [0, 0], [0, 0], [1, 0], [4, 5], [0, 0], [0, 0]], [[1, 0], [4, 2], [4, 2], [6, 

Individus iguals POB-P_MUT ?  False
Individus iguals POB-P_MUT ?  False
-------------------
individu 3
Original  [[[3, 0], [3, 0], [1, 0], [2, 0], [0, 0], [1, 0], [2, 0], [4, 5], [0, 0], [0, 0], [6, 4], [4, 5], [0, 0], [3, 0], [1, 0], [1, 0], [0, 0], [0, 0], [3, 0], [0, 0], [0, 0], [6, 4], [0, 0], [0, 0], [6, 4], [0, 0], [1, 0], [0, 0], [0, 0], [0, 0], [0, 0], [1, 0], [4, 5], [0, 0], [0, 0]], [[1, 0], [4, 2], [4, 2], [6, 0], [4, 2], [5, 0], [3, 0], [3, 0], [0, 0], [2, 4], [1, 0], [5, 0], [3, 0], [1, 0], [5, 0], [1, 0], [1, 0], [5, 0], [0, 0], [5, 0], [0, 0], [5, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [6, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0]]]
 
Pcopia  [[[3, 0], [3, 0], [1, 0], [2, 0], [0, 0], [1, 0], [2, 0], [4, 5], [0, 0], [0, 0], [6, 4], [4, 5], [0, 0], [3, 0], [1, 0], [1, 0], [0, 0], [0, 0], [3, 0], [0, 0], [0, 0], [6, 4], [0, 0], [0, 0], [6, 4], [0, 0], [1, 0], [0, 0], [0, 0], [0, 0], [0, 0], [1, 0], [4, 5], [0, 0], [0, 0]], [[1, 0], [4, 2], [4, 2], [6, 

COST 1 [1431.0554807087383, 1431.0554807087383, 1431.0554807087383, 1431.0554807087383, 1431.0554807087383]
COST 2 [1431.0554807087383, 1431.0554807087383, 1431.0554807087383, 1431.0554807087383, 1431.0554807087383]
COST 3 [1431.0554807087383, 1431.0554807087383, 1431.0554807087383, 1431.0554807087383, 1431.0554807087383]
{0: 1431.0554807087383, 1: 1431.0554807087383, 2: 1431.0554807087383, 3: 1431.0554807087383, 4: 1431.0554807087383}
[(4, 1431.0554807087383), (3, 1431.0554807087383), (2, 1431.0554807087383), (1, 1431.0554807087383), (0, 1431.0554807087383)]
MINIM (0, 1431.0554807087383)
Antes de canviar  [[1, 0], [4, 2], [4, 2], [6, 0], [4, 2], [5, 0], [3, 0], [3, 0], [0, 0], [2, 4], [1, 0], [5, 0], [3, 0], [1, 0], [5, 0], [1, 0], [1, 0], [5, 0], [0, 0], [5, 0], [0, 0], [5, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [6, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0]]
 
Després de canviar  [[1, 0], [4, 2], [4, 2], [6, 0], [4, 2], [5, 0], [3, 0], [3, 0], [0, 0], [2, 4], [1

COST 2 [1494.4891537796123, 1494.4891537796123, 1494.4891537796123, 1494.4891537796123, 1494.4891537796123]
COST 3 [1494.4891537796123, 1494.4891537796123, 1494.4891537796123, 1494.4891537796123, 1494.4891537796123]
{0: 1494.4891537796123, 1: 1494.4891537796123, 2: 1494.4891537796123, 3: 1494.4891537796123, 4: 1494.4891537796123}
[(4, 1494.4891537796123), (3, 1494.4891537796123), (2, 1494.4891537796123), (1, 1494.4891537796123), (0, 1494.4891537796123)]
MINIM (0, 1494.4891537796123)
-------------------
individu 0
Original  [[[3, 0], [0, 0], [1, 0], [0, 0], [0, 0], [1, 0], [2, 0], [4, 5], [0, 0], [0, 0], [0, 0], [4, 5], [0, 0], [3, 0], [1, 0], [1, 0], [0, 0], [0, 0], [3, 0], [3, 0], [0, 0], [6, 4], [0, 0], [0, 0], [1, 0], [0, 0], [1, 0], [0, 0], [0, 0], [0, 0], [0, 0], [6, 4], [4, 5], [6, 4], [2, 0]], [[1, 0], [4, 2], [4, 2], [6, 0], [4, 2], [5, 0], [3, 0], [3, 0], [0, 0], [2, 4], [1, 0], [0, 0], [3, 0], [1, 0], [5, 0], [1, 0], [1, 0], [5, 0], [5, 0], [5, 0], [0, 0], [5, 0], [0, 0], [0,

COST 1 [1510.6492307087383, 1510.6492307087383, 1510.6492307087383, 1510.6492307087383, 1510.6492307087383]
COST 2 [1510.6492307087383, 1510.6492307087383, 1510.6492307087383, 1510.6492307087383, 1510.6492307087383]
COST 3 [1510.6492307087383, 1510.6492307087383, 1510.6492307087383, 1510.6492307087383, 1510.6492307087383]
{0: 1510.6492307087383, 1: 1510.6492307087383, 2: 1510.6492307087383, 3: 1510.6492307087383, 4: 1510.6492307087383}
[(4, 1510.6492307087383), (3, 1510.6492307087383), (2, 1510.6492307087383), (1, 1510.6492307087383), (0, 1510.6492307087383)]
MINIM (0, 1510.6492307087383)
Antes de canviar  [[1, 0], [4, 2], [4, 2], [6, 0], [4, 2], [5, 0], [3, 0], [3, 0], [0, 0], [2, 4], [1, 0], [0, 0], [3, 0], [1, 0], [5, 0], [1, 0], [1, 0], [5, 0], [5, 0], [5, 0], [0, 0], [5, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [6, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0]]
 
Després de canviar  [[0, 0], [4, 2], [4, 2], [6, 0], [4, 2], [5, 0], [3, 0], [3, 0], [0, 0], [2, 4], [1

POBLACIO [[[[3, 0], [6, 4], [1, 0], [0, 0], [0, 0], [1, 0], [2, 0], [4, 5], [2, 0], [0, 0], [0, 0], [4, 5], [0, 0], [3, 0], [1, 0], [1, 0], [0, 0], [0, 0], [3, 0], [3, 0], [0, 0], [0, 0], [0, 0], [0, 0], [1, 0], [0, 0], [1, 0], [0, 0], [0, 0], [0, 0], [0, 0], [6, 4], [4, 5], [6, 4], [0, 0]], [[0, 0], [4, 2], [5, 0], [6, 0], [4, 2], [5, 0], [3, 0], [3, 0], [0, 0], [2, 4], [1, 0], [0, 0], [3, 0], [1, 0], [5, 0], [1, 0], [1, 0], [5, 0], [4, 2], [5, 0], [0, 0], [5, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [6, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [1, 0], [0, 0]]], [[[3, 0], [6, 4], [1, 0], [0, 0], [0, 0], [1, 0], [2, 0], [4, 5], [2, 0], [0, 0], [0, 0], [4, 5], [0, 0], [3, 0], [1, 0], [1, 0], [0, 0], [0, 0], [3, 0], [3, 0], [0, 0], [0, 0], [0, 0], [0, 0], [1, 0], [0, 0], [1, 0], [0, 0], [0, 0], [0, 0], [0, 0], [6, 4], [4, 5], [6, 4], [0, 0]], [[0, 0], [4, 2], [5, 0], [6, 0], [4, 2], [5, 0], [3, 0], [3, 0], [0, 0], [2, 4], [1, 0], [0, 0], [3, 0], [1, 0], [5, 0], [1, 0], [1, 0], [5, 

Pcopia  [[[3, 0], [6, 4], [1, 0], [0, 0], [0, 0], [1, 0], [2, 0], [4, 5], [2, 0], [0, 0], [0, 0], [4, 5], [0, 0], [3, 0], [1, 0], [1, 0], [0, 0], [0, 0], [3, 0], [3, 0], [0, 0], [0, 0], [0, 0], [0, 0], [1, 0], [0, 0], [1, 0], [0, 0], [0, 0], [0, 0], [0, 0], [6, 4], [4, 5], [6, 4], [0, 0]], [[0, 0], [4, 2], [5, 0], [6, 0], [4, 2], [5, 0], [0, 0], [3, 0], [0, 0], [2, 4], [1, 0], [3, 0], [3, 0], [1, 0], [5, 0], [1, 0], [1, 0], [5, 0], [4, 2], [5, 0], [0, 0], [5, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [6, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [1, 0], [0, 0]]]
 
Mutat [[[3, 0], [6, 4], [1, 0], [0, 0], [0, 0], [1, 0], [2, 0], [4, 5], [2, 0], [0, 0], [0, 0], [4, 5], [0, 0], [3, 0], [1, 0], [1, 0], [0, 0], [0, 0], [3, 0], [3, 0], [0, 0], [0, 0], [0, 0], [0, 0], [1, 0], [0, 0], [1, 0], [0, 0], [0, 0], [0, 0], [0, 0], [6, 4], [4, 5], [6, 4], [0, 0]], [[0, 0], [4, 2], [5, 0], [6, 0], [4, 2], [5, 0], [0, 0], [3, 0], [0, 0], [2, 4], [1, 0], [3, 0], [3, 0], [1, 0], [5, 0], [1, 0], [5, 0],

-------------------
individu 0
Original  [[[3, 0], [6, 4], [1, 0], [0, 0], [0, 0], [1, 0], [2, 0], [4, 5], [2, 0], [0, 0], [0, 0], [4, 5], [0, 0], [3, 0], [1, 0], [1, 0], [0, 0], [0, 0], [3, 0], [3, 0], [0, 0], [0, 0], [0, 0], [0, 0], [1, 0], [0, 0], [1, 0], [0, 0], [0, 0], [0, 0], [0, 0], [6, 4], [4, 5], [6, 4], [0, 0]], [[0, 0], [4, 2], [5, 0], [0, 0], [4, 2], [5, 0], [0, 0], [3, 0], [0, 0], [2, 4], [1, 0], [3, 0], [3, 0], [1, 0], [5, 0], [1, 0], [5, 0], [5, 0], [4, 2], [1, 0], [0, 0], [5, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [6, 0], [0, 0], [0, 0], [6, 0], [0, 0], [0, 0], [1, 0], [0, 0]]]
 
Pcopia  [[[3, 0], [6, 4], [1, 0], [0, 0], [0, 0], [1, 0], [2, 0], [4, 5], [2, 0], [0, 0], [0, 0], [4, 5], [0, 0], [3, 0], [1, 0], [1, 0], [0, 0], [0, 0], [3, 0], [3, 0], [0, 0], [0, 0], [0, 0], [0, 0], [1, 0], [0, 0], [1, 0], [0, 0], [0, 0], [0, 0], [0, 0], [6, 4], [4, 5], [6, 4], [0, 0]], [[0, 0], [4, 2], [5, 0], [0, 0], [4, 2], [5, 0], [0, 0], [3, 0], [0, 0], [2, 4], [1, 0], [3, 0], [3, 

individu 0
Original  [[[3, 0], [6, 4], [1, 0], [0, 0], [0, 0], [1, 0], [2, 0], [4, 5], [2, 0], [0, 0], [0, 0], [4, 5], [0, 0], [3, 0], [1, 0], [1, 0], [0, 0], [0, 0], [3, 0], [3, 0], [0, 0], [0, 0], [0, 0], [0, 0], [1, 0], [0, 0], [1, 0], [0, 0], [0, 0], [0, 0], [0, 0], [6, 4], [4, 5], [6, 4], [0, 0]], [[0, 0], [4, 2], [5, 0], [0, 0], [4, 2], [5, 0], [0, 0], [3, 0], [0, 0], [2, 4], [1, 0], [3, 0], [5, 0], [1, 0], [5, 0], [1, 0], [5, 0], [3, 0], [4, 2], [1, 0], [0, 0], [5, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [6, 0], [0, 0], [0, 0], [6, 0], [0, 0], [0, 0], [1, 0], [0, 0]]]
 
Pcopia  [[[3, 0], [6, 4], [1, 0], [0, 0], [0, 0], [1, 0], [2, 0], [4, 5], [2, 0], [0, 0], [0, 0], [4, 5], [0, 0], [3, 0], [1, 0], [1, 0], [0, 0], [0, 0], [3, 0], [3, 0], [0, 0], [0, 0], [0, 0], [0, 0], [1, 0], [0, 0], [1, 0], [0, 0], [0, 0], [0, 0], [0, 0], [6, 4], [4, 5], [6, 4], [0, 0]], [[0, 0], [4, 2], [5, 0], [0, 0], [4, 2], [5, 0], [0, 0], [3, 0], [0, 0], [2, 4], [1, 0], [3, 0], [5, 0], [1, 0], [5, 0], 

COST M [1426.82524992136, 1426.82524992136, 1426.82524992136, 1426.82524992136, 1426.82524992136]
------------------------------[ 78
COST 1 [1426.82524992136, 1426.82524992136, 1426.82524992136, 1426.82524992136, 1426.82524992136]
COST 2 [1426.82524992136, 1426.82524992136, 1426.82524992136, 1426.82524992136, 1426.82524992136]
COST 3 [1426.82524992136, 1426.82524992136, 1426.82524992136, 1426.82524992136, 1426.82524992136]
{0: 1426.82524992136, 1: 1426.82524992136, 2: 1426.82524992136, 3: 1426.82524992136, 4: 1426.82524992136}
[(4, 1426.82524992136), (3, 1426.82524992136), (2, 1426.82524992136), (1, 1426.82524992136), (0, 1426.82524992136)]
MINIM (0, 1426.82524992136)
-------------------
individu 0
Original  [[[3, 0], [6, 4], [1, 0], [0, 0], [0, 0], [1, 0], [2, 0], [4, 5], [2, 0], [0, 0], [0, 0], [4, 5], [0, 0], [3, 0], [1, 0], [1, 0], [0, 0], [0, 0], [3, 0], [3, 0], [0, 0], [0, 0], [0, 0], [0, 0], [1, 0], [0, 0], [1, 0], [0, 0], [0, 0], [0, 0], [0, 0], [6, 4], [4, 5], [6, 4], [0, 0]],

POB MUTA [[[[3, 0], [6, 4], [1, 0], [0, 0], [0, 0], [1, 0], [2, 0], [4, 5], [2, 0], [0, 0], [0, 0], [4, 5], [0, 0], [3, 0], [1, 0], [1, 0], [0, 0], [0, 0], [3, 0], [3, 0], [0, 0], [0, 0], [0, 0], [0, 0], [1, 0], [0, 0], [1, 0], [0, 0], [0, 0], [0, 0], [0, 0], [6, 4], [4, 5], [6, 4], [0, 0]], [[0, 0], [4, 2], [5, 0], [0, 0], [4, 2], [5, 0], [0, 0], [0, 0], [0, 0], [2, 4], [1, 0], [3, 0], [5, 0], [1, 0], [5, 0], [1, 0], [5, 0], [3, 0], [4, 2], [1, 0], [0, 0], [5, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [6, 0], [0, 0], [3, 0], [6, 0], [0, 0], [0, 0], [1, 0], [0, 0]]], [[[3, 0], [6, 4], [1, 0], [0, 0], [0, 0], [1, 0], [2, 0], [4, 5], [2, 0], [0, 0], [0, 0], [4, 5], [0, 0], [3, 0], [1, 0], [1, 0], [0, 0], [0, 0], [3, 0], [3, 0], [0, 0], [0, 0], [0, 0], [0, 0], [1, 0], [0, 0], [1, 0], [0, 0], [0, 0], [0, 0], [0, 0], [6, 4], [4, 5], [6, 4], [0, 0]], [[0, 0], [4, 2], [5, 0], [0, 0], [4, 2], [5, 0], [0, 0], [0, 0], [0, 0], [2, 4], [1, 0], [3, 0], [5, 0], [1, 0], [5, 0], [1, 0], [5, 0], [3, 

 
Pcopia  [[[3, 0], [6, 4], [1, 0], [0, 0], [0, 0], [1, 0], [2, 0], [4, 5], [2, 0], [0, 0], [0, 0], [4, 5], [0, 0], [3, 0], [1, 0], [1, 0], [0, 0], [0, 0], [3, 0], [3, 0], [0, 0], [0, 0], [0, 0], [0, 0], [1, 0], [0, 0], [1, 0], [0, 0], [0, 0], [0, 0], [0, 0], [6, 4], [4, 5], [6, 4], [0, 0]], [[0, 0], [4, 2], [5, 0], [0, 0], [4, 2], [5, 0], [0, 0], [0, 0], [0, 0], [2, 4], [1, 0], [3, 0], [5, 0], [1, 0], [5, 0], [1, 0], [5, 0], [3, 0], [4, 2], [1, 0], [0, 0], [5, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [6, 0], [0, 0], [3, 0], [6, 0], [0, 0], [0, 0], [1, 0], [0, 0]]]
 
Mutat [[[3, 0], [6, 4], [1, 0], [0, 0], [0, 0], [1, 0], [2, 0], [4, 5], [2, 0], [0, 0], [0, 0], [4, 5], [0, 0], [3, 0], [1, 0], [1, 0], [0, 0], [0, 0], [3, 0], [3, 0], [0, 0], [0, 0], [0, 0], [0, 0], [1, 0], [0, 0], [1, 0], [0, 0], [0, 0], [0, 0], [0, 0], [6, 4], [4, 5], [6, 4], [0, 0]], [[0, 0], [4, 2], [5, 0], [0, 0], [4, 2], [5, 0], [0, 0], [5, 0], [0, 0], [2, 4], [1, 0], [3, 0], [0, 0], [1, 0], [5, 0], [1, 0], [5, 0

COST 1 [1467.0714229922337, 1467.0714229922337, 1467.0714229922337, 1467.0714229922337, 1467.0714229922337]
COST 2 [1467.0714229922337, 1467.0714229922337, 1467.0714229922337, 1467.0714229922337, 1467.0714229922337]
COST 3 [1467.0714229922337, 1467.0714229922337, 1467.0714229922337, 1467.0714229922337, 1467.0714229922337]
{0: 1467.0714229922337, 1: 1467.0714229922337, 2: 1467.0714229922337, 3: 1467.0714229922337, 4: 1467.0714229922337}
[(4, 1467.0714229922337), (3, 1467.0714229922337), (2, 1467.0714229922337), (1, 1467.0714229922337), (0, 1467.0714229922337)]
MINIM (0, 1467.0714229922337)
-------------------
individu 0
Original  [[[3, 0], [6, 4], [1, 0], [0, 0], [0, 0], [1, 0], [2, 0], [4, 5], [2, 0], [0, 0], [0, 0], [4, 5], [0, 0], [3, 0], [1, 0], [1, 0], [0, 0], [0, 0], [3, 0], [3, 0], [0, 0], [0, 0], [0, 0], [0, 0], [1, 0], [0, 0], [1, 0], [0, 0], [0, 0], [0, 0], [0, 0], [6, 4], [4, 5], [6, 4], [0, 0]], [[0, 0], [4, 2], [5, 0], [0, 0], [4, 2], [5, 0], [0, 0], [5, 0], [0, 0], [2, 4],

COST 1 [1476.2901729922337, 1476.2901729922337, 1476.2901729922337, 1476.2901729922337, 1476.2901729922337]
COST 2 [1476.2901729922337, 1476.2901729922337, 1476.2901729922337, 1476.2901729922337, 1476.2901729922337]
COST 3 [1476.2901729922337, 1476.2901729922337, 1476.2901729922337, 1476.2901729922337, 1476.2901729922337]
{0: 1476.2901729922337, 1: 1476.2901729922337, 2: 1476.2901729922337, 3: 1476.2901729922337, 4: 1476.2901729922337}
[(4, 1476.2901729922337), (3, 1476.2901729922337), (2, 1476.2901729922337), (1, 1476.2901729922337), (0, 1476.2901729922337)]
MINIM (0, 1476.2901729922337)
-------------------
individu 0
Original  [[[3, 0], [6, 4], [1, 0], [0, 0], [0, 0], [1, 0], [2, 0], [4, 5], [2, 0], [0, 0], [0, 0], [4, 5], [0, 0], [3, 0], [1, 0], [1, 0], [0, 0], [0, 0], [3, 0], [3, 0], [0, 0], [0, 0], [0, 0], [0, 0], [1, 0], [0, 0], [1, 0], [0, 0], [0, 0], [0, 0], [0, 0], [6, 4], [4, 5], [6, 4], [0, 0]], [[0, 0], [4, 2], [0, 0], [0, 0], [4, 2], [5, 0], [0, 0], [5, 0], [0, 0], [2, 4],

Individus iguals POB-P_MUT ?  True
Individus iguals POB-P_MUT ?  True
-------------------
individu 1
Original  [[[3, 0], [6, 4], [1, 0], [0, 0], [0, 0], [1, 0], [2, 0], [4, 5], [2, 0], [0, 0], [0, 0], [4, 5], [0, 0], [3, 0], [1, 0], [1, 0], [0, 0], [0, 0], [3, 0], [3, 0], [0, 0], [0, 0], [0, 0], [0, 0], [1, 0], [0, 0], [1, 0], [0, 0], [0, 0], [0, 0], [0, 0], [6, 4], [4, 5], [6, 4], [0, 0]], [[0, 0], [4, 2], [0, 0], [0, 0], [4, 2], [5, 0], [0, 0], [5, 0], [0, 0], [2, 4], [1, 0], [3, 0], [0, 0], [1, 0], [5, 0], [1, 0], [5, 0], [3, 0], [4, 2], [1, 0], [0, 0], [5, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [6, 0], [0, 0], [3, 0], [6, 0], [0, 0], [5, 0], [1, 0], [0, 0]]]
 
Pcopia  [[[3, 0], [6, 4], [1, 0], [0, 0], [0, 0], [1, 0], [2, 0], [4, 5], [2, 0], [0, 0], [0, 0], [4, 5], [0, 0], [3, 0], [1, 0], [1, 0], [0, 0], [0, 0], [3, 0], [3, 0], [0, 0], [0, 0], [0, 0], [0, 0], [1, 0], [0, 0], [1, 0], [0, 0], [0, 0], [0, 0], [0, 0], [6, 4], [4, 5], [6, 4], [0, 0]], [[0, 0], [4, 2], [0, 0], [0, 0]

Original  [[[3, 0], [6, 4], [1, 0], [0, 0], [0, 0], [1, 0], [2, 0], [4, 5], [2, 0], [0, 0], [0, 0], [4, 5], [0, 0], [3, 0], [1, 0], [1, 0], [0, 0], [0, 0], [3, 0], [3, 0], [0, 0], [0, 0], [0, 0], [0, 0], [1, 0], [0, 0], [1, 0], [0, 0], [0, 0], [0, 0], [0, 0], [6, 4], [4, 5], [6, 4], [0, 0]], [[0, 0], [4, 2], [0, 0], [0, 0], [4, 2], [5, 0], [0, 0], [5, 0], [0, 0], [2, 4], [1, 0], [3, 0], [0, 0], [1, 0], [5, 0], [1, 0], [5, 0], [3, 0], [4, 2], [1, 0], [0, 0], [5, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [6, 0], [0, 0], [3, 0], [6, 0], [0, 0], [5, 0], [1, 0], [0, 0]]]
 
Pcopia  [[[3, 0], [6, 4], [1, 0], [0, 0], [0, 0], [1, 0], [2, 0], [4, 5], [2, 0], [0, 0], [0, 0], [4, 5], [0, 0], [3, 0], [1, 0], [1, 0], [0, 0], [0, 0], [3, 0], [3, 0], [0, 0], [0, 0], [0, 0], [0, 0], [1, 0], [0, 0], [1, 0], [0, 0], [0, 0], [0, 0], [0, 0], [6, 4], [4, 5], [6, 4], [0, 0]], [[0, 0], [4, 2], [0, 0], [0, 0], [4, 2], [5, 0], [0, 0], [5, 0], [0, 0], [2, 4], [1, 0], [3, 0], [0, 0], [1, 0], [5, 0], [1, 0], [5,

In [26]:
for i in range(100):
    costsTeachers=[[0 for i in range(numTeachers)] for i in range(population)]
    classTimeT=[0 for i in range(population)]
    calculatedCosts=costFunction(poblacio)
        
    costsTeachers=[[0 for i in range(numTeachers)] for i in range(population)]
    calculatedCosts=costFunction(poblacio)
    print("COST 2",calculatedCosts)


    costs={}
    for i in range(population):
        costs[i]=calculatedCosts[i]
    print(costs)

    sorted_costs = sorted(costs.items(), key=operator.itemgetter(1))
    sorted_costs.reverse()
    print(sorted_costs)
    nova_poblacio = []

    # Elitism: aseguram que el millor cromosoma pasa a la següent generacio
    nova_poblacio.append(poblacio[sorted_costs[-1][0]])
    print("MINIM",sorted_costs[-1])
    #print(poblacio[sorted_costs[-1][0]])
    #print(nova_poblacio[0])


    #costsTeachers=[[0 for i in range(numTeachers)] for i in range(population)]
    #print(costFunction(nova_poblacio))
    
    # Selecció dels individus a reproduir
    for i in range(N-1):
        rand = random.random()
        for i in range(len(probability)):
            if (rand > mapped[i]) & (rand <= mapped[i+1]):
                cromo_index = i
                break
        # Aqui s'ha triat el cromosoma que s'ha de reproduir. Ara l'hem de reproduir
        
        nova_poblacio.append(poblacio[sorted_costs[cromo_index][0]])
    #print("poblacio",poblacio)
    #print("nova poblacio",nova_poblacio)
    
    #poblacio_mutada = mutation(nova_poblacio, costsTeachers)
    #costsTeachers=[[0 for i in range(numTeachers)] for i in range(population)]
    #print("costsNP",costFunction(poblacio))
    #costsTeachers=[[0 for i in range(numTeachers)] for i in range(population)]
    #print("costsNP_2",costFunction(poblacio))
    #poblacio = copy.deepcopy(poblacio_mutada)
    poblacio=copy.deepcopy(nova_poblacio)

COST 2 [1535.54399992136, 1535.54399992136, 1535.54399992136, 1535.54399992136, 1535.54399992136]
{0: 1535.54399992136, 1: 1535.54399992136, 2: 1535.54399992136, 3: 1535.54399992136, 4: 1535.54399992136}
[(4, 1535.54399992136), (3, 1535.54399992136), (2, 1535.54399992136), (1, 1535.54399992136), (0, 1535.54399992136)]
MINIM (0, 1535.54399992136)
COST 2 [1535.54399992136, 1535.54399992136, 1535.54399992136, 1535.54399992136, 1535.54399992136]
{0: 1535.54399992136, 1: 1535.54399992136, 2: 1535.54399992136, 3: 1535.54399992136, 4: 1535.54399992136}
[(4, 1535.54399992136), (3, 1535.54399992136), (2, 1535.54399992136), (1, 1535.54399992136), (0, 1535.54399992136)]
MINIM (0, 1535.54399992136)
COST 2 [1535.54399992136, 1535.54399992136, 1535.54399992136, 1535.54399992136, 1535.54399992136]
{0: 1535.54399992136, 1: 1535.54399992136, 2: 1535.54399992136, 3: 1535.54399992136, 4: 1535.54399992136}
[(4, 1535.54399992136), (3, 1535.54399992136), (2, 1535.54399992136), (1, 1535.54399992136), (0, 153

COST 2 [1535.54399992136, 1535.54399992136, 1535.54399992136, 1535.54399992136, 1535.54399992136]
{0: 1535.54399992136, 1: 1535.54399992136, 2: 1535.54399992136, 3: 1535.54399992136, 4: 1535.54399992136}
[(4, 1535.54399992136), (3, 1535.54399992136), (2, 1535.54399992136), (1, 1535.54399992136), (0, 1535.54399992136)]
MINIM (0, 1535.54399992136)
COST 2 [1535.54399992136, 1535.54399992136, 1535.54399992136, 1535.54399992136, 1535.54399992136]
{0: 1535.54399992136, 1: 1535.54399992136, 2: 1535.54399992136, 3: 1535.54399992136, 4: 1535.54399992136}
[(4, 1535.54399992136), (3, 1535.54399992136), (2, 1535.54399992136), (1, 1535.54399992136), (0, 1535.54399992136)]
MINIM (0, 1535.54399992136)
COST 2 [1535.54399992136, 1535.54399992136, 1535.54399992136, 1535.54399992136, 1535.54399992136]
{0: 1535.54399992136, 1: 1535.54399992136, 2: 1535.54399992136, 3: 1535.54399992136, 4: 1535.54399992136}
[(4, 1535.54399992136), (3, 1535.54399992136), (2, 1535.54399992136), (1, 1535.54399992136), (0, 153

COST 2 [1535.54399992136, 1535.54399992136, 1535.54399992136, 1535.54399992136, 1535.54399992136]
{0: 1535.54399992136, 1: 1535.54399992136, 2: 1535.54399992136, 3: 1535.54399992136, 4: 1535.54399992136}
[(4, 1535.54399992136), (3, 1535.54399992136), (2, 1535.54399992136), (1, 1535.54399992136), (0, 1535.54399992136)]
MINIM (0, 1535.54399992136)
COST 2 [1535.54399992136, 1535.54399992136, 1535.54399992136, 1535.54399992136, 1535.54399992136]
{0: 1535.54399992136, 1: 1535.54399992136, 2: 1535.54399992136, 3: 1535.54399992136, 4: 1535.54399992136}
[(4, 1535.54399992136), (3, 1535.54399992136), (2, 1535.54399992136), (1, 1535.54399992136), (0, 1535.54399992136)]
MINIM (0, 1535.54399992136)
COST 2 [1535.54399992136, 1535.54399992136, 1535.54399992136, 1535.54399992136, 1535.54399992136]
{0: 1535.54399992136, 1: 1535.54399992136, 2: 1535.54399992136, 3: 1535.54399992136, 4: 1535.54399992136}
[(4, 1535.54399992136), (3, 1535.54399992136), (2, 1535.54399992136), (1, 1535.54399992136), (0, 153

COST 2 [1535.54399992136, 1535.54399992136, 1535.54399992136, 1535.54399992136, 1535.54399992136]
{0: 1535.54399992136, 1: 1535.54399992136, 2: 1535.54399992136, 3: 1535.54399992136, 4: 1535.54399992136}
[(4, 1535.54399992136), (3, 1535.54399992136), (2, 1535.54399992136), (1, 1535.54399992136), (0, 1535.54399992136)]
MINIM (0, 1535.54399992136)
COST 2 [1535.54399992136, 1535.54399992136, 1535.54399992136, 1535.54399992136, 1535.54399992136]
{0: 1535.54399992136, 1: 1535.54399992136, 2: 1535.54399992136, 3: 1535.54399992136, 4: 1535.54399992136}
[(4, 1535.54399992136), (3, 1535.54399992136), (2, 1535.54399992136), (1, 1535.54399992136), (0, 1535.54399992136)]
MINIM (0, 1535.54399992136)
COST 2 [1535.54399992136, 1535.54399992136, 1535.54399992136, 1535.54399992136, 1535.54399992136]
{0: 1535.54399992136, 1: 1535.54399992136, 2: 1535.54399992136, 3: 1535.54399992136, 4: 1535.54399992136}
[(4, 1535.54399992136), (3, 1535.54399992136), (2, 1535.54399992136), (1, 1535.54399992136), (0, 153

*Teacher unavailability: For each teacher and for each time period this teacher is assigned to a class, while he/she is unavailable at school the corresponding day, the following cost is added: HCW ∗ BASE3.

*Teacher assigned in more than one class: For each teacher and for each time period, if this teacher is assigned to more than one class, for example, to k classes, the following cost is added: HCW ∗ BASEk


Teacher lessons’ dispersion: For each teacher the following subcost is added: IDWT ∗ HOURS ∗ BASEDAYS, where
HOURS is the total number of time periods that are different compared to the ideal dispersion teacher’s timetable
and DAYS is the number of days in the teacher’s timetable that such a declination from the ideal case exists.